const activities = [
  // ─── ATHENS (12) ──────────────────────────────────────────────────────────────
  {
    id: 'act-acropolis-guided-tour',
    tab: 'activities',
    name: 'Acropolis Guided Tour',
    city: 'Athens',
    category: 'tour',
    description:
      'Expert-led walking tour through the hilltop citadel covering the Parthenon, Erechtheion, and Temple of Athena Nike. Your licensed archaeologist guide brings 2,500 years of history to life with stories you won\'t find in guidebooks.',
    photos: [
      'https://images.unsplash.com/photo-1655916355045-0f94f47b398c?w=800&q=80',
      'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1655916355045-0f94f47b398c?w=800&q=80',
    address: 'Acropolis Hill, Athens 105 58',
    coordinates: { lat: 37.9715, lng: 23.7257 },
    hours: 'Apr-Oct: 8:00 AM - 8:00 PM; Nov-Mar: 8:00 AM - 5:00 PM',
    costEstimate: '$$$',
    costNote: '€40-60 per person including entrance fee and guide',
    duration: '2.5 hours',
    difficulty: 'moderate',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Book the earliest morning slot to beat cruise-ship crowds',
      'Wear sturdy shoes — the marble paths are extremely slippery',
      'Bring at least 1 liter of water per person in summer',
    ],
    tags: ['ancient ruins', 'history', 'must-see', 'Athens'],
  },
  {
    id: 'act-athens-food-tour',
    tab: 'activities',
    name: 'Athens Food Tour (Monastiraki & Psyrri)',
    city: 'Athens',
    category: 'experience',
    description:
      'Taste your way through Athens\' most vibrant food neighborhoods. Sample loukoumades, souvlaki, local cheeses, and seasonal mezedes at hidden tavernas and market stalls across Monastiraki and Psyrri.',
    photos: [
      'https://images.unsplash.com/photo-1655916355039-c30f9b4c967c?w=800&q=80',
      'https://images.unsplash.com/photo-1594048234320-f2caf3dac5c0?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1655916355039-c30f9b4c967c?w=800&q=80',
    address: 'Monastiraki Square, Athens 105 55',
    coordinates: { lat: 37.9763, lng: 23.7259 },
    hours: '10:00 AM - 2:00 PM or 5:00 PM - 9:00 PM',
    costEstimate: '$$',
    costNote: '€65-80 per person, all tastings included',
    duration: '3.5 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Come hungry — you\'ll visit 7-8 stops with generous portions',
      'The evening tour has a livelier atmosphere with locals dining out',
      'Let the guide know about dietary restrictions at least 24 hours ahead',
    ],
    tags: ['food', 'street food', 'local culture', 'Athens'],
  },
  {
    id: 'act-greek-cooking-class',
    tab: 'activities',
    name: 'Greek Cooking Class',
    city: 'Athens',
    category: 'cooking',
    description:
      'Learn to prepare classic Greek dishes — moussaka, tzatziki, and spanakopita — in a hands-on kitchen workshop. Includes a market visit to select fresh ingredients, followed by a communal meal of everything you cooked.',
    photos: [
      'https://images.unsplash.com/photo-1505883973882-490ee8cd39da?w=800&q=80',
      'https://images.unsplash.com/photo-1503152394-c571994fd383?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1505883973882-490ee8cd39da?w=800&q=80',
    address: 'Athinas 36, Athens 105 51',
    coordinates: { lat: 37.9784, lng: 23.7263 },
    hours: '10:00 AM - 2:30 PM',
    costEstimate: '$$$',
    costNote: '€75-90 per person including ingredients and meal',
    duration: '4 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Classes are limited to 10-12 people — book at least a week in advance',
      'You\'ll receive printed recipes to take home',
      'Vegetarian alternatives are available if requested ahead of time',
    ],
    tags: ['cooking', 'food', 'hands-on', 'Athens'],
  },
  {
    id: 'act-athens-street-art-walk',
    tab: 'activities',
    name: 'Athens Street Art Walk (Exarchia & Psyrri)',
    city: 'Athens',
    category: 'cultural',
    description:
      'Explore the vibrant murals and graffiti of Exarchia and Psyrri with a local artist guide. Athens\' street art scene exploded during the financial crisis and now ranks among Europe\'s most dynamic urban canvases.',
    photos: [
      'https://images.unsplash.com/photo-1664111943859-fb9637c97723?w=800&q=80',
      'https://images.unsplash.com/photo-1669706341369-1e40498d2e40?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1664111943859-fb9637c97723?w=800&q=80',
    address: 'Plateia Exarchion, Athens 106 81',
    coordinates: { lat: 37.9862, lng: 23.7342 },
    hours: '10:00 AM - 1:00 PM',
    costEstimate: '$$',
    costNote: '€35-45 per person',
    duration: '3 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Wear comfortable walking shoes — you\'ll cover around 4 km',
      'Bring a camera with a wide-angle lens for large murals',
      'The neighborhood is edgier than tourist Athens, but perfectly safe during the day',
    ],
    tags: ['street art', 'urban culture', 'walking', 'Athens'],
  },
  {
    id: 'act-changing-of-the-guard',
    tab: 'activities',
    name: 'Changing of the Guard Ceremony',
    city: 'Athens',
    category: 'cultural',
    description:
      'Watch the iconic Evzone soldiers perform the ceremonial changing of the guard at the Tomb of the Unknown Soldier in Syntagma Square. The elaborate Sunday morning ceremony features the full regiment in traditional foustanella uniforms.',
    photos: [
      'https://images.unsplash.com/photo-1605707141131-aa742dcf4671?w=800&q=80',
      'https://images.unsplash.com/photo-1676831159775-604ec16e1c1f?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1605707141131-aa742dcf4671?w=800&q=80',
    address: 'Syntagma Square, Athens 105 63',
    coordinates: { lat: 37.9755, lng: 23.7348 },
    hours: 'Every hour on the hour; grand ceremony Sundays at 11:00 AM',
    costEstimate: 'Free',
    costNote: 'No charge',
    duration: '30 minutes',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'The full Sunday ceremony is far more impressive than the hourly change',
      'Stand to the side rather than directly in front for the best photo angle',
      'Combine with a walk through the National Garden right behind the Parliament',
    ],
    tags: ['free', 'ceremony', 'cultural', 'Athens'],
  },
  {
    id: 'act-delphi-day-trip',
    tab: 'activities',
    name: 'Delphi Guided Day Trip',
    city: 'Athens',
    category: 'tour',
    description:
      'Full-day organized bus excursion to the ancient Oracle of Delphi, the "navel of the world." Visit the Temple of Apollo, the ancient theater, and the Delphi Archaeological Museum with an expert guide.',
    photos: [
      'https://images.unsplash.com/photo-1655916355033-cb0bfd30f8df?w=800&q=80',
      'https://images.unsplash.com/photo-1697455621664-d97023b8ee7d?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1655916355033-cb0bfd30f8df?w=800&q=80',
    address: 'Pickup from Syntagma Square, Athens',
    coordinates: { lat: 38.4824, lng: 22.5010 },
    hours: 'Departure 8:00 AM, return ~6:30 PM',
    costEstimate: '$$$',
    costNote: '€85-110 per person including transport, guide, and entrance fees',
    duration: '10 hours',
    difficulty: 'moderate',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Most tours include a lunch stop in the mountain village of Arachova',
      'Bring layers — Delphi sits at 600 m elevation and can be 10°C cooler than Athens',
      'Request a small-group tour (max 15 people) for a much better experience',
    ],
    tags: ['day trip', 'ancient ruins', 'history', 'Athens'],
  },
  {
    id: 'act-plaka-walking-tour',
    tab: 'activities',
    name: 'Plaka Walking Tour',
    city: 'Athens',
    category: 'tour',
    description:
      'Wander the charming historic streets of Plaka, the oldest neighborhood in Athens, nestled at the foot of the Acropolis. Discover Byzantine churches, neoclassical mansions, and hidden squares with a knowledgeable local guide.',
    photos: [
      'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
      'https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
    address: 'Plaka, Athens 105 58',
    coordinates: { lat: 37.9725, lng: 23.7300 },
    hours: '9:30 AM - 12:00 PM or 4:00 PM - 6:30 PM',
    costEstimate: '$',
    costNote: '€20-30 per person (some are tip-based free tours)',
    duration: '2.5 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'The afternoon tour is cooler and catches the golden-hour light on the buildings',
      'Visit the tiny Church of Panagia Kapnikarea — one of Athens\' oldest',
      'End with a Greek coffee at one of the shaded cafes in Anafiotika',
    ],
    tags: ['walking tour', 'history', 'architecture', 'Athens'],
  },
  {
    id: 'act-athenian-pottery-workshop',
    tab: 'activities',
    name: 'Athenian Pottery Workshop',
    city: 'Athens',
    category: 'cultural',
    description:
      'Try your hand at ancient Greek pottery techniques in a small studio near the Ceramicus district. A master ceramicist guides you through shaping, decorating, and painting your own piece using methods unchanged for millennia.',
    photos: [
      'https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?w=800&q=80',
      'https://images.unsplash.com/photo-1676831410404-ee79a62c8188?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?w=800&q=80',
    address: 'Kerameikou 28, Athens 104 36',
    coordinates: { lat: 37.9782, lng: 23.7140 },
    hours: '10:00 AM - 1:00 PM or 3:00 PM - 6:00 PM',
    costEstimate: '$$',
    costNote: '€45-60 per person including materials and firing',
    duration: '2.5 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Wear old clothes — clay splatter is inevitable and part of the fun',
      'Your finished piece can be shipped home for an additional fee of around €15',
      'Great for families with kids aged 8 and up',
    ],
    tags: ['workshop', 'pottery', 'hands-on', 'Athens'],
  },
  {
    id: 'act-athens-bike-tour',
    tab: 'activities',
    name: 'Athens Bike Tour',
    city: 'Athens',
    category: 'tour',
    description:
      'See more of Athens in less time on a guided cycling tour through the historic center. Pedal past the Ancient Agora, Hadrian\'s Library, the Roman Forum, and Thissio while your guide shares insider stories at each stop.',
    photos: [
      'https://images.unsplash.com/photo-1676831410404-ee79a62c8188?w=800&q=80',
      'https://images.unsplash.com/photo-1666192179043-5aad64280d63?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1676831410404-ee79a62c8188?w=800&q=80',
    address: 'Athinas 29, Athens 105 54',
    coordinates: { lat: 37.9770, lng: 23.7255 },
    hours: '9:00 AM - 12:30 PM or 4:00 PM - 7:30 PM',
    costEstimate: '$$',
    costNote: '€35-45 per person including bike and helmet',
    duration: '3 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'The route is mostly flat — suitable for all fitness levels',
      'Electric bikes are available for a €10 supplement',
      'The afternoon tour avoids the worst of the summer heat',
    ],
    tags: ['cycling', 'sightseeing', 'active', 'Athens'],
  },
  {
    id: 'act-hammam-spa-experience',
    tab: 'activities',
    name: 'Hammam Spa Experience',
    city: 'Athens',
    category: 'wellness',
    description:
      'Unwind in a beautifully restored Ottoman-era hammam in the heart of Athens. The ritual includes a steam room session, full-body scrub, and aromatherapy massage in candlelit marble chambers.',
    photos: [
      'https://images.unsplash.com/photo-1594048234320-f2caf3dac5c0?w=800&q=80',
      'https://images.unsplash.com/photo-1669706341369-1e40498d2e40?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1594048234320-f2caf3dac5c0?w=800&q=80',
    address: 'Melidoni 1, Athens 105 53',
    coordinates: { lat: 37.9788, lng: 23.7215 },
    hours: '10:00 AM - 10:00 PM',
    costEstimate: '$$$',
    costNote: '€50-80 per person for the full ritual package',
    duration: '1.5 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Book at least 3 days in advance during peak season',
      'The couples\' package offers a private room for a more intimate experience',
      'Hydrate well before and after — the steam room is intense',
    ],
    tags: ['spa', 'wellness', 'relaxation', 'Athens'],
  },
  {
    id: 'act-national-garden-walk',
    tab: 'activities',
    name: 'National Garden Walk',
    city: 'Athens',
    category: 'experience',
    description:
      'Escape the city heat in Athens\' lush National Garden, a 15-hectare green oasis right behind Parliament. Stroll past ancient ruins, duck ponds, a small botanical museum, and shaded pathways lined with towering palm trees and bougainvillea.',
    photos: [
      'https://images.unsplash.com/photo-1676831159775-604ec16e1c1f?w=800&q=80',
      'https://images.unsplash.com/photo-1655916355045-0f94f47b398c?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1676831159775-604ec16e1c1f?w=800&q=80',
    address: 'National Garden, Leoforos Vasilissis Amalias, Athens 105 57',
    coordinates: { lat: 37.9728, lng: 23.7365 },
    hours: 'Sunrise to sunset daily',
    costEstimate: 'Free',
    costNote: 'No charge',
    duration: '1-2 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'The garden has a small playground and duck pond — perfect for families with young children',
      'Enter from the Zappeion side for the most scenic approach',
      'Pair it with the Changing of the Guard at nearby Syntagma Square',
    ],
    tags: ['free', 'nature', 'family-friendly', 'Athens'],
  },
  {
    id: 'act-sunset-philopappos-hill',
    tab: 'activities',
    name: 'Sunset at Philopappos Hill',
    city: 'Athens',
    category: 'hiking',
    description:
      'Climb the gentle pine-covered paths of Philopappos Hill for the best sunset view of the Acropolis in all of Athens. The hilltop monument and surrounding parkland offer a peaceful alternative to crowded rooftop bars.',
    photos: [
      'https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?w=800&q=80',
      'https://images.unsplash.com/photo-1697455621664-d97023b8ee7d?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?w=800&q=80',
    address: 'Philopappos Hill, Dionysiou Areopagitou, Athens 117 42',
    coordinates: { lat: 37.9674, lng: 23.7220 },
    hours: 'Open 24 hours; best at sunset',
    costEstimate: 'Free',
    costNote: 'No charge',
    duration: '1.5 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Arrive 45 minutes before sunset to claim a good spot on the rocks',
      'Bring a picnic blanket and snacks — there are no vendors on the hill',
      'The path from the Dionysiou Areopagitou pedestrian street is the easiest approach',
    ],
    tags: ['free', 'sunset', 'views', 'Athens'],
  },

  // ─── NAFPLIO (12) ─────────────────────────────────────────────────────────────
  {
    id: 'act-climb-palamidi-fortress',
    tab: 'activities',
    name: 'Climb Palamidi Fortress (999 Steps)',
    city: 'Nafplio',
    category: 'hiking',
    description:
      'Ascend the legendary 999 stone steps to the Venetian fortress of Palamidi towering 216 meters above Nafplio. The panoramic views of the Argolic Gulf and the town\'s terracotta rooftops are the best reward in the Peloponnese.',
    photos: [
      'https://images.unsplash.com/photo-1751060867787-3d28ea3d6e22?w=800&q=80',
      'https://images.unsplash.com/photo-1677336068327-e0e545dbf13a?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1751060867787-3d28ea3d6e22?w=800&q=80',
    address: 'Palamidi Fortress, Nafplio 211 00',
    coordinates: { lat: 37.5621, lng: 22.8016 },
    hours: 'Apr-Oct: 8:00 AM - 8:00 PM; Nov-Mar: 8:30 AM - 3:30 PM',
    costEstimate: '$',
    costNote: '€8 entrance fee',
    duration: '2 hours',
    difficulty: 'hard',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Start early in the morning to avoid the midday heat',
      'Bring at least 1.5 liters of water — there\'s no shade on the steps',
      'You can also drive to the top and walk down the steps instead',
    ],
    tags: ['hiking', 'fortress', 'views', 'Nafplio'],
  },
  {
    id: 'act-mycenae-epidaurus-tour',
    tab: 'activities',
    name: 'Mycenae & Epidaurus Guided Tour',
    city: 'Nafplio',
    category: 'tour',
    description:
      'Visit two of Greece\'s most important ancient sites in a single day. Explore the Lion Gate and royal tombs at Mycenae, then marvel at the acoustically perfect ancient theater at Epidaurus.',
    photos: [
      'https://images.unsplash.com/photo-1588250977873-b15f82d8176f?w=800&q=80',
      'https://images.unsplash.com/photo-1759063293478-1d2a9348d696?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1588250977873-b15f82d8176f?w=800&q=80',
    address: 'Pickup from Nafplio town center',
    coordinates: { lat: 37.7308, lng: 22.7563 },
    hours: '9:00 AM - 4:00 PM',
    costEstimate: '$$$',
    costNote: '€70-90 per person including transport, guide, and entrance fees',
    duration: '7 hours',
    difficulty: 'moderate',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Test the acoustics at Epidaurus — drop a coin on the center stone and listen from the top row',
      'Mycenae is exposed with no shade; wear a hat and sunscreen',
      'Ask your guide about the curse of the House of Atreus for the full dramatic story',
    ],
    tags: ['ancient ruins', 'day trip', 'history', 'Nafplio'],
  },
  {
    id: 'act-kayaking-nafplio-bay',
    tab: 'activities',
    name: 'Kayaking in Nafplio Bay',
    city: 'Nafplio',
    category: 'water sport',
    description:
      'Paddle a sea kayak around the tiny island fortress of Bourtzi in the middle of Nafplio Bay. The calm waters and stunning backdrop of Palamidi fortress make this one of the most scenic paddles in Greece.',
    photos: [
      'https://images.unsplash.com/photo-1602348143971-0c5c97d23367?w=800&q=80',
      'https://images.unsplash.com/photo-1602348709085-bc5720f99fd5?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1602348143971-0c5c97d23367?w=800&q=80',
    address: 'Nafplio Waterfront, Akti Miaouli, Nafplio 211 00',
    coordinates: { lat: 37.5672, lng: 22.7955 },
    hours: '9:00 AM - 6:00 PM (seasonal)',
    costEstimate: '$$',
    costNote: '€35-50 per person for a 2-hour guided paddle',
    duration: '2 hours',
    difficulty: 'moderate',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Morning sessions have calmer water and better light for photos',
      'Waterproof phone pouches are usually provided but bring your own to be safe',
      'No prior kayaking experience needed — guides provide a full briefing',
    ],
    tags: ['kayaking', 'water sport', 'Bourtzi', 'Nafplio'],
  },
  {
    id: 'act-olive-oil-tasting',
    tab: 'activities',
    name: 'Olive Oil Tasting Experience',
    city: 'Nafplio',
    category: 'experience',
    description:
      'Visit a family-run olive grove in the Peloponnese countryside for a guided tasting of single-estate extra virgin olive oils. Learn about harvesting, cold pressing, and how to distinguish quality oils by aroma and flavor.',
    photos: [
      'https://images.unsplash.com/photo-1728454978463-31b0233e41c2?w=800&q=80',
      'https://images.unsplash.com/photo-1775649135113-51d710c37983?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1728454978463-31b0233e41c2?w=800&q=80',
    address: 'Ligourio, Argolida, Peloponnese 211 00',
    coordinates: { lat: 37.6032, lng: 23.0425 },
    hours: '10:00 AM - 4:00 PM',
    costEstimate: '$$',
    costNote: '€25-40 per person including tasting and light snacks',
    duration: '2 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Ask about Koroneiki olives — the Peloponnese\'s prized variety',
      'You can usually buy bottles directly at much lower prices than in shops',
      'Best combined with a visit to Epidaurus, which is just 15 minutes away',
    ],
    tags: ['olive oil', 'food', 'countryside', 'Nafplio'],
  },
  {
    id: 'act-ancient-olympia-tour',
    tab: 'activities',
    name: 'Ancient Olympia Guided Tour',
    city: 'Nafplio',
    category: 'tour',
    description:
      'Journey to the birthplace of the Olympic Games for a guided tour of the ancient stadium, Temple of Zeus, and the excellent archaeological museum. Stand on the original starting blocks where athletes competed nearly 3,000 years ago.',
    photos: [
      'https://images.unsplash.com/photo-1589528391483-dbdc76a9bd58?w=800&q=80',
      'https://images.unsplash.com/photo-1537649019808-a87dc561d0cc?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1589528391483-dbdc76a9bd58?w=800&q=80',
    address: 'Ancient Olympia, Elis, Peloponnese 270 65',
    coordinates: { lat: 37.6388, lng: 21.6299 },
    hours: '8:00 AM - 7:30 PM (summer); 8:00 AM - 3:00 PM (winter)',
    costEstimate: '$$$',
    costNote: '€90-120 per person including transport from Nafplio, guide, and entrance',
    duration: '10 hours (full day)',
    difficulty: 'moderate',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'It\'s a 2.5-hour drive each way from Nafplio — start early',
      'The museum\'s Hermes of Praxiteles sculpture is worth lingering over',
      'Race your travel companions on the ancient stadium track — it\'s a tradition',
    ],
    tags: ['ancient ruins', 'Olympics', 'day trip', 'Nafplio'],
  },
  {
    id: 'act-arvanitia-beach-swim',
    tab: 'activities',
    name: 'Swimming at Arvanitia Beach',
    city: 'Nafplio',
    category: 'beach',
    description:
      'Nafplio\'s beloved town beach sits tucked beneath the Akronafplia fortress, just a 10-minute walk from the old town. The pebbly beach has crystal-clear water and dramatic cliff scenery that makes it feel far more remote than it is.',
    photos: [
      'https://images.unsplash.com/photo-1760324271160-92ac8f84b5f6?w=800&q=80',
      'https://images.unsplash.com/photo-1662241947856-00c0fbe79c9b?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1760324271160-92ac8f84b5f6?w=800&q=80',
    address: 'Arvanitia Beach, Nafplio 211 00',
    coordinates: { lat: 37.5620, lng: 22.8010 },
    hours: 'Daylight hours',
    costEstimate: 'Free',
    costNote: 'Free entry; sunbed and umbrella rental €8-10',
    duration: '2-3 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Bring water shoes — the beach is pebbly and the rocks can be sharp',
      'There\'s a small canteen for drinks and snacks but no full restaurant',
      'Walk the scenic Arvanitia promenade path that hugs the cliff to reach the beach',
    ],
    tags: ['beach', 'swimming', 'free', 'Nafplio'],
  },
  {
    id: 'act-nafplio-bicycle-tour',
    tab: 'activities',
    name: 'Bicycle Tour of Nafplio',
    city: 'Nafplio',
    category: 'experience',
    description:
      'Cruise the coastal promenade and surrounding countryside on a guided bicycle tour. Ride past Bourtzi views, orange groves, and quiet seaside paths with stops for photos and local snacks.',
    photos: [
      'https://images.unsplash.com/photo-1559576587-ddf2a82285d1?w=800&q=80',
      'https://images.unsplash.com/photo-1751060867787-3d28ea3d6e22?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1559576587-ddf2a82285d1?w=800&q=80',
    address: 'Nafplio Waterfront, Bouboulinas St, Nafplio 211 00',
    coordinates: { lat: 37.5677, lng: 22.7943 },
    hours: '9:00 AM - 12:00 PM or 4:00 PM - 7:00 PM',
    costEstimate: '$$',
    costNote: '€30-40 per person including bike rental and guide',
    duration: '3 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'The afternoon tour catches the golden-hour light along the coast',
      'Routes are mostly flat — suitable for casual cyclists',
      'Helmets are provided but bring your own sunglasses and sunscreen',
    ],
    tags: ['cycling', 'coastal', 'outdoors', 'Nafplio'],
  },
  {
    id: 'act-epidaurus-theater-performance',
    tab: 'activities',
    name: 'Epidaurus Theater Performance (Summer Festival)',
    city: 'Nafplio',
    category: 'cultural',
    description:
      'Experience a live performance of ancient Greek drama in the 2,300-year-old theater of Epidaurus during the Athens & Epidaurus Festival. The acoustics are so perfect you can hear a whisper from the back row of the 14,000-seat amphitheater.',
    photos: [
      'https://images.unsplash.com/photo-1759063293478-1d2a9348d696?w=800&q=80',
      'https://images.unsplash.com/photo-1588250977873-b15f82d8176f?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1759063293478-1d2a9348d696?w=800&q=80',
    address: 'Ancient Theatre of Epidaurus, Ligourio 210 52',
    coordinates: { lat: 37.5961, lng: 23.0792 },
    hours: 'Performances typically at 9:00 PM (Fri-Sat, Jun-Aug)',
    costEstimate: '$$',
    costNote: '€20-50 per ticket depending on seating',
    duration: '3 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Book tickets well in advance through the Athens Festival website — popular shows sell out',
      'Bring a cushion or blanket — the stone seats get uncomfortable after two hours',
      'Performances are usually in modern Greek with English surtitles',
    ],
    tags: ['theater', 'ancient', 'festival', 'Nafplio'],
  },
  {
    id: 'act-peloponnese-coast-drive',
    tab: 'activities',
    name: 'Drive the Peloponnese Coast',
    city: 'Nafplio',
    category: 'experience',
    description:
      'Take a scenic self-drive along the eastern Peloponnese coastline from Nafplio through fishing villages, hidden coves, and olive-covered hillsides. Stop at Tolo, Drepano, and the beaches of Argolida along the way.',
    photos: [
      'https://images.unsplash.com/photo-1677336068327-e0e545dbf13a?w=800&q=80',
      'https://images.unsplash.com/photo-1537649019808-a87dc561d0cc?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1677336068327-e0e545dbf13a?w=800&q=80',
    address: 'Nafplio to Tolo coastal road, Peloponnese',
    coordinates: { lat: 37.5230, lng: 22.8700 },
    hours: 'Daylight hours',
    costEstimate: '$',
    costNote: 'Fuel costs only — approximately €15-20 for the loop',
    duration: '4-5 hours with stops',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Rent a car in Nafplio for the day — about €40-50 including insurance',
      'Stop in Tolo for a seafood lunch at one of the tavernas on the waterfront',
      'The road to Drepano has a beautiful viewpoint overlooking the bay',
    ],
    tags: ['scenic drive', 'coastal', 'road trip', 'Nafplio'],
  },
  {
    id: 'act-snorkeling-tolo-beach',
    tab: 'activities',
    name: 'Snorkeling at Tolo Beach',
    city: 'Nafplio',
    category: 'water sport',
    description:
      'Explore the clear shallow waters off Tolo Beach, about 12 km from Nafplio. The rocky edges of the bay are home to sea urchins, colorful wrasse, and octopus, making it ideal for snorkeling right from shore.',
    photos: [
      'https://images.unsplash.com/photo-1592685294766-463e3340d43b?w=800&q=80',
      'https://images.unsplash.com/photo-1647990837483-4126e311d3f8?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1592685294766-463e3340d43b?w=800&q=80',
    address: 'Tolo Beach, Tolo 210 56, Argolida',
    coordinates: { lat: 37.5195, lng: 22.8720 },
    hours: 'Daylight hours',
    costEstimate: '$',
    costNote: '€10-15 for mask and snorkel rental; free if you bring your own',
    duration: '2-3 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Head to the rocky area on the left side of the beach for the best underwater life',
      'Visibility is best in the morning before afternoon winds stir up sediment',
      'Combine with lunch at one of Tolo\'s beachfront fish tavernas',
    ],
    tags: ['snorkeling', 'water sport', 'beach', 'Nafplio'],
  },
  {
    id: 'act-horseback-riding-argolida',
    tab: 'activities',
    name: 'Horseback Riding in Argolida',
    city: 'Nafplio',
    category: 'experience',
    description:
      'Ride through the orange groves and olive orchards of the Argolid plain on a guided horseback excursion. Routes pass by ancient ruins and offer sweeping views of the Argolic Gulf, suitable for beginners and experienced riders alike.',
    photos: [
      'https://images.unsplash.com/photo-1760324271160-92ac8f84b5f6?w=800&q=80',
      'https://images.unsplash.com/photo-1589528391483-dbdc76a9bd58?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1760324271160-92ac8f84b5f6?w=800&q=80',
    address: 'Argolida Riding Club, Drepano, Argolida 211 00',
    coordinates: { lat: 37.5470, lng: 22.8460 },
    hours: '8:00 AM - 12:00 PM or 4:00 PM - 7:00 PM',
    costEstimate: '$$',
    costNote: '€45-65 per person for a 1.5-hour guided ride',
    duration: '1.5 hours',
    difficulty: 'moderate',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Wear long pants and closed-toe shoes with a small heel',
      'Morning rides are cooler and the horses are more energetic',
      'Children under 12 can ride with a handler leading the horse',
    ],
    tags: ['horseback riding', 'countryside', 'outdoors', 'Nafplio'],
  },
  {
    id: 'act-cooking-class-nafplio',
    tab: 'activities',
    name: 'Cooking Class in Nafplio',
    city: 'Nafplio',
    category: 'cooking',
    description:
      'Learn to cook traditional Peloponnesian recipes in a home kitchen overlooking Nafplio\'s old town. Prepare dishes like pastitsio, gemista (stuffed tomatoes), and galaktoboureko using family recipes passed down through generations.',
    photos: [
      'https://images.unsplash.com/photo-1662241947856-00c0fbe79c9b?w=800&q=80',
      'https://images.unsplash.com/photo-1728454978463-31b0233e41c2?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1662241947856-00c0fbe79c9b?w=800&q=80',
    address: 'Staikopoulou 22, Nafplio 211 00',
    coordinates: { lat: 37.5670, lng: 22.7975 },
    hours: '10:00 AM - 2:00 PM',
    costEstimate: '$$',
    costNote: '€55-70 per person including ingredients and full meal',
    duration: '3.5 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Classes are kept intimate with a maximum of 8 guests',
      'The host often shares stories about local food traditions between courses',
      'Ask about seasonal specials — spring classes feature wild greens and artichokes',
    ],
    tags: ['cooking', 'food', 'local culture', 'Nafplio'],
  },

  // ─── CRETE (10) ───────────────────────────────────────────────────────────────
  {
    id: 'act-knossos-palace-guided-tour',
    tab: 'activities',
    name: 'Knossos Palace Guided Tour',
    city: 'Crete',
    category: 'tour',
    description:
      'Explore the legendary Minoan palace of Knossos with an expert archaeologist guide. Walk through the Throne Room, royal quarters, and vibrant frescoes of Europe\'s oldest civilization, dating back over 4,000 years.',
    photos: [
      'https://images.unsplash.com/photo-1570303345338-e1f0eddf4946?w=800&q=80',
      'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1570303345338-e1f0eddf4946?w=800&q=80',
    address: 'Knossos Archaeological Site, Heraklion, Crete 714 09',
    coordinates: { lat: 35.2979, lng: 25.1633 },
    hours: 'Apr-Oct: 8:00 AM - 8:00 PM; Nov-Mar: 8:00 AM - 5:00 PM',
    costEstimate: '$$',
    costNote: '€15 entrance fee plus €30-40 for a licensed guide',
    duration: '2.5 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Arrive right at opening to beat the cruise-ship crowds that peak at 10 AM',
      'A guide is essential — the site is confusing and poorly signed without one',
      'Combine with a visit to the Heraklion Archaeological Museum to see the original frescoes',
    ],
    tags: ['ancient ruins', 'history', 'must-see', 'Crete'],
  },
  {
    id: 'act-heraklion-food-tour',
    tab: 'activities',
    name: 'Heraklion Food Tour',
    city: 'Crete',
    category: 'experience',
    description:
      'Taste your way through Heraklion\'s old town on a guided food tour of Cretan cuisine. Sample dakos, graviera cheese, fresh-baked kaltsounia, local honey, and seasonal mezedes at market stalls and family-run shops.',
    photos: [
      'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
      'https://images.unsplash.com/photo-1504512485720-7d83a16ee930?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    address: 'Central Market (1866 Street), Heraklion, Crete 712 02',
    coordinates: { lat: 35.3394, lng: 25.1335 },
    hours: '10:00 AM - 2:00 PM or 5:00 PM - 9:00 PM',
    costEstimate: '$$',
    costNote: '€55-70 per person, all tastings included',
    duration: '3.5 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Come hungry — you\'ll visit 6-8 stops with generous Cretan portions',
      'The morning tour passes through the bustling central market at its liveliest',
      'Ask the guide to explain the Cretan diet and why locals live so long',
    ],
    tags: ['food', 'street food', 'local culture', 'Crete'],
  },
  {
    id: 'act-cretan-cooking-class',
    tab: 'activities',
    name: 'Cretan Cooking Class',
    city: 'Crete',
    category: 'cooking',
    description:
      'Learn to prepare authentic Cretan specialties — dakos, kalitsounia, and herb-rich lamb dishes — in a hands-on kitchen workshop. Includes a visit to a local garden to pick fresh herbs, followed by a communal meal of everything you cooked.',
    photos: [
      'https://images.unsplash.com/photo-1504512485720-7d83a16ee930?w=800&q=80',
      'https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1504512485720-7d83a16ee930?w=800&q=80',
    address: 'Archanes Village, Heraklion, Crete 701 00',
    coordinates: { lat: 35.2348, lng: 25.1624 },
    hours: '10:00 AM - 2:30 PM',
    costEstimate: '$$',
    costNote: '€65-80 per person including ingredients and meal',
    duration: '4 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Classes are limited to 10 guests — book at least a week in advance',
      'You\'ll receive printed recipes to take home and recreate the dishes',
      'Vegetarian alternatives are available if requested at least 24 hours ahead',
    ],
    tags: ['cooking', 'food', 'hands-on', 'Crete'],
  },
  {
    id: 'act-snorkeling-amnissos-beach',
    tab: 'activities',
    name: 'Snorkeling at Amnissos Beach',
    city: 'Crete',
    category: 'water sport',
    description:
      'Explore the crystal-clear shallow waters off Amnissos Beach, just 7 km east of Heraklion. The rocky outcrops and sandy patches are home to colorful fish, sea urchins, and occasional octopus, perfect for snorkeling right from shore.',
    photos: [
      'https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=800&q=80',
      'https://images.unsplash.com/photo-1598889272668-64e8b2d04a1b?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=800&q=80',
    address: 'Amnissos Beach, Heraklion, Crete 714 14',
    coordinates: { lat: 35.3362, lng: 25.1852 },
    hours: 'Daylight hours',
    costEstimate: '$',
    costNote: '€10-15 for mask and snorkel rental; free if you bring your own',
    duration: '2-3 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Head to the rocky area on the east side of the beach for the best marine life',
      'Visibility is best in the morning before afternoon winds pick up',
      'Bring water shoes — the entry can be rocky in places',
    ],
    tags: ['snorkeling', 'water sport', 'beach', 'Crete'],
  },
  {
    id: 'act-harbor-walk-koules-sunset',
    tab: 'activities',
    name: 'Harbor Walk & Koules Sunset',
    city: 'Crete',
    category: 'experience',
    description:
      'Stroll along the historic Venetian harbor of Heraklion and out to the imposing Koules fortress at the harbor entrance. Time your walk for sunset to watch the sky turn golden over the sea from the fortress ramparts.',
    photos: [
      'https://images.unsplash.com/photo-1598889272668-64e8b2d04a1b?w=800&q=80',
      'https://images.unsplash.com/photo-1587130906985-0e1e97d1c6e5?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1598889272668-64e8b2d04a1b?w=800&q=80',
    address: 'Venetian Harbor, Heraklion, Crete 712 02',
    coordinates: { lat: 35.3452, lng: 25.1355 },
    hours: 'Harbor: open 24 hours; Koules Fortress: 8:00 AM - 7:00 PM (summer)',
    costEstimate: '$',
    costNote: '€4 entrance to Koules fortress',
    duration: '1.5 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Arrive 30 minutes before sunset to explore the fortress before the light show',
      'The harbor promenade is lined with cafes if you want to sit and enjoy the view',
      'The fortress has excellent views of the harbor and the open sea from its rooftop',
    ],
    tags: ['sunset', 'free', 'walking', 'Crete'],
  },
  {
    id: 'act-heraklion-bike-tour',
    tab: 'activities',
    name: 'Heraklion Bike Tour',
    city: 'Crete',
    category: 'tour',
    description:
      'Cycle through Heraklion\'s old town and along the coastal road on a guided bike tour. Pedal past Venetian walls, the Morosini Fountain, the harbor, and seaside promenades while your guide shares stories of the city\'s layered history.',
    photos: [
      'https://images.unsplash.com/photo-1587130906985-0e1e97d1c6e5?w=800&q=80',
      'https://images.unsplash.com/photo-1572803655444-0c52dba3e1de?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1587130906985-0e1e97d1c6e5?w=800&q=80',
    address: 'Lion Square (Plateia Venizelou), Heraklion, Crete 712 02',
    coordinates: { lat: 35.3390, lng: 25.1343 },
    hours: '9:00 AM - 12:30 PM or 4:00 PM - 7:30 PM',
    costEstimate: '$$',
    costNote: '€35-45 per person including bike and helmet',
    duration: '3 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'The route is mostly flat — suitable for casual cyclists of all fitness levels',
      'Electric bikes are available for a €10 supplement',
      'The afternoon tour avoids the midday heat and catches golden-hour light',
    ],
    tags: ['cycling', 'sightseeing', 'active', 'Crete'],
  },
  {
    id: 'act-cretaquarium-visit',
    tab: 'activities',
    name: 'Visit CretAquarium',
    city: 'Crete',
    category: 'experience',
    description:
      'Discover the marine life of the Mediterranean at CretAquarium, one of the largest aquariums in Europe. Over 2,500 sea creatures across 60 tanks showcase sharks, jellyfish, loggerhead turtles, and colorful reef fish native to Cretan waters.',
    photos: [
      'https://images.unsplash.com/photo-1572803655444-0c52dba3e1de?w=800&q=80',
      'https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1572803655444-0c52dba3e1de?w=800&q=80',
    address: 'CretAquarium, Gournes, Heraklion, Crete 710 03',
    coordinates: { lat: 35.3320, lng: 25.2816 },
    hours: 'Apr-Oct: 9:30 AM - 7:00 PM; Nov-Mar: 9:30 AM - 5:00 PM',
    costEstimate: '$',
    costNote: '€10 adults, €6 children (5-17 years)',
    duration: '1.5-2 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Perfect rainy-day or midday-heat activity when the beach is too hot',
      'The shark and jellyfish tanks are the highlights — take your time there',
      'Great for families with young children who need a break from ruins and hiking',
    ],
    tags: ['aquarium', 'family-friendly', 'indoor', 'Crete'],
  },
  {
    id: 'act-cretan-olive-oil-tasting',
    tab: 'activities',
    name: 'Cretan Olive Oil Tasting',
    city: 'Crete',
    category: 'experience',
    description:
      'Visit a traditional Cretan olive press in the hills south of Heraklion for a guided tasting of single-estate extra virgin olive oils. Learn about ancient harvesting methods, cold pressing, and why Cretan oil is considered among the finest in the world.',
    photos: [
      'https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=800&q=80',
      'https://images.unsplash.com/photo-1597223557791-6e4e3a94c7ea?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=800&q=80',
    address: 'Archanes Olive Mill, Archanes, Heraklion, Crete 701 00',
    coordinates: { lat: 35.2335, lng: 25.1610 },
    hours: '10:00 AM - 4:00 PM',
    costEstimate: '$$',
    costNote: '€25-35 per person including tasting and light snacks',
    duration: '2 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Ask about the Koroneiki and Tsounati olive varieties unique to Crete',
      'You can buy bottles directly at the press for much lower prices than in shops',
      'Best combined with the Cretan cooking class in nearby Archanes village',
    ],
    tags: ['olive oil', 'food', 'countryside', 'Crete'],
  },
  {
    id: 'act-day-boat-trip-coast',
    tab: 'activities',
    name: 'Day Boat Trip Along the Coast',
    city: 'Crete',
    category: 'boat trip',
    description:
      'Sail from Heraklion harbor along the northern Cretan coast to explore hidden coves, sea caves, and secluded beaches inaccessible by land. Includes swimming stops and a freshly prepared lunch on board.',
    photos: [
      'https://images.unsplash.com/photo-1597223557791-6e4e3a94c7ea?w=800&q=80',
      'https://images.unsplash.com/photo-1564594985645-4427056e22e2?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1597223557791-6e4e3a94c7ea?w=800&q=80',
    address: 'Heraklion Marina, Heraklion, Crete 712 02',
    coordinates: { lat: 35.3465, lng: 25.1380 },
    hours: 'Departure 9:30 AM, return ~4:30 PM',
    costEstimate: '$$$',
    costNote: '€85-120 per person including lunch and snorkeling gear',
    duration: '7 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Book a small-group trip (max 12 people) for a much better experience',
      'Bring reef-safe sunscreen and a hat — there is limited shade on deck',
      'The swimming stops have spectacular snorkeling right from the boat',
    ],
    tags: ['boat trip', 'coastal', 'swimming', 'Crete'],
  },
  {
    id: 'act-pottery-workshop-thrapsano',
    tab: 'activities',
    name: 'Pottery Workshop in Thrapsano',
    city: 'Crete',
    category: 'cultural',
    description:
      'Shape clay on a traditional wheel in Thrapsano, Crete\'s historic pottery village. A local master potter teaches you centuries-old techniques used to create the island\'s iconic pitharia storage jars, and you take home your finished piece.',
    photos: [
      'https://images.unsplash.com/photo-1564594985645-4427056e22e2?w=800&q=80',
      'https://images.unsplash.com/photo-1570303345338-e1f0eddf4946?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1564594985645-4427056e22e2?w=800&q=80',
    address: 'Thrapsano Village, Heraklion, Crete 700 06',
    coordinates: { lat: 35.2270, lng: 25.2535 },
    hours: '10:00 AM - 1:00 PM or 3:00 PM - 6:00 PM',
    costEstimate: '$$',
    costNote: '€40-55 per person including materials and one finished piece',
    duration: '2.5 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Wear old clothes — clay splatter is inevitable and part of the fun',
      'Thrapsano itself is a charming village worth exploring before or after the class',
      'Suitable for all ages including children over 6',
    ],
    tags: ['pottery', 'workshop', 'hands-on', 'Crete'],
  },

  // ─── SANTORINI (11) ───────────────────────────────────────────────────────────
  {
    id: 'act-fira-to-oia-caldera-walk',
    tab: 'activities',
    name: 'Fira-to-Oia Caldera Walk',
    city: 'Santorini',
    category: 'hiking',
    description:
      'Hike the spectacular 10 km cliff-edge trail from Fira to Oia along the caldera rim. Pass through Firostefani, Imerovigli, and along dramatic volcanic cliffs with endless Aegean views.',
    photos: [
      'https://images.unsplash.com/photo-1690324075771-f8b43b7b1bbc?w=800&q=80',
      'https://images.unsplash.com/photo-1580855453606-7a02774c686c?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1690324075771-f8b43b7b1bbc?w=800&q=80',
    address: 'Start: Fira town center, Santorini 847 00',
    coordinates: { lat: 36.4167, lng: 25.4315 },
    hours: 'Daylight hours',
    costEstimate: 'Free',
    costNote: 'No charge — just bring water and snacks',
    duration: '4-5 hours',
    difficulty: 'moderate',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Start early from Fira (before 8 AM) to avoid midday heat and crowds',
      'Walk Fira to Oia so you finish at the sunset viewpoint',
      'Bring at least 2 liters of water — there are few shops along the trail',
    ],
    tags: ['hiking', 'caldera', 'views', 'Santorini'],
  },
  {
    id: 'act-volcano-hot-springs-boat',
    tab: 'activities',
    name: 'Volcano & Hot Springs Boat Trip',
    city: 'Santorini',
    category: 'boat trip',
    description:
      'Sail from Fira\'s old port to the volcanic island of Nea Kameni and hike to the steaming crater rim. Then swim in the warm sulfur hot springs at Palea Kameni before returning to Santorini.',
    photos: [
      'https://images.unsplash.com/photo-1724412575242-5d1a62458751?w=800&q=80',
      'https://images.unsplash.com/photo-1654118890957-136cbada631e?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1724412575242-5d1a62458751?w=800&q=80',
    address: 'Old Port, Fira, Santorini 847 00',
    coordinates: { lat: 36.4080, lng: 25.4265 },
    hours: '10:00 AM - 3:00 PM (departures vary)',
    costEstimate: '$$',
    costNote: '€30-45 per person including boat and volcano entrance fee',
    duration: '5 hours',
    difficulty: 'moderate',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'The hot springs contain sulfur — wear a dark swimsuit as it may stain',
      'Bring sturdy shoes for the volcanic rock trail on Nea Kameni',
      'Take the cable car down to the old port rather than walking the 588 steps',
    ],
    tags: ['volcano', 'boat trip', 'hot springs', 'Santorini'],
  },
  {
    id: 'act-catamaran-sunset-cruise',
    tab: 'activities',
    name: 'Catamaran Sunset Cruise',
    city: 'Santorini',
    category: 'boat trip',
    description:
      'Sail the caldera aboard a luxury catamaran as the sun sets behind Oia. Includes swimming stops at the Red Beach and White Beach, plus a freshly prepared barbecue dinner on board with soft drinks and juices.',
    photos: [
      'https://images.unsplash.com/photo-1652179326115-943d168c4cb2?w=800&q=80',
      'https://images.unsplash.com/photo-1676730056228-7e38cbb88edc?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1652179326115-943d168c4cb2?w=800&q=80',
    address: 'Vlychada Marina, Santorini 847 00',
    coordinates: { lat: 36.3475, lng: 25.4292 },
    hours: 'Sunset cruise departs ~3:00 PM, returns ~8:30 PM',
    costEstimate: '$$$',
    costNote: '€150-200 per person for a semi-private catamaran (max 20 guests)',
    duration: '5 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Book a semi-private tour (max 20 people) rather than a large boat for a better experience',
      'Bring a light jacket — the wind picks up significantly after sunset',
      'Apply reef-safe sunscreen before the swimming stops',
    ],
    tags: ['sailing', 'sunset', 'luxury', 'Santorini'],
  },
  {
    id: 'act-scuba-diving-amoudi-bay',
    tab: 'activities',
    name: 'Scuba Diving at Amoudi Bay',
    city: 'Santorini',
    category: 'water sport',
    description:
      'Dive into the crystal-clear waters of Amoudi Bay below Oia to explore underwater volcanic rock formations, swim-throughs, and colorful marine life. Suitable for both beginners and certified divers.',
    photos: [
      'https://images.unsplash.com/photo-1625936716555-5577fb317a24?w=800&q=80',
      'https://images.unsplash.com/photo-1654118891010-3c067d8c25cc?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1625936716555-5577fb317a24?w=800&q=80',
    address: 'Amoudi Bay, Oia, Santorini 847 02',
    coordinates: { lat: 36.4641, lng: 25.3723 },
    hours: '8:30 AM - 4:00 PM',
    costEstimate: '$$$',
    costNote: '€80-110 per person for a 2-tank dive; €60 for discovery dive (beginners)',
    duration: '3 hours',
    difficulty: 'moderate',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'No certification needed for the discovery dive — just basic swimming ability',
      'Visibility reaches 30+ meters in summer, making it exceptional for photography',
      'Don\'t fly within 24 hours of diving — schedule this early in your Santorini stay',
    ],
    tags: ['scuba diving', 'water sport', 'underwater', 'Santorini'],
  },
  {
    id: 'act-akrotiri-archaeological-tour',
    tab: 'activities',
    name: 'Akrotiri Archaeological Guided Tour',
    city: 'Santorini',
    category: 'tour',
    description:
      'Explore the remarkably preserved Minoan city of Akrotiri with an expert archaeologist guide. Often called the "Pompeii of the Aegean," this Bronze Age settlement was buried by the volcanic eruption around 1600 BC.',
    photos: [
      'https://images.unsplash.com/photo-1651045691067-d02eaaf96205?w=800&q=80',
      'https://images.unsplash.com/photo-1652179467601-e313edb8473f?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1651045691067-d02eaaf96205?w=800&q=80',
    address: 'Akrotiri Archaeological Site, Santorini 847 00',
    coordinates: { lat: 36.3517, lng: 25.4038 },
    hours: 'Apr-Oct: 8:00 AM - 8:00 PM; Nov-Mar: 8:00 AM - 3:00 PM',
    costEstimate: '$$',
    costNote: '€12 entrance fee plus €30-40 for a private guide',
    duration: '2 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'A guide is essential here — without context, the ruins are hard to interpret',
      'The site is covered by a modern roof so it\'s a great option on hot days',
      'Combine with the nearby Red Beach, which is a 10-minute walk away',
    ],
    tags: ['archaeology', 'ancient ruins', 'history', 'Santorini'],
  },
  {
    id: 'act-santorini-cooking-class',
    tab: 'activities',
    name: 'Santorini Cooking Class',
    city: 'Santorini',
    category: 'cooking',
    description:
      'Learn to cook Greek island cuisine using Santorini\'s unique local ingredients — cherry tomatoes, white eggplant, capers, and fava beans. Classes are held in a traditional kitchen with caldera views.',
    photos: [
      'https://images.unsplash.com/photo-1565741478311-b3e79a17bfe3?w=800&q=80',
      'https://images.unsplash.com/photo-1654118891010-3c067d8c25cc?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1565741478311-b3e79a17bfe3?w=800&q=80',
    address: 'Firostefani, Santorini 847 00',
    coordinates: { lat: 36.4260, lng: 25.4305 },
    hours: '10:00 AM - 2:00 PM or 5:00 PM - 9:00 PM',
    costEstimate: '$$$',
    costNote: '€85-110 per person including all ingredients and meal',
    duration: '4 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'The evening class lets you dine as the sun sets over the caldera',
      'Ask to learn tomatokeftedes — Santorini\'s signature tomato fritters',
      'Classes book out 1-2 weeks in advance during peak summer season',
    ],
    tags: ['cooking', 'food', 'local cuisine', 'Santorini'],
  },
  {
    id: 'act-oia-photography-workshop',
    tab: 'activities',
    name: 'Photography Workshop at Oia',
    city: 'Santorini',
    category: 'experience',
    description:
      'Join a professional photographer for a hands-on workshop capturing the world-famous Oia sunset and blue-domed churches. Learn composition, exposure settings, and editing techniques at the most photogenic spot in the Cyclades.',
    photos: [
      'https://images.unsplash.com/photo-1580855453606-7a02774c686c?w=800&q=80',
      'https://images.unsplash.com/photo-1690324075771-f8b43b7b1bbc?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1580855453606-7a02774c686c?w=800&q=80',
    address: 'Oia Castle, Oia, Santorini 847 02',
    coordinates: { lat: 36.4618, lng: 25.3755 },
    hours: '2 hours before sunset (time varies by season)',
    costEstimate: '$$$',
    costNote: '€75-100 per person for a small-group workshop (max 8)',
    duration: '2.5 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Bring a camera with manual mode — even a modern smartphone works well',
      'Arrive at the meeting point early; Oia gets extremely crowded at sunset',
      'The instructor usually shares secret viewpoints away from the main castle crowds',
    ],
    tags: ['photography', 'sunset', 'workshop', 'Santorini'],
  },
  {
    id: 'act-horseback-riding-santorini',
    tab: 'activities',
    name: 'Horseback Riding on the Beach',
    city: 'Santorini',
    category: 'experience',
    description:
      'Ride along the black volcanic sand of Perivolos Beach at sunrise or sunset on a guided horseback excursion. The dramatic contrast of dark sand, turquoise water, and the caldera cliffs in the distance makes this an unforgettable experience.',
    photos: [
      'https://images.unsplash.com/photo-1663051861448-44f15fa8f74d?w=800&q=80',
      'https://images.unsplash.com/photo-1654118890950-e4b0785175e5?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1663051861448-44f15fa8f74d?w=800&q=80',
    address: 'Perivolos Beach, Santorini 847 03',
    coordinates: { lat: 36.3510, lng: 25.4530 },
    hours: '8:00 AM - 10:00 AM or 5:00 PM - 7:00 PM',
    costEstimate: '$$',
    costNote: '€60-80 per person for a 1.5-hour ride',
    duration: '1.5 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'The sunset ride is magical but books up fast — reserve at least a week ahead',
      'No experience needed; the horses are calm and handlers walk alongside beginners',
      'Wear long pants and closed-toe shoes for comfort and safety',
    ],
    tags: ['horseback riding', 'beach', 'outdoors', 'Santorini'],
  },
  {
    id: 'act-sup-perivolos',
    tab: 'activities',
    name: 'Stand-Up Paddleboarding at Perivolos',
    city: 'Santorini',
    category: 'water sport',
    description:
      'Glide across the calm waters off Perivolos Beach on a stand-up paddleboard. The sheltered black-sand beach offers ideal conditions for beginners, with lessons available and boards for rent by the hour.',
    photos: [
      'https://images.unsplash.com/photo-1544327404-f6aed3d39dbf?w=800&q=80',
      'https://images.unsplash.com/photo-1545006547-eee2b9beddff?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1544327404-f6aed3d39dbf?w=800&q=80',
    address: 'Perivolos Beach, Santorini 847 03',
    coordinates: { lat: 36.3505, lng: 25.4540 },
    hours: '9:00 AM - 6:00 PM (May-Oct)',
    costEstimate: '$',
    costNote: '€15-20 per hour for board rental; €35 for a 1-hour lesson',
    duration: '1-2 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Morning has the flattest water — afternoon winds can make it challenging for beginners',
      'Wear a rash guard or apply plenty of waterproof sunscreen — the sun reflects intensely off the water',
      'Ask about the guided coastal SUP tour that paddles along the cliffs',
    ],
    tags: ['paddleboarding', 'water sport', 'beach', 'Santorini'],
  },
  {
    id: 'act-sunset-kayaking-caldera',
    tab: 'activities',
    name: 'Sunset Kayaking Along the Caldera',
    city: 'Santorini',
    category: 'water sport',
    description:
      'Paddle a sea kayak along the base of Santorini\'s towering caldera cliffs as the sun drops toward the horizon. The guided tour includes stops at sea caves and a swimming break, with the volcanic landscape glowing orange and gold around you.',
    photos: [
      'https://images.unsplash.com/photo-1652179467601-e313edb8473f?w=800&q=80',
      'https://images.unsplash.com/photo-1676730056228-7e38cbb88edc?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1652179467601-e313edb8473f?w=800&q=80',
    address: 'Mesa Pigadia, Santorini 847 00',
    coordinates: { lat: 36.3990, lng: 25.4200 },
    hours: 'Departs 2-3 hours before sunset (time varies by season)',
    costEstimate: '$$',
    costNote: '€55-75 per person including equipment and guide',
    duration: '3 hours',
    difficulty: 'moderate',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Basic fitness is needed — you\'ll paddle about 5 km total',
      'Bring a dry bag for your phone and camera',
      'Wear water shoes for getting in and out at the rocky launch point',
    ],
    tags: ['kayaking', 'sunset', 'caldera', 'Santorini'],
  },
  {
    id: 'act-pottery-class-megalochori',
    tab: 'activities',
    name: 'Pottery Class in Megalochori',
    city: 'Santorini',
    category: 'cultural',
    description:
      'Shape volcanic clay on a traditional pottery wheel in the quiet village of Megalochori. A local ceramicist teaches you the basics of throwing and glazing, and your finished piece is fired and shipped to your home address.',
    photos: [
      'https://images.unsplash.com/photo-1651045691067-d02eaaf96205?w=800&q=80',
      'https://images.unsplash.com/photo-1565741478311-b3e79a17bfe3?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1651045691067-d02eaaf96205?w=800&q=80',
    address: 'Megalochori village, Santorini 847 00',
    coordinates: { lat: 36.3790, lng: 25.4270 },
    hours: '10:00 AM - 1:00 PM or 4:00 PM - 7:00 PM',
    costEstimate: '$$',
    costNote: '€50-65 per person including materials and international shipping',
    duration: '2 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'The clay used is mixed with local volcanic earth, giving it a distinctive dark color',
      'Megalochori itself is worth exploring — far quieter and more authentic than Fira or Oia',
      'Suitable for all ages, including children over 6',
    ],
    tags: ['pottery', 'workshop', 'hands-on', 'Santorini'],
  },
];

export default activities;
