const eat = [
  // ========== ATHENS (12) ==========
  {
    id: 'eat-tzitzikas-kai-mermigas',
    tab: 'eat',
    name: 'Tzitzikas kai Mermigas',
    city: 'Athens',
    category: 'traditional',
    description:
      'A modern Greek taverna steps from Syntagma Square that reinvents classic regional recipes with flair. The menu rotates seasonally and showcases dishes from across the Greek mainland and islands, served in a lively, contemporary setting.',
    photos: [
      'https://images.unsplash.com/photo-1655916355045-0f94f47b398c?w=800&q=80',
      'https://images.unsplash.com/photo-1655916355039-c30f9b4c967c?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1655916355045-0f94f47b398c?w=800&q=80',
    address: 'Mitropoleos 12-14, Syntagma, Athens 105 63',
    coordinates: { lat: 37.9755, lng: 23.7348 },
    hours: 'Daily 12:00 PM – 12:00 AM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€15–25 per person',
    phone: '+30 210 324 7607',
    website: 'https://www.tzitzikas.gr',
    bookingRequired: false,
    tips: [
      'Try the Cretan dakos salad and the lamb chops with lemon potatoes.',
      'Grab a table on the pedestrianized street for prime people-watching.',
      'Lunch is less crowded than dinner — arrive by 1 PM for easy seating.',
    ],
    tags: ['syntagma', 'modern-greek', 'taverna'],
  },
  {
    id: 'eat-karamanlidika-tou-fani',
    tab: 'eat',
    name: 'Karamanlidika tou Fani',
    city: 'Athens',
    category: 'mezedes',
    description:
      'Part delicatessen, part meze restaurant, this beloved spot near the Central Market is a shrine to the culinary heritage of Asia Minor Greeks. The cured meats are made in-house and the meze-style plates are inventive yet deeply traditional. Hanging pastourma and louza adorn the ceiling.',
    photos: [
      'https://images.unsplash.com/photo-1505883973882-490ee8cd39da?w=800&q=80',
      'https://images.unsplash.com/photo-1664111943859-fb9637c97723?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1505883973882-490ee8cd39da?w=800&q=80',
    address: 'Evripidou 52, Athens 105 54',
    coordinates: { lat: 37.9801, lng: 23.7249 },
    hours: 'Tue–Sat 10:00 AM – 11:00 PM, Sun 10:00 AM – 6:00 PM, Mon closed',
    closedOn: 'Monday',
    costEstimate: '$$',
    costNote: '€20–35 per person',
    phone: '+30 210 325 4184',
    website: 'https://karamanlidika.gr',
    bookingRequired: true,
    tips: [
      'Ask for the tasting platter if you want to try a bit of everything.',
      'Pick up packaged pastourma and loukaniko from the deli counter as souvenirs.',
      'Reserve ahead for dinner — it fills up fast, especially on weekends.',
    ],
    tags: ['deli', 'asia-minor', 'cured-meats', 'meze'],
  },
  {
    id: 'eat-kostas-souvlaki',
    tab: 'eat',
    name: 'Kostas Souvlaki',
    city: 'Athens',
    category: 'souvlaki',
    description:
      'A legendary hole-in-the-wall souvlaki joint tucked into Agia Irini Square, operating since 1950. The menu is refreshingly simple: pork or beef souvlaki wrapped in warm pita with tomato, onion, and a secret spicy sauce. Most people eat standing in the square — and every bite is worth it.',
    photos: [
      'https://images.unsplash.com/photo-1503152394-c571994fd383?w=800&q=80',
      'https://images.unsplash.com/photo-1655916355033-cb0bfd30f8df?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1503152394-c571994fd383?w=800&q=80',
    address: 'Pentelis 5, Agia Irini Square, Athens 105 60',
    coordinates: { lat: 37.9771, lng: 23.7273 },
    hours: 'Mon–Sat 10:30 AM – 4:00 PM or until sold out, Sun closed',
    closedOn: 'Sunday',
    costEstimate: '$',
    costNote: '€3–5 per wrap',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Get there before noon — they regularly sell out by early afternoon.',
      'Order one pork and one beef to compare; the spicy sauce is the star.',
      'Cash only, no seating — grab and eat in the charming square.',
    ],
    tags: ['souvlaki', 'street-food', 'budget'],
  },
  {
    id: 'eat-o-thanasis',
    tab: 'eat',
    name: 'O Thanasis',
    city: 'Athens',
    category: 'street food',
    description:
      'An iconic kebab restaurant anchoring the edge of Monastiraki Square since 1964. Famous for its juicy ground-beef kebabs on fluffy pita, served with chopped onion and grilled tomato. The large outdoor terrace offers a front-row seat to the Monastiraki action with the Acropolis looming overhead.',
    photos: [
      'https://images.unsplash.com/photo-1697455621664-d97023b8ee7d?w=800&q=80',
      'https://images.unsplash.com/photo-1676831410404-ee79a62c8188?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1697455621664-d97023b8ee7d?w=800&q=80',
    address: 'Mitropoleos 69, Monastiraki, Athens 105 55',
    coordinates: { lat: 37.9762, lng: 23.7264 },
    hours: 'Daily 9:00 AM – 2:30 AM',
    closedOn: undefined,
    costEstimate: '$',
    costNote: '€6–10 per person',
    phone: '+30 210 324 4705',
    website: null,
    bookingRequired: false,
    tips: [
      'Order the kebab plate with extra pita — the bread soaks up the juices perfectly.',
      'Great for a late-night bite after bar-hopping in Monastiraki.',
      'Sit outside for views of Monastiraki Square and the Acropolis at night.',
    ],
    tags: ['kebab', 'monastiraki', 'late-night'],
  },
  {
    id: 'eat-cafe-avissinia',
    tab: 'eat',
    name: 'Cafe Avissinia',
    city: 'Athens',
    category: 'taverna',
    description:
      'A bohemian gem perched on Avissinia Square in the heart of the Monastiraki flea market. The eclectic interior is filled with antiques and mismatched furniture, and the weekend atmosphere comes alive with live rebetiko music. The menu features refined Greek comfort food like slow-cooked lamb and mushroom saganaki.',
    photos: [
      'https://images.unsplash.com/photo-1655916355045-0f94f47b398c?w=800&q=80',
      'https://images.unsplash.com/photo-1664111943859-fb9637c97723?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1664111943859-fb9637c97723?w=800&q=80',
    address: 'Kinetou 7, Avissinia Square, Monastiraki, Athens 105 55',
    coordinates: { lat: 37.9768, lng: 23.7237 },
    hours: 'Tue–Sat 11:00 AM – 12:00 AM, Sun 11:00 AM – 7:00 PM, Mon closed',
    closedOn: 'Monday',
    costEstimate: '$$',
    costNote: '€18–30 per person',
    phone: '+30 210 321 7047',
    website: null,
    bookingRequired: true,
    tips: [
      'Visit on a Saturday or Sunday for live rebetiko music — truly magical.',
      'Reserve a balcony table for views over the flea market square.',
      'The mushroom saganaki and slow-roasted lamb shank are standout dishes.',
    ],
    tags: ['flea-market', 'live-music', 'bohemian'],
  },
  {
    id: 'eat-diporto-agoras',
    tab: 'eat',
    name: 'Diporto Agoras',
    city: 'Athens',
    category: 'taverna',
    description:
      'A beautifully unmarked basement taverna hidden beneath the Athinas Street market — there is no sign, just a staircase leading down. Run by the same family for decades, it serves only a handful of dishes each day: chickpeas, fish, beans, and rough house wine from the barrel. Athens at its most raw and authentic.',
    photos: [
      'https://images.unsplash.com/photo-1655916355039-c30f9b4c967c?w=800&q=80',
      'https://images.unsplash.com/photo-1505883973882-490ee8cd39da?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1655916355039-c30f9b4c967c?w=800&q=80',
    address: 'Sokratous 9 & Theatrou, Athens 105 52',
    coordinates: { lat: 37.9798, lng: 23.7257 },
    hours: 'Mon–Sat 9:00 AM – 6:00 PM, Sun closed',
    closedOn: 'Sunday',
    costEstimate: '$',
    costNote: '€8–12 per person',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'No menu — just point at what others are eating or ask what is cooking today.',
      'Look for the unmarked staircase going down near the corner of Sokratous and Theatrou.',
      'Cash only. Bring small bills — there is no card machine.',
    ],
    tags: ['hidden-gem', 'basement', 'no-menu'],
  },
  {
    id: 'eat-lukumades',
    tab: 'eat',
    name: 'Lukumades',
    city: 'Athens',
    category: 'bakery',
    description:
      'The go-to spot in Athens for loukoumades — crispy, golden Greek donuts drizzled with honey, cinnamon, and an array of modern toppings from Nutella to pistachio praline. The tiny shop in Agia Irini Square draws long lines, but they move fast. Ideal as a dessert stop or an indulgent mid-afternoon snack.',
    photos: [
      'https://images.unsplash.com/photo-1503152394-c571994fd383?w=800&q=80',
      'https://images.unsplash.com/photo-1655916355033-cb0bfd30f8df?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1503152394-c571994fd383?w=800&q=80',
    address: 'Aiolou 21, Monastiraki, Athens 105 51',
    coordinates: { lat: 37.9774, lng: 23.7271 },
    hours: 'Daily 10:00 AM – 12:00 AM',
    closedOn: undefined,
    costEstimate: '$',
    costNote: '€4–7 per serving',
    phone: '+30 210 321 2262',
    website: 'https://www.lukumades.com',
    bookingRequired: false,
    tips: [
      'Classic honey-cinnamon is the purist choice; Nutella-oreo is the crowd favorite.',
      'Best enjoyed immediately while still hot and crispy.',
      'Combine with a visit to Kostas Souvlaki nearby for a savory-then-sweet circuit.',
    ],
    tags: ['dessert', 'donuts', 'loukoumades'],
  },
  {
    id: 'eat-bairaktaris',
    tab: 'eat',
    name: 'Bairaktaris',
    city: 'Athens',
    category: 'traditional',
    description:
      'A Monastiraki Square institution since 1879, Bairaktaris is one of the oldest tavernas in Athens. The sprawling outdoor terrace buzzes day and night with locals and tourists tucking into generous portions of moussaka, souvlaki, and slow-roasted lamb. Old-school waiters in aprons deliver plates at speed to the sound of clinking glasses.',
    photos: [
      'https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?w=800&q=80',
      'https://images.unsplash.com/photo-1605707141131-aa742dcf4671?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?w=800&q=80',
    address: 'Monastiraki Square 2, Athens 105 55',
    coordinates: { lat: 37.9761, lng: 23.7256 },
    hours: 'Daily 7:00 AM – 2:00 AM',
    closedOn: undefined,
    costEstimate: '$',
    costNote: '€8–15 per person',
    phone: '+30 210 321 3036',
    website: null,
    bookingRequired: false,
    tips: [
      'The lamb on the spit roasting out front is the move — ask for a plate.',
      'Huge portions at very fair prices for such a central location.',
      'Great for a quick, hearty meal between sightseeing stops.',
    ],
    tags: ['monastiraki', 'historic', 'taverna'],
  },
  {
    id: 'eat-liondi-traditional-greek',
    tab: 'eat',
    name: 'Liondi Traditional Greek Restaurant',
    city: 'Athens',
    category: 'traditional',
    description:
      'A warm, family-run restaurant in the Plaka neighborhood serving lovingly prepared home-style Greek dishes. The menu features beautifully executed classics like gemista, pastitsio, and slow-braised beef stifado. The covered courtyard with climbing vines feels like eating at a village home in the heart of the city.',
    photos: [
      'https://images.unsplash.com/photo-1605707141131-aa742dcf4671?w=800&q=80',
      'https://images.unsplash.com/photo-1655916355045-0f94f47b398c?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1605707141131-aa742dcf4671?w=800&q=80',
    address: 'Sholeiou 5, Plaka, Athens 105 58',
    coordinates: { lat: 37.9745, lng: 23.7310 },
    hours: 'Daily 12:00 PM – 11:00 PM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€15–25 per person',
    phone: '+30 210 322 2392',
    website: null,
    bookingRequired: false,
    tips: [
      'The beef stifado and the stuffed vine leaves are exceptional.',
      'Ask the owner for daily specials — they cook what is fresh that morning.',
      'One of the more authentic options in touristy Plaka — worth seeking out.',
    ],
    tags: ['plaka', 'home-cooking', 'family-run'],
  },
  {
    id: 'eat-oineas',
    tab: 'eat',
    name: 'Oineas',
    city: 'Athens',
    category: 'mezedes',
    description:
      'A cozy mezedopoleio in the atmospheric Psyrri neighborhood serving creative Greek small plates. The menu bridges traditional and modern with dishes like fava with caramelized onions, smoked eggplant, and pork belly with plum sauce. Exposed stone walls, dim lighting, and a great house wine list make it a perfect dinner spot.',
    photos: [
      'https://images.unsplash.com/photo-1676831410404-ee79a62c8188?w=800&q=80',
      'https://images.unsplash.com/photo-1697455621664-d97023b8ee7d?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1676831410404-ee79a62c8188?w=800&q=80',
    address: 'Aischylou 9, Psyrri, Athens 105 54',
    coordinates: { lat: 37.9783, lng: 23.7244 },
    hours: 'Daily 1:00 PM – 12:00 AM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€18–28 per person',
    phone: '+30 210 321 5614',
    website: null,
    bookingRequired: true,
    tips: [
      'Order four or five small plates to share — the menu is built for grazing.',
      'The fava bean puree and the grilled octopus are must-orders.',
      'Reserve for dinner on weekends — this place fills up quickly.',
    ],
    tags: ['psyrri', 'small-plates', 'meze'],
  },
  {
    id: 'eat-ariston',
    tab: 'eat',
    name: 'Ariston',
    city: 'Athens',
    category: 'bakery',
    description:
      'A legendary Athenian bakery operating since 1910, famous across the city for its flaky savory pies. The spanakopita and tyropita are perfection — buttery, crispy phyllo with generous fillings. Locals queue at lunchtime for a quick, cheap, and deeply satisfying meal on the go. An essential Athens food experience.',
    photos: [
      'https://images.unsplash.com/photo-1655916355033-cb0bfd30f8df?w=800&q=80',
      'https://images.unsplash.com/photo-1655916355039-c30f9b4c967c?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1655916355033-cb0bfd30f8df?w=800&q=80',
    address: 'Voulis 10, Syntagma, Athens 105 62',
    coordinates: { lat: 37.9753, lng: 23.7339 },
    hours: 'Mon–Fri 7:30 AM – 5:00 PM, Sat 7:30 AM – 3:30 PM, Sun closed',
    closedOn: 'Sunday',
    costEstimate: '$',
    costNote: '€2–5 per pie',
    phone: '+30 210 322 7626',
    website: null,
    bookingRequired: false,
    tips: [
      'The kourou tyropita (cheese pie with sesame crust) is the signature — do not skip it.',
      'Arrive before noon for the best selection; popular items sell out.',
      'Perfect grab-and-go breakfast or lunch between Syntagma and Plaka.',
    ],
    tags: ['bakery', 'pies', 'budget', 'historic'],
  },
  {
    id: 'eat-to-kafeneio',
    tab: 'eat',
    name: 'To Kafeneio',
    city: 'Athens',
    category: 'taverna',
    description:
      'A charming old-world taverna tucked into the quiet upper reaches of Plaka, just below the Anafiotika neighborhood. The intimate terrace is draped in bougainvillea and overlooks a quiet pedestrian lane. The menu is short and traditional — grilled meats, stuffed peppers, fresh salads — prepared with care and served without pretense.',
    photos: [
      'https://images.unsplash.com/photo-1664111943859-fb9637c97723?w=800&q=80',
      'https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1664111943859-fb9637c97723?w=800&q=80',
    address: 'Epicharmou 1, Plaka, Athens 105 58',
    coordinates: { lat: 37.9731, lng: 23.7303 },
    hours: 'Daily 11:00 AM – 12:00 AM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€14–22 per person',
    phone: '+30 210 324 6916',
    website: null,
    bookingRequired: false,
    tips: [
      'Sit on the upper terrace for a quiet, vine-shaded escape from the crowds below.',
      'Try the gemista (stuffed tomatoes and peppers) — a comfort-food classic.',
      'A lovely spot for a long, relaxed lunch after visiting the Acropolis.',
    ],
    tags: ['plaka', 'terrace', 'quiet', 'traditional'],
  },

  // ========== NAFPLIO (9) ==========
  {
    id: 'eat-arapakos',
    tab: 'eat',
    name: 'Arapakos',
    city: 'Nafplio',
    category: 'seafood',
    description:
      'An upscale seafood restaurant tucked into the atmospheric alleys of Nafplio\'s old town. Arapakos sources fish daily from local fishermen and presents it with refined simplicity — grilled whole sea bream, octopus carpaccio, and delicate shrimp risotto. The candlelit stone courtyard makes it a perfect romantic dinner spot.',
    photos: [
      'https://images.unsplash.com/photo-1751060867787-3d28ea3d6e22?w=800&q=80',
      'https://images.unsplash.com/photo-1677336068327-e0e545dbf13a?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1751060867787-3d28ea3d6e22?w=800&q=80',
    address: 'Bouboulinas 81, Nafplio 211 00',
    coordinates: { lat: 37.5674, lng: 22.7981 },
    hours: 'Daily 12:00 PM – 11:30 PM',
    closedOn: undefined,
    costEstimate: '$$$',
    costNote: '€30–50 per person',
    phone: '+30 275 202 7675',
    website: null,
    bookingRequired: true,
    tips: [
      'Ask the waiter what fish came in today and order it grilled whole.',
      'Reserve a courtyard table for the most atmospheric experience.',
      'The octopus carpaccio starter is not to be missed.',
    ],
    tags: ['seafood', 'upscale', 'old-town'],
  },
  {
    id: 'eat-antica-gelateria-di-roma',
    tab: 'eat',
    name: 'Antica Gelateria di Roma',
    city: 'Nafplio',
    category: 'bakery',
    description:
      'A Nafplio institution and arguably the best gelato in all of Greece, run by an Italian family using traditional Roman recipes. The pistachio, stracciatella, and seasonal fruit flavors are extraordinary. Located on a charming pedestrian street, it is impossible to walk past without stopping.',
    photos: [
      'https://images.unsplash.com/photo-1602348143971-0c5c97d23367?w=800&q=80',
      'https://images.unsplash.com/photo-1602348709085-bc5720f99fd5?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1602348143971-0c5c97d23367?w=800&q=80',
    address: 'Farmakopoulou 3, Nafplio 211 00',
    coordinates: { lat: 37.5676, lng: 22.7957 },
    hours: 'Daily 9:00 AM – 12:00 AM (seasonal hours)',
    closedOn: undefined,
    costEstimate: '$',
    costNote: '€3–6 per serving',
    phone: '+30 275 202 3520',
    website: null,
    bookingRequired: false,
    tips: [
      'Pistachio and dark chocolate are the consensus top flavors.',
      'Visit twice — once for gelato, once for their excellent Italian-style pastries.',
      'Lines can be long on summer evenings; the wait is always worth it.',
    ],
    tags: ['gelato', 'dessert', 'italian'],
  },
  {
    id: 'eat-ta-fanaria',
    tab: 'eat',
    name: 'Ta Fanaria',
    city: 'Nafplio',
    category: 'taverna',
    description:
      'A cozy, family-run taverna hidden in the winding alleys of Nafplio\'s old town. The menu features home-style Greek cooking — moussaka, gemista, and tender lamb kleftiko cooked in parchment. Vine-covered walls, checkered tablecloths, and genuine warmth from the owners make this feel like eating at a Greek grandmother\'s home.',
    photos: [
      'https://images.unsplash.com/photo-1728454978463-31b0233e41c2?w=800&q=80',
      'https://images.unsplash.com/photo-1677336068327-e0e545dbf13a?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1728454978463-31b0233e41c2?w=800&q=80',
    address: 'Staikopoulou 13, Nafplio 211 00',
    coordinates: { lat: 37.5679, lng: 22.7963 },
    hours: 'Daily 12:00 PM – 11:00 PM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€12–22 per person',
    phone: '+30 275 202 7141',
    website: null,
    bookingRequired: false,
    tips: [
      'The lamb kleftiko wrapped in parchment is the signature — order it.',
      'Ask about daily specials, which are always cooked fresh that morning.',
      'Lovely for a quiet weekday lunch away from the waterfront crowds.',
    ],
    tags: ['home-cooking', 'taverna', 'old-town'],
  },
  {
    id: 'eat-savouras',
    tab: 'eat',
    name: 'Savouras',
    city: 'Nafplio',
    category: 'seafood',
    description:
      'A classic waterfront fish taverna where locals go for the freshest catch in Nafplio. The no-frills setup — paper tablecloths, simple wooden chairs, and a glass case full of today\'s fish — belies the quality of the cooking. Grilled whole fish, fried calamari, and garlicky shrimp saganaki are all superb.',
    photos: [
      'https://images.unsplash.com/photo-1751060867787-3d28ea3d6e22?w=800&q=80',
      'https://images.unsplash.com/photo-1759063293478-1d2a9348d696?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1759063293478-1d2a9348d696?w=800&q=80',
    address: 'Bouboulinas 79, Nafplio 211 00',
    coordinates: { lat: 37.5672, lng: 22.7984 },
    hours: 'Daily 12:00 PM – 11:00 PM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€18–30 per person',
    phone: '+30 275 202 7704',
    website: null,
    bookingRequired: false,
    tips: [
      'Pick your fish from the display case — price is by the kilo.',
      'The fried calamari is some of the best in the Peloponnese.',
      'Sit waterside for views of the Bourtzi fortress.',
    ],
    tags: ['seafood', 'waterfront', 'fish-taverna'],
  },
  {
    id: 'eat-noulis',
    tab: 'eat',
    name: 'Noulis',
    city: 'Nafplio',
    category: 'souvlaki',
    description:
      'The go-to casual grill in Nafplio for no-nonsense souvlaki, gyros, and grilled meats. Locals pack this no-frills spot for generous pork gyros wrapped in warm pita with hand-cut fries, tangy tzatziki, and fresh tomato. Cheap, fast, and extremely satisfying — the ideal fuel after climbing Palamidi fortress.',
    photos: [
      'https://images.unsplash.com/photo-1602348709085-bc5720f99fd5?w=800&q=80',
      'https://images.unsplash.com/photo-1588250977873-b15f82d8176f?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1602348709085-bc5720f99fd5?w=800&q=80',
    address: 'Moutzouridou 21, Nafplio 211 00',
    coordinates: { lat: 37.5688, lng: 22.7942 },
    hours: 'Daily 11:00 AM – 11:00 PM',
    closedOn: undefined,
    costEstimate: '$',
    costNote: '€5–9 per person',
    phone: '+30 275 202 5541',
    website: null,
    bookingRequired: false,
    tips: [
      'The pork gyros pita is the move — big, messy, and delicious.',
      'Perfect refueling stop after the 999-step climb up Palamidi.',
      'Takeaway works great for a bench lunch on the waterfront.',
    ],
    tags: ['souvlaki', 'gyros', 'budget'],
  },
  {
    id: 'eat-alaloum',
    tab: 'eat',
    name: 'Alaloum',
    city: 'Nafplio',
    category: 'mezedes',
    description:
      'A stylish modern Greek eatery in Nafplio\'s old town offering creative small plates that blend traditional flavors with contemporary presentation. Think beet carpaccio with xinomyzithra cheese, pork belly with fig reduction, and deconstructed baklava. The wine list focuses on excellent Peloponnesian and Nemea varietals.',
    photos: [
      'https://images.unsplash.com/photo-1677336068327-e0e545dbf13a?w=800&q=80',
      'https://images.unsplash.com/photo-1728454978463-31b0233e41c2?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1677336068327-e0e545dbf13a?w=800&q=80',
    address: 'Kapodistiriou 26, Nafplio 211 00',
    coordinates: { lat: 37.5669, lng: 22.7950 },
    hours: 'Wed–Mon 6:00 PM – 12:00 AM, Tue closed',
    closedOn: 'Tuesday',
    costEstimate: '$$',
    costNote: '€20–35 per person',
    phone: '+30 275 202 9012',
    website: null,
    bookingRequired: true,
    tips: [
      'Order several small plates to share — the menu is designed for grazing.',
      'Ask for a Nemea Agiorgitiko red wine to pair with the meat dishes.',
      'Closed Tuesdays — plan accordingly.',
    ],
    tags: ['modern-greek', 'small-plates', 'wine'],
  },
  {
    id: 'eat-to-ellinikon',
    tab: 'eat',
    name: 'To Ellinikon',
    city: 'Nafplio',
    category: 'traditional',
    description:
      'A beloved neighborhood taverna that locals fiercely guard as their own. The menu is pure Greek comfort — generous portions of pastitsio, beef kokkinisto, and perfectly grilled paidakia (lamb chops). The relaxed atmosphere and honest pricing keep regulars coming back week after week. No frills, just excellent home-style cooking.',
    photos: [
      'https://images.unsplash.com/photo-1588250977873-b15f82d8176f?w=800&q=80',
      'https://images.unsplash.com/photo-1759063293478-1d2a9348d696?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1588250977873-b15f82d8176f?w=800&q=80',
    address: 'Plapouta Square, Nafplio 211 00',
    coordinates: { lat: 37.5683, lng: 22.7939 },
    hours: 'Daily 12:00 PM – 11:00 PM',
    closedOn: undefined,
    costEstimate: '$',
    costNote: '€10–18 per person',
    phone: '+30 275 202 2449',
    website: null,
    bookingRequired: false,
    tips: [
      'The grilled lamb chops are thick, juicy, and perfectly charred.',
      'Sit in the square for a lovely al fresco meal on warm evenings.',
      'One of the best value meals in Nafplio — big portions, fair prices.',
    ],
    tags: ['home-cooking', 'budget', 'local-favorite'],
  },
  {
    id: 'eat-mezedopoleio-noulis',
    tab: 'eat',
    name: 'Mezedopoleio Noulis',
    city: 'Nafplio',
    category: 'mezedes',
    description:
      'Not to be confused with the souvlaki spot, this is a proper mezedopoleio specializing in shareable small plates and seafood meze. The fried gavros, grilled sardines, and taramosalata are all excellent. The covered patio on a quiet lane is a relaxing spot to while away an evening over raki and small bites.',
    photos: [
      'https://images.unsplash.com/photo-1759063293478-1d2a9348d696?w=800&q=80',
      'https://images.unsplash.com/photo-1751060867787-3d28ea3d6e22?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1759063293478-1d2a9348d696?w=800&q=80',
    address: 'Moutzouridou 22, Nafplio 211 00',
    coordinates: { lat: 37.5687, lng: 22.7944 },
    hours: 'Daily 12:00 PM – 11:30 PM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€15–25 per person',
    phone: '+30 275 202 5541',
    website: null,
    bookingRequired: false,
    tips: [
      'Order the fried gavros (anchovies) — impossibly crispy and addictive.',
      'Ask for a carafe of local raki to accompany your meze spread.',
      'Great option for a lighter meal of shared small plates.',
    ],
    tags: ['meze', 'seafood', 'small-plates'],
  },
  {
    id: 'eat-psaropoula',
    tab: 'eat',
    name: 'Psaropoula Fish Taverna',
    city: 'Nafplio',
    category: 'seafood',
    description:
      'A no-nonsense fish taverna on the waterfront promenade with tables practically touching the sea. The daily catch is displayed on ice and grilled to order — simple, fresh, and delicious. Fried calamari, grilled sardines, and whole sea bass come with lemon wedges and nothing more. Exactly what a Greek fish taverna should be.',
    photos: [
      'https://images.unsplash.com/photo-1602348143971-0c5c97d23367?w=800&q=80',
      'https://images.unsplash.com/photo-1728454978463-31b0233e41c2?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1602348143971-0c5c97d23367?w=800&q=80',
    address: 'Bouboulinas 99, Nafplio 211 00',
    coordinates: { lat: 37.5670, lng: 22.7990 },
    hours: 'Daily 12:00 PM – 11:00 PM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€18–30 per person',
    phone: '+30 275 202 7234',
    website: null,
    bookingRequired: false,
    tips: [
      'The grilled sardines are cheap, fresh, and absolutely perfect with lemon.',
      'Grab a waterfront table for views of Bourtzi fortress at sunset.',
      'Ask what was caught that morning — that is always the best order.',
    ],
    tags: ['fish-taverna', 'waterfront', 'fresh-catch'],
  },

  // ========== SANTORINI (9) ==========
  {
    id: 'eat-ammoudi-fish-tavern',
    tab: 'eat',
    name: 'Ammoudi Fish Tavern',
    city: 'Santorini',
    category: 'seafood',
    description:
      'Perched right on the tiny harbor of Amoudi Bay below Oia, this no-frills fish taverna serves the freshest catch steps from where the boats dock. The setting is impossibly picturesque — volcanic red cliffs, turquoise water, and tables practically touching the sea. Grilled octopus, sea bream, and lobster pasta are the highlights.',
    photos: [
      'https://images.unsplash.com/photo-1690324075771-f8b43b7b1bbc?w=800&q=80',
      'https://images.unsplash.com/photo-1580855453606-7a02774c686c?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1690324075771-f8b43b7b1bbc?w=800&q=80',
    address: 'Amoudi Bay, Oia, Santorini 847 02',
    coordinates: { lat: 36.4657, lng: 25.3733 },
    hours: 'Daily 11:00 AM – 10:00 PM (seasonal)',
    closedOn: undefined,
    costEstimate: '$$$',
    costNote: '€30–50 per person',
    phone: '+30 228 607 1614',
    website: null,
    bookingRequired: true,
    tips: [
      'Walk down the 300 steps from Oia or take a donkey — no cars allowed.',
      'Time your lunch so you can swim off the rocks at Amoudi before eating.',
      'The grilled octopus is a must-order — perfectly charred every time.',
    ],
    tags: ['oia', 'seafood', 'waterfront'],
  },
  {
    id: 'eat-metaxy-mas',
    tab: 'eat',
    name: 'Metaxy Mas',
    city: 'Santorini',
    category: 'traditional',
    description:
      'Hidden in the quiet village of Exo Gonia, away from the tourist crowds, Metaxy Mas serves exceptional traditional Cretan and Greek dishes in a charming village setting. The roasted lamb, fava with capers, and house-made sausage are standouts. Consistently rated as one of the best restaurants on Santorini by locals and visitors alike.',
    photos: [
      'https://images.unsplash.com/photo-1545006547-eee2b9beddff?w=800&q=80',
      'https://images.unsplash.com/photo-1544327404-f6aed3d39dbf?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1545006547-eee2b9beddff?w=800&q=80',
    address: 'Exo Gonia, Santorini 847 00',
    coordinates: { lat: 36.3975, lng: 25.4547 },
    hours: 'Daily 12:00 PM – 11:30 PM (April–October)',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€18–30 per person',
    phone: '+30 228 603 1323',
    website: 'https://www.metaxymas.gr',
    bookingRequired: true,
    tips: [
      'Reserve at least a day ahead in peak season — it books solid.',
      'You will need a car or ATV to reach Exo Gonia; it is worth the trip.',
      'Try the Cretan apaki (smoked pork) and the Santorinian fava.',
    ],
    tags: ['traditional', 'cretan', 'village'],
  },
  {
    id: 'eat-luckys-souvlaki',
    tab: 'eat',
    name: "Lucky's Souvlaki",
    city: 'Santorini',
    category: 'souvlaki',
    description:
      'The best quick-service gyros and souvlaki in Fira, and possibly all of Santorini. This tiny takeaway joint near the main square serves massive pork and chicken gyros stuffed with hand-cut fries and creamy tzatziki for just a few euros. The perfect cheap eat when you do not want to spend Santorini prices on every meal.',
    photos: [
      'https://images.unsplash.com/photo-1652179326115-943d168c4cb2?w=800&q=80',
      'https://images.unsplash.com/photo-1676730056228-7e38cbb88edc?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1652179326115-943d168c4cb2?w=800&q=80',
    address: 'Dekigala, Fira, Santorini 847 00',
    coordinates: { lat: 36.4167, lng: 25.4315 },
    hours: 'Daily 11:00 AM – 3:00 AM',
    closedOn: undefined,
    costEstimate: '$',
    costNote: '€4–7 per wrap',
    phone: '+30 228 602 2003',
    website: null,
    bookingRequired: false,
    tips: [
      'Open very late — perfect after a night out in Fira.',
      'The pork gyros is the locals\u2019 favorite; add extra tzatziki.',
      'Grab your wrap and walk to the caldera edge for a free million-dollar view.',
    ],
    tags: ['fira', 'gyros', 'budget', 'late-night'],
  },
  {
    id: 'eat-pelican-kipos',
    tab: 'eat',
    name: 'Pelican Kipos',
    city: 'Santorini',
    category: 'taverna',
    description:
      'A garden courtyard taverna tucked away in the beach resort village of Kamari, shaded by bougainvillea and citrus trees. The menu is hearty traditional Greek — moussaka, pastitsio, grilled lamb chops, and excellent Greek salads with Santorinian cherry tomatoes. A relaxing, family-friendly alternative to the pricier caldera restaurants.',
    photos: [
      'https://images.unsplash.com/photo-1544327404-f6aed3d39dbf?w=800&q=80',
      'https://images.unsplash.com/photo-1545006547-eee2b9beddff?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1544327404-f6aed3d39dbf?w=800&q=80',
    address: 'Kamari, Santorini 847 00',
    coordinates: { lat: 36.3787, lng: 25.4821 },
    hours: 'Daily 12:00 PM – 11:00 PM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€14–25 per person',
    phone: '+30 228 603 3710',
    website: null,
    bookingRequired: false,
    tips: [
      'Request a table under the bougainvillea canopy in the garden.',
      'Great option after a day at Kamari black sand beach.',
      'The Santorinian tomato fritters (tomatokeftedes) here are excellent.',
    ],
    tags: ['kamari', 'garden', 'family-friendly'],
  },
  {
    id: 'eat-to-psaraki',
    tab: 'eat',
    name: 'To Psaraki',
    city: 'Santorini',
    category: 'seafood',
    description:
      'A relaxed seafood taverna right on the dramatic Vlychada marina, surrounded by lunar-like white cliffs carved by wind and waves. The fish is landed daily at the adjacent port, and the menu keeps things simple: grilled whole fish, fried calamari, and seafood pasta. One of the most unique dining settings on the island.',
    photos: [
      'https://images.unsplash.com/photo-1654118890957-136cbada631e?w=800&q=80',
      'https://images.unsplash.com/photo-1690324075771-f8b43b7b1bbc?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1654118890957-136cbada631e?w=800&q=80',
    address: 'Vlychada Marina, Santorini 847 00',
    coordinates: { lat: 36.3478, lng: 25.4292 },
    hours: 'Daily 12:00 PM – 10:30 PM (seasonal)',
    closedOn: undefined,
    costEstimate: '$$$',
    costNote: '€25–45 per person',
    phone: '+30 228 608 2783',
    website: null,
    bookingRequired: true,
    tips: [
      'Combine with a visit to Vlychada Beach and the dramatic cliff formations.',
      'The lobster spaghetti is the splurge dish — big enough for two to share.',
      'Arrive for a late lunch to avoid the biggest crowds.',
    ],
    tags: ['seafood', 'vlychada', 'marina'],
  },
  {
    id: 'eat-aktaion',
    tab: 'eat',
    name: 'Aktaion',
    city: 'Santorini',
    category: 'taverna',
    description:
      'Perched right on the caldera cliff edge in Fira, Aktaion is a classic taverna with arguably the best sunset dining view in town at honest prices. The menu is traditional Greek with a focus on grilled meats and fresh salads. The panoramic terrace overlooks the volcanic caldera, Nea Kameni, and Thirassia island.',
    photos: [
      'https://images.unsplash.com/photo-1580855453606-7a02774c686c?w=800&q=80',
      'https://images.unsplash.com/photo-1724412575242-5d1a62458751?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1580855453606-7a02774c686c?w=800&q=80',
    address: 'Ypapantis, Fira, Santorini 847 00',
    coordinates: { lat: 36.4172, lng: 25.4280 },
    hours: 'Daily 10:00 AM – 12:00 AM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€20–35 per person',
    phone: '+30 228 602 2336',
    website: null,
    bookingRequired: true,
    tips: [
      'Reserve a front-row caldera table for sunset — call at least a day ahead.',
      'The prices are surprisingly reasonable for the view you get.',
      'Good spot for a long, lazy lunch with wine overlooking the caldera.',
    ],
    tags: ['fira', 'caldera', 'sunset', 'terrace'],
  },
  {
    id: 'eat-dimitris-ammoudi-taverna',
    tab: 'eat',
    name: 'Dimitris Ammoudi Taverna',
    city: 'Santorini',
    category: 'seafood',
    description:
      'The other legendary fish taverna at Amoudi Bay, right next door to its competitor and equally excellent. Dimitris has been serving grilled fish and octopus on the water\'s edge for decades. The sun-dried octopus hanging outside is the calling card. Simpler and slightly more rustic than its neighbor, with fierce local loyalty.',
    photos: [
      'https://images.unsplash.com/photo-1724412575242-5d1a62458751?w=800&q=80',
      'https://images.unsplash.com/photo-1654118890957-136cbada631e?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1724412575242-5d1a62458751?w=800&q=80',
    address: 'Amoudi Bay, Oia, Santorini 847 02',
    coordinates: { lat: 36.4655, lng: 25.3731 },
    hours: 'Daily 11:00 AM – 10:00 PM (seasonal)',
    closedOn: undefined,
    costEstimate: '$$$',
    costNote: '€30–50 per person',
    phone: '+30 228 607 1490',
    website: null,
    bookingRequired: true,
    tips: [
      'The sun-dried octopus grilled over charcoal is the signature dish.',
      'Come for a late lunch to beat the sunset dinner rush.',
      'Walk down the 300 steps from Oia — the bay itself is worth the descent.',
    ],
    tags: ['oia', 'seafood', 'waterfront', 'octopus'],
  },
  {
    id: 'eat-mama-thira',
    tab: 'eat',
    name: 'Mama Thira',
    city: 'Santorini',
    category: 'traditional',
    description:
      'A cozy family taverna in the heart of Fira serving generous portions of home-style Greek food. The warm interior is decorated with old Santorinian photographs and embroidery. Mama Thira excels at the classics — rich moussaka, creamy fava, tender stewed rabbit, and Santorinian tomatokeftedes. A comforting antidote to tourist-trap dining.',
    photos: [
      'https://images.unsplash.com/photo-1676730056228-7e38cbb88edc?w=800&q=80',
      'https://images.unsplash.com/photo-1652179326115-943d168c4cb2?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1676730056228-7e38cbb88edc?w=800&q=80',
    address: 'Erythrou Stavrou, Fira, Santorini 847 00',
    coordinates: { lat: 36.4163, lng: 25.4322 },
    hours: 'Daily 12:00 PM – 11:00 PM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€15–25 per person',
    phone: '+30 228 602 2189',
    website: null,
    bookingRequired: false,
    tips: [
      'The tomatokeftedes and fava are the essential Santorinian starters.',
      'Ask for the daily stew — it changes based on what is fresh.',
      'A reliable, honest meal at fair prices in the center of Fira.',
    ],
    tags: ['fira', 'home-cooking', 'family-run'],
  },
  {
    id: 'eat-the-good-heart',
    tab: 'eat',
    name: 'The Good Heart (Kali Kardia)',
    city: 'Santorini',
    category: 'taverna',
    description:
      'A true neighborhood taverna in the village of Akrotiri, far from the caldera crowds. Run by a warm local family, it serves robust portions of grilled meats, baked dishes, and classic mezedes at village prices. The vine-shaded terrace and unhurried pace make you feel like you have been invited to a family dinner.',
    photos: [
      'https://images.unsplash.com/photo-1545006547-eee2b9beddff?w=800&q=80',
      'https://images.unsplash.com/photo-1690324075771-f8b43b7b1bbc?w=800&q=80',
    ],
    heroPhoto:
      'https://images.unsplash.com/photo-1545006547-eee2b9beddff?w=800&q=80',
    address: 'Akrotiri, Santorini 847 00',
    coordinates: { lat: 36.3518, lng: 25.4032 },
    hours: 'Daily 12:00 PM – 11:00 PM',
    closedOn: undefined,
    costEstimate: '$',
    costNote: '€10–18 per person',
    phone: '+30 228 608 2027',
    website: null,
    bookingRequired: false,
    tips: [
      'Pair with a visit to the nearby Akrotiri archaeological site.',
      'The grilled pork chops and village sausage are outstanding.',
      'Some of the lowest prices on the island for genuinely delicious food.',
    ],
    tags: ['akrotiri', 'village', 'budget', 'family-run'],
  },
];

export default eat;
