const u = (id) => `https://images.unsplash.com/photo-${id}?w=800&q=80`;

const see = [
  // ─── ATHENS (12) ───────────────────────────────────────────────
  {
    id: 'see-acropolis-parthenon',
    tab: 'see',
    name: 'Acropolis & Parthenon',
    city: 'Athens',
    category: 'temple',
    description:
      'The crown jewel of Athens and Western civilization, the Acropolis rises 150 meters above the city topped by the iconic Parthenon, built in 447 BC to honor the goddess Athena. The sacred rock also holds the Erechtheion with its Caryatid porch and the Temple of Athena Nike.',
    photos: [
      u('1655916355045-0f94f47b398c'),
      u('1655916355039-c30f9b4c967c'),
      u('1505883973882-490ee8cd39da'),
    ],
    heroPhoto: u('1655916355045-0f94f47b398c'),
    address: 'Acropolis, Athens 105 58, Greece',
    coordinates: { lat: 37.9715, lng: 23.7257 },
    hours: 'Apr–Oct: 8:00 AM – 8:00 PM; Nov–Mar: 8:00 AM – 5:00 PM',
    costEstimate: '$$',
    costNote: '€20 adults, free on certain national holidays',
    duration: '2-3 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Arrive right at opening (8 AM) or after 5 PM to avoid the worst crowds and heat.',
      'Buy the €30 combo ticket that covers 7 archaeological sites and is valid for 5 days.',
      'Wear sturdy shoes — the marble paths are extremely slippery.',
    ],
    tags: ['must-see', 'ancient', 'UNESCO'],
  },
  {
    id: 'see-acropolis-museum',
    tab: 'see',
    name: 'Acropolis Museum',
    city: 'Athens',
    category: 'museum',
    description:
      'This stunning modern museum at the foot of the Acropolis houses an extraordinary collection of artifacts from the sacred rock, including original Caryatids, archaic statues, and the Parthenon Gallery with its panoramic views of the Acropolis itself.',
    photos: [
      u('1664111943859-fb9637c97723'),
      u('1603565816030-6b389eeb23cb'),
    ],
    heroPhoto: u('1664111943859-fb9637c97723'),
    address: '15 Dionysiou Areopagitou, Athens 117 42, Greece',
    coordinates: { lat: 37.9686, lng: 23.7288 },
    hours: 'Mon: 9 AM – 5 PM; Tue–Sun: 9 AM – 8 PM (extended Fri to 10 PM in summer)',
    costEstimate: '$$',
    costNote: '€15 adults, €10 reduced',
    duration: '2-3 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'The glass floor on the ground level reveals an ongoing archaeological dig beneath the building.',
      'Visit the top-floor Parthenon Gallery last — natural light and Acropolis views make it magical.',
      'The restaurant on the second floor has excellent food with Acropolis views at reasonable prices.',
    ],
    tags: ['museum', 'ancient', 'must-see'],
  },
  {
    id: 'see-ancient-agora',
    tab: 'see',
    name: 'Ancient Agora & Temple of Hephaestus',
    city: 'Athens',
    category: 'ruins',
    description:
      'The civic heart of ancient Athens where Socrates debated and democracy was born. The remarkably well-preserved Temple of Hephaestus (449 BC) is the best-surviving ancient Greek temple, and the reconstructed Stoa of Attalos now houses an excellent museum.',
    photos: [
      u('1605707141131-aa742dcf4671'),
      u('1503152394-c571994fd383'),
    ],
    heroPhoto: u('1605707141131-aa742dcf4671'),
    address: '24 Adrianou, Athens 105 55, Greece',
    coordinates: { lat: 37.9747, lng: 23.7222 },
    hours: 'Daily 8:00 AM – 8:00 PM (summer), 8:00 AM – 5:00 PM (winter)',
    costEstimate: '$',
    costNote: '€10 adults, or included in the €30 combo ticket',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Covered by the Acropolis combo ticket — buy it here if you have not already.',
      'The shady paths are a welcome retreat from the Athens heat — pack a picnic.',
      'The Stoa of Attalos museum is often overlooked but has fascinating everyday artifacts.',
    ],
    tags: ['ancient', 'ruins', 'history'],
  },
  {
    id: 'see-national-archaeological-museum',
    tab: 'see',
    name: 'National Archaeological Museum',
    city: 'Athens',
    category: 'museum',
    description:
      'Greece\'s largest and most important museum houses an unrivaled collection spanning 7,000 years, from Neolithic figurines to classical bronzes. Highlights include the golden Mask of Agamemnon, the Antikythera Mechanism, and the bronze Poseidon of Artemision.',
    photos: [
      u('1655916355033-cb0bfd30f8df'),
      u('1697455621664-d97023b8ee7d'),
    ],
    heroPhoto: u('1655916355033-cb0bfd30f8df'),
    address: '28is Oktovriou 44, Athens 106 82, Greece',
    coordinates: { lat: 37.9891, lng: 23.7322 },
    hours: 'Tue–Sun: 8:30 AM – 8:00 PM; Mon: 1:00 PM – 8:00 PM',
    costEstimate: '$$',
    costNote: '€12 adults, €6 reduced',
    duration: '2-4 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Allow at least 2 hours — this is one of the world\'s great museums and you could easily spend half a day.',
      'The Mycenaean gallery on the ground floor is the undisputed highlight.',
      'It is a 20-minute walk from Syntagma — take the metro to Omonia or Victoria station instead.',
    ],
    tags: ['museum', 'must-see', 'history'],
  },
  {
    id: 'see-plaka-neighborhood',
    tab: 'see',
    name: 'Plaka Neighborhood',
    city: 'Athens',
    category: 'neighborhood',
    description:
      'The oldest continuously inhabited neighborhood in Athens, Plaka\'s labyrinth of narrow pedestrian streets, neoclassical houses, and Byzantine churches nestles beneath the Acropolis. Its bougainvillea-draped alleyways are packed with tavernas, shops, and cafes.',
    photos: [
      u('1676831410404-ee79a62c8188'),
      u('1594048234320-f2caf3dac5c0'),
    ],
    heroPhoto: u('1676831410404-ee79a62c8188'),
    address: 'Plaka, Athens 105 56, Greece',
    coordinates: { lat: 37.9725, lng: 23.7300 },
    hours: 'Open 24 hours (shops/restaurants typically 10 AM – 11 PM)',
    costEstimate: 'Free',
    costNote: 'Free to walk; dining and shopping vary',
    duration: '2-3 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Wander into the sub-neighborhood of Anafiotika for a Cycladic island feel right in central Athens.',
      'Avoid the touristy restaurants on Adrianou Street — head one block deeper for better food and prices.',
      'Visit in the evening when the streets come alive and the Acropolis is beautifully lit above you.',
    ],
    tags: ['neighborhood', 'free', 'evening'],
  },
  {
    id: 'see-monastiraki-square',
    tab: 'see',
    name: 'Monastiraki Square & Flea Market',
    city: 'Athens',
    category: 'landmark',
    description:
      'This lively square is the gateway to Athens\' famous flea market, where streets fan out with antique shops, vintage finds, street food, and souvenirs. The square itself offers postcard-perfect views of the Acropolis framed by the ancient Hadrian\'s Library ruins.',
    photos: [
      u('1555993539-1732b0258235'),
      u('1669706341369-1e40498d2e40'),
    ],
    heroPhoto: u('1555993539-1732b0258235'),
    address: 'Monastiraki Square, Athens 105 55, Greece',
    coordinates: { lat: 37.9763, lng: 23.7259 },
    hours: 'Open 24 hours (market shops 10 AM – 8 PM; Sunday flea market from 8 AM)',
    costEstimate: 'Free',
    costNote: 'Free to explore; shopping varies',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Sunday morning is the best time for the flea market — arrive early for the best finds.',
      'Haggling is expected at the outdoor stalls but not inside established shops.',
      'Grab a souvlaki from Thanasis or Bairaktaris on the square — both are Athenian institutions.',
    ],
    tags: ['market', 'free', 'shopping'],
  },
  {
    id: 'see-temple-olympian-zeus',
    tab: 'see',
    name: 'Temple of Olympian Zeus',
    city: 'Athens',
    category: 'ruins',
    description:
      'Once the largest temple in Greece, this colossal ruin took nearly 700 years to complete. Fifteen of the original 104 Corinthian columns still stand at 17 meters tall, and nearby Hadrian\'s Arch marks the ancient boundary between old Athens and the Roman city.',
    photos: [
      u('1676831159775-604ec16e1c1f'),
      u('1666192179043-5aad64280d63'),
    ],
    heroPhoto: u('1676831159775-604ec16e1c1f'),
    address: 'Vasilissis Olgas, Athens 105 57, Greece',
    coordinates: { lat: 37.9693, lng: 23.7331 },
    hours: 'Daily 8:00 AM – 8:00 PM (summer), 8:00 AM – 5:00 PM (winter)',
    costEstimate: '$',
    costNote: '€8 adults, or included in the €30 combo ticket',
    duration: '30-60 minutes',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Best photographed in late afternoon light when the columns glow golden.',
      'Combine with Hadrian\'s Arch which is right at the entrance — it is free to see from outside.',
      'One of the 7 sites on the combo ticket, so use it if you have not already visited.',
    ],
    tags: ['ancient', 'ruins', 'photography'],
  },
  {
    id: 'see-syntagma-square-parliament',
    tab: 'see',
    name: 'Syntagma Square & Parliament',
    city: 'Athens',
    category: 'landmark',
    description:
      'Athens\' central square is home to the Greek Parliament (former Royal Palace) and the Tomb of the Unknown Soldier, where the iconic Evzone guards in traditional dress perform an elaborate changing of the guard ceremony every hour on the hour.',
    photos: [
      u('1594048234320-f2caf3dac5c0'),
      u('1503152394-c571994fd383'),
    ],
    heroPhoto: u('1594048234320-f2caf3dac5c0'),
    address: 'Plateia Syntagmatos, Athens 105 63, Greece',
    coordinates: { lat: 37.9755, lng: 23.7348 },
    hours: 'Square open 24 hours; changing of the guard every hour, grand ceremony Sunday 11 AM',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '30-60 minutes',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'The grand changing of the guard on Sunday at 11 AM features the full regiment in ceremonial dress — do not miss it.',
      'Stand close to the tomb for the best view of the Evzones\' choreographed movements.',
      'The National Garden behind Parliament is a cool, shady retreat from the city bustle.',
    ],
    tags: ['free', 'ceremony', 'landmark'],
  },
  {
    id: 'see-lycabettus-hill',
    tab: 'see',
    name: 'Lycabettus Hill',
    city: 'Athens',
    category: 'viewpoint',
    description:
      'At 277 meters, Lycabettus is the highest point in central Athens, offering a sweeping 360-degree panorama from the Acropolis to the Saronic Gulf. You can hike up through pine-scented paths, take the funicular, or drive to the whitewashed Chapel of St. George at the summit.',
    photos: [
      u('1697455621664-d97023b8ee7d'),
      u('1669706341369-1e40498d2e40'),
    ],
    heroPhoto: u('1697455621664-d97023b8ee7d'),
    address: 'Lycabettus Hill, Athens 114 71, Greece',
    coordinates: { lat: 37.9825, lng: 23.7449 },
    hours: 'Open 24 hours; funicular runs 9:00 AM – 2:30 AM',
    costEstimate: '$',
    costNote: 'Free to hike; funicular €10 round trip',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Come for sunset — the views of the Acropolis and city lights are extraordinary.',
      'The hike up takes about 30 minutes from Kolonaki; bring water in summer.',
      'The Chapel of St. George at the top is a beautiful whitewashed church with panoramic views.',
    ],
    tags: ['viewpoint', 'sunset', 'hiking'],
  },
  {
    id: 'see-delphi-day-trip',
    tab: 'see',
    name: 'Delphi (Day Trip)',
    city: 'Athens',
    category: 'ruins',
    description:
      'Once considered the center of the world by the ancient Greeks, Delphi is set dramatically on the slopes of Mount Parnassus. The sanctuary of Apollo, the ancient theatre, the stadium, and the superb archaeological museum make this one of Greece\'s most awe-inspiring sites.',
    photos: [
      u('1555993539-1732b0258235'),
      u('1605707141131-aa742dcf4671'),
      u('1664111943859-fb9637c97723'),
    ],
    heroPhoto: u('1555993539-1732b0258235'),
    address: 'Archaeological Site of Delphi, Delphi 330 54, Greece',
    coordinates: { lat: 38.4824, lng: 22.5010 },
    hours: 'Daily 8:00 AM – 8:00 PM (summer), 8:30 AM – 3:30 PM (winter)',
    costEstimate: '$$',
    costNote: '€12 site + museum combo ticket',
    duration: 'Full day (3 hours driving + 3-4 hours on site)',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Leave Athens by 7 AM to arrive before the tour buses — the 2.5-hour drive is scenic through Boeotia.',
      'Visit the museum first to understand what you will see at the site, especially the bronze Charioteer.',
      'Stop in the mountain village of Arachova on the way back for coffee and local honey.',
    ],
    tags: ['day-trip', 'UNESCO', 'ancient'],
  },
  {
    id: 'see-benaki-museum',
    tab: 'see',
    name: 'Benaki Museum',
    city: 'Athens',
    category: 'museum',
    description:
      'Housed in a stunning neoclassical mansion near the National Garden, the Benaki Museum traces Greek culture from prehistory to the 20th century across 36 beautifully curated rooms. The collection spans gold jewelry, Byzantine icons, traditional costumes, and El Greco paintings.',
    photos: [
      u('1676831410404-ee79a62c8188'),
      u('1655916355033-cb0bfd30f8df'),
    ],
    heroPhoto: u('1676831410404-ee79a62c8188'),
    address: '1 Koumbari Street, Athens 106 74, Greece',
    coordinates: { lat: 37.9762, lng: 23.7400 },
    hours: 'Wed & Fri: 10 AM – 6 PM; Thu & Sat: 10 AM – midnight; Sun: 10 AM – 4 PM; closed Mon & Tue',
    costEstimate: '$',
    costNote: '€12 adults, free on Thursdays',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Visit on Thursday when admission is free and the museum stays open late.',
      'The rooftop cafe has beautiful views over the National Garden and toward the Acropolis.',
      'Do not miss the recreation of 18th-century Macedonian mansion rooms on the upper floors.',
    ],
    tags: ['museum', 'culture', 'history'],
  },
  {
    id: 'see-panathenaic-stadium',
    tab: 'see',
    name: 'Panathenaic Stadium (Kallimarmaro)',
    city: 'Athens',
    category: 'landmark',
    description:
      'The only stadium in the world built entirely of marble, the Panathenaic Stadium was reconstructed in 1896 to host the first modern Olympic Games. Originally built in 330 BC for the ancient Panathenaic Games, it seats 50,000 spectators and remains the finish line for the Athens Classic Marathon.',
    photos: [
      u('1666192179043-5aad64280d63'),
      u('1676831159775-604ec16e1c1f'),
    ],
    heroPhoto: u('1666192179043-5aad64280d63'),
    address: 'Vassileos Konstantinou, Athens 116 35, Greece',
    coordinates: { lat: 37.9683, lng: 23.7412 },
    hours: 'Daily 8:00 AM – 7:00 PM (Mar–Oct), 8:00 AM – 5:00 PM (Nov–Feb)',
    costEstimate: '$',
    costNote: '€10 adults, includes audio guide',
    duration: '1 hour',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Stand on the podium for a photo — it is set up for visitors and the audio guide encourages it.',
      'The small museum in the tunnel beneath the stands has fascinating Olympic memorabilia.',
      'Visit in the late afternoon when the marble glows in the golden light and crowds thin out.',
    ],
    tags: ['landmark', 'Olympic', 'history'],
  },

  // ─── NAFPLIO / PELOPONNESE (13) ────────────────────────────────
  {
    id: 'see-nafplio-old-town',
    tab: 'see',
    name: 'Nafplio Old Town',
    city: 'Nafplio',
    category: 'neighborhood',
    description:
      'Greece\'s first capital is one of the most romantic towns in the country, with elegant Venetian mansions, Ottoman fountains, flower-filled balconies, and cobblestone streets winding beneath the mighty Palamidi Fortress. The waterfront promenade and Syntagma Square are the heart of town.',
    photos: [
      u('1751060867787-3d28ea3d6e22'),
      u('1677336068327-e0e545dbf13a'),
      u('1588250977873-b15f82d8176f'),
    ],
    heroPhoto: u('1751060867787-3d28ea3d6e22'),
    address: 'Old Town, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5673, lng: 22.8016 },
    hours: 'Open 24 hours',
    costEstimate: 'Free',
    costNote: 'Free to explore',
    duration: '2-3 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Stay at least two nights — Nafplio deserves more than a day trip from Athens.',
      'Try the local gelato shops along the waterfront; Antica Gelateria is superb.',
      'Walk the seaside promenade to Arvanitia Beach for beautiful views back toward Bourtzi.',
    ],
    tags: ['neighborhood', 'romantic', 'free'],
  },
  {
    id: 'see-palamidi-fortress',
    tab: 'see',
    name: 'Palamidi Fortress',
    city: 'Nafplio',
    category: 'historic',
    description:
      'This imposing Venetian fortress crowns the 216-meter hill above Nafplio, connected by a legendary staircase of 999 steps. Built in just three years (1711-1714), it features eight self-contained bastions and offers breathtaking views over the Argolic Gulf and the town below.',
    photos: [
      u('1759063293478-1d2a9348d696'),
      u('1602348143971-0c5c97d23367'),
    ],
    heroPhoto: u('1759063293478-1d2a9348d696'),
    address: 'Palamidi, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5621, lng: 22.8049 },
    hours: 'Daily 8:00 AM – 8:00 PM (summer), 8:30 AM – 3:30 PM (winter)',
    costEstimate: '$',
    costNote: '€8 adults',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Climb the 999 steps early in the morning to avoid the heat — bring plenty of water.',
      'You can also drive up from the east side if the stairs are too daunting.',
      'The views at sunset are spectacular but check closing times as they change seasonally.',
    ],
    tags: ['fortress', 'views', 'exercise'],
  },
  {
    id: 'see-bourtzi-castle',
    tab: 'see',
    name: 'Bourtzi Castle',
    city: 'Nafplio',
    category: 'historic',
    description:
      'This picturesque island fortress sits in the middle of Nafplio\'s harbor, built by the Venetians in 1473 to protect the town. The small castle on its rocky islet is one of Greece\'s most photographed sights, especially beautiful at sunset when the stone glows amber.',
    photos: [
      u('1602348709085-bc5720f99fd5'),
      u('1728454978463-31b0233e41c2'),
    ],
    heroPhoto: u('1602348709085-bc5720f99fd5'),
    address: 'Bourtzi, Nafplio Harbor, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5688, lng: 22.7972 },
    hours: 'Boat trips run 10:00 AM – 7:00 PM in summer; exterior visible 24 hours',
    costEstimate: '$',
    costNote: '€5 for the short boat ride from the port',
    duration: '30-60 minutes',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Small boats depart from the port regularly in summer — no reservation needed.',
      'The best photos of Bourtzi are from the waterfront promenade at sunset.',
      'The castle sometimes hosts concerts and events in summer — check local listings.',
    ],
    tags: ['castle', 'photography', 'harbor'],
  },
  {
    id: 'see-mycenae',
    tab: 'see',
    name: 'Mycenae (Lion Gate & Treasury of Atreus)',
    city: 'Nafplio',
    category: 'ruins',
    description:
      'The legendary kingdom of Agamemnon, Mycenae was the most powerful city in the ancient Greek world from 1600 to 1100 BC. Walk through the iconic Lion Gate, descend into the underground cistern, and visit the monumental beehive tomb known as the Treasury of Atreus.',
    photos: [
      u('1775649135113-51d710c37983'),
      u('1589528391483-dbdc76a9bd58'),
      u('1537649019808-a87dc561d0cc'),
    ],
    heroPhoto: u('1775649135113-51d710c37983'),
    address: 'Mycenae Archaeological Site, Mykines 212 00, Greece',
    coordinates: { lat: 37.7306, lng: 22.7563 },
    hours: 'Daily 8:00 AM – 8:00 PM (summer), 8:30 AM – 3:30 PM (winter)',
    costEstimate: '$$',
    costNote: '€12 adults (site + museum combo)',
    duration: '2-3 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Visit the Treasury of Atreus (Tomb of Agamemnon) first — it is just off the road before the main site entrance.',
      'Bring a flashlight or use your phone torch for the underground cistern — it is dark and slippery.',
      'Only 30 minutes from Nafplio, making it an easy half-day trip.',
    ],
    tags: ['ancient', 'UNESCO', 'must-see'],
  },
  {
    id: 'see-ancient-epidaurus',
    tab: 'see',
    name: 'Ancient Epidaurus',
    city: 'Nafplio',
    category: 'ruins',
    description:
      'Home to the best-preserved ancient theatre in Greece, Epidaurus seats 14,000 spectators and still has near-perfect acoustics — a coin dropped on stage can be heard in the last row. The larger sanctuary was dedicated to Asklepios, the god of medicine.',
    photos: [
      u('1592685294766-463e3340d43b'),
      u('1647990837483-4126e311d3f8'),
    ],
    heroPhoto: u('1592685294766-463e3340d43b'),
    address: 'Epidaurus Archaeological Site, Epidavros 210 52, Greece',
    coordinates: { lat: 37.5962, lng: 23.0792 },
    hours: 'Daily 8:00 AM – 8:00 PM (summer), 8:00 AM – 5:00 PM (winter)',
    costEstimate: '$$',
    costNote: '€14 adults (site + museum)',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Test the acoustics yourself — have someone stand on the orchestra circle while you sit in the top row.',
      'In summer (Jul–Aug) the Athens & Epidaurus Festival stages ancient Greek dramas here on Friday and Saturday nights.',
      'About 30 minutes from Nafplio; combine with a beach stop at the nearby coastal village of Old Epidavros.',
    ],
    tags: ['ancient', 'UNESCO', 'theatre'],
  },
  {
    id: 'see-ancient-olympia',
    tab: 'see',
    name: 'Ancient Olympia',
    city: 'Nafplio',
    category: 'ruins',
    description:
      'The birthplace of the Olympic Games, where athletes competed every four years from 776 BC to 393 AD. Wander through the ruins of the Temple of Zeus (which once held one of the Seven Wonders), the ancient stadium, and the superb archaeological museum.',
    photos: [
      u('1760324271160-92ac8f84b5f6'),
      u('1662241947856-00c0fbe79c9b'),
      u('1559576587-ddf2a82285d1'),
    ],
    heroPhoto: u('1760324271160-92ac8f84b5f6'),
    address: 'Archaeological Site of Olympia, Archaia Olympia 270 65, Greece',
    coordinates: { lat: 37.6388, lng: 21.6297 },
    hours: 'Daily 8:00 AM – 8:00 PM (summer), 8:30 AM – 3:30 PM (winter)',
    costEstimate: '$$',
    costNote: '€12 adults (site + museum combo)',
    duration: 'Full day from Nafplio (3 hours driving each way + 2-3 hours on site)',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Run a lap in the original Olympic stadium — the stone starting blocks are still in place.',
      'The museum houses the famous statue of Hermes by Praxiteles and the pediment sculptures from the Temple of Zeus.',
      'This is a long day trip from Nafplio; consider staying overnight in the pleasant town of Olympia.',
    ],
    tags: ['ancient', 'UNESCO', 'day-trip'],
  },
  {
    id: 'see-corinth-canal',
    tab: 'see',
    name: 'Corinth Canal',
    city: 'Nafplio',
    category: 'landmark',
    description:
      'This dramatic 6.4-kilometer canal slices through solid rock walls up to 63 meters high, connecting the Aegean and Ionian seas. First dreamed of by Periander in 602 BC and finally completed in 1893, the narrow passage is a jaw-dropping feat of engineering.',
    photos: [
      u('1677336068327-e0e545dbf13a'),
      u('1588250977873-b15f82d8176f'),
    ],
    heroPhoto: u('1677336068327-e0e545dbf13a'),
    address: 'Corinth Canal, Isthmia 201 00, Greece',
    coordinates: { lat: 37.9345, lng: 22.9844 },
    hours: 'Viewable 24 hours from the pedestrian bridge',
    costEstimate: 'Free',
    costNote: 'Free to view; bungee jumping available for ~€80',
    duration: '30 minutes',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Stop at the pedestrian bridge on the old national road for the most dramatic straight-down views.',
      'If you are driving from Athens to Nafplio, this is a perfect 5-minute stop right along the way.',
      'Zulu Bungy operates bungee jumps from the bridge for thrill-seekers.',
    ],
    tags: ['landmark', 'free', 'engineering'],
  },
  {
    id: 'see-nemea-archaeological-site',
    tab: 'see',
    name: 'Nemea Archaeological Site',
    city: 'Nafplio',
    category: 'ruins',
    description:
      'Ancient Nemea was the site of the biennial Nemean Games and the mythical slaying of the Nemean Lion by Hercules. The three standing columns of the Temple of Zeus are striking, and the ancient stadium features a remarkable vaulted tunnel entrance where athletes once walked to compete.',
    photos: [
      u('1537649019808-a87dc561d0cc'),
      u('1559576587-ddf2a82285d1'),
    ],
    heroPhoto: u('1537649019808-a87dc561d0cc'),
    address: 'Ancient Nemea, Nemea 205 00, Greece',
    coordinates: { lat: 37.8076, lng: 22.7104 },
    hours: 'Daily 8:30 AM – 3:30 PM',
    costEstimate: '$',
    costNote: '€8 adults (site + museum)',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'The ancient stadium is a 5-minute walk from the main site — do not miss the athletes\' entrance tunnel.',
      'Much less crowded than Olympia or Epidaurus, making for a more peaceful visit.',
      'About 40 minutes from Nafplio, easily combined with a visit to Mycenae.',
    ],
    tags: ['ancient', 'ruins', 'off-beaten-path'],
  },
  {
    id: 'see-monemvasia',
    tab: 'see',
    name: 'Monemvasia',
    city: 'Nafplio',
    category: 'historic',
    description:
      'A medieval fortress town built on a massive rock island connected to the mainland by a single causeway, Monemvasia is one of Greece\'s most dramatic destinations. The car-free lower town has Byzantine churches, stone mansions, and winding alleys, while the upper citadel ruins offer sweeping sea views.',
    photos: [
      u('1589528391483-dbdc76a9bd58'),
      u('1592685294766-463e3340d43b'),
      u('1647990837483-4126e311d3f8'),
    ],
    heroPhoto: u('1589528391483-dbdc76a9bd58'),
    address: 'Monemvasia 230 70, Laconia, Greece',
    coordinates: { lat: 36.6876, lng: 23.0571 },
    hours: 'Open 24 hours (fortress town is car-free)',
    costEstimate: 'Free',
    costNote: 'Free to explore; dining varies',
    duration: 'Half day to full day',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'The drive from Nafplio takes about 2.5 hours through beautiful scenery — worth an overnight stay.',
      'Climb to the upper citadel for the church of Agia Sophia perched on the cliff edge.',
      'The lower town has charming cafes and shops tucked into medieval stone buildings.',
    ],
    tags: ['medieval', 'romantic', 'photography'],
  },
  {
    id: 'see-tiryns',
    tab: 'see',
    name: 'Tiryns',
    city: 'Nafplio',
    category: 'ruins',
    description:
      'This UNESCO-listed Mycenaean citadel just outside Nafplio features some of the most impressive Cyclopean walls in Greece, with stone blocks weighing up to 14 tons. Homer described Tiryns as "mighty walled," and the massive fortifications, galleries, and palace foundations remain awe-inspiring after 3,300 years.',
    photos: [
      u('1728454978463-31b0233e41c2'),
      u('1762241947856-00c0fbe79c9b'),
    ],
    heroPhoto: u('1728454978463-31b0233e41c2'),
    address: 'Tiryns Archaeological Site, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5997, lng: 22.7997 },
    hours: 'Daily 8:00 AM – 8:00 PM (summer), 8:30 AM – 3:30 PM (winter)',
    costEstimate: '$',
    costNote: '€6 adults',
    duration: '1 hour',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Only 4 kilometers from Nafplio, making it an easy quick visit on the way to or from Mycenae.',
      'Walk through the corbelled galleries inside the walls — they are remarkably intact.',
      'Very few tourists visit here compared to Mycenae, so you may have the site nearly to yourself.',
    ],
    tags: ['ancient', 'UNESCO', 'ruins'],
  },
  {
    id: 'see-tolo-beach',
    tab: 'see',
    name: 'Tolo Beach',
    city: 'Nafplio',
    category: 'beach',
    description:
      'A long crescent of golden sand and shallow turquoise water just 11 kilometers from Nafplio, Tolo is the most popular beach in the Argolic Gulf. The gentle slope makes it ideal for families, and the waterfront is lined with tavernas serving fresh seafood with views of the tiny islands offshore.',
    photos: [
      u('1602348143971-0c5c97d23367'),
      u('1759063293478-1d2a9348d696'),
    ],
    heroPhoto: u('1602348143971-0c5c97d23367'),
    address: 'Tolo Beach, Tolo 210 56, Greece',
    coordinates: { lat: 37.5213, lng: 22.8719 },
    hours: 'Open 24 hours; sunbed rentals typically 9 AM – 7 PM',
    costEstimate: '$',
    costNote: 'Free access; sunbed and umbrella rental €8-10',
    duration: '2-4 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Arrive early in summer to claim a good spot — the beach fills up by midday.',
      'The eastern end of the beach is less crowded and has clearer water.',
      'Take a water taxi to the small island of Romvi for snorkeling and a more secluded swim.',
    ],
    tags: ['beach', 'swimming', 'family'],
  },
  {
    id: 'see-arvanitia-promenade',
    tab: 'see',
    name: 'Arvanitia Promenade',
    city: 'Nafplio',
    category: 'nature',
    description:
      'This scenic coastal walkway carved into the cliffs below Akronafplia fortress connects the old town to Arvanitia Beach. The path hugs the rocky shoreline with crystal-clear water on one side and pine-covered cliffs on the other, offering stunning views of the Argolic Gulf and Bourtzi Castle.',
    photos: [
      u('1751060867787-3d28ea3d6e22'),
      u('1602348709085-bc5720f99fd5'),
    ],
    heroPhoto: u('1751060867787-3d28ea3d6e22'),
    address: 'Arvanitia Promenade, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5633, lng: 22.7994 },
    hours: 'Open 24 hours',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '1 hour',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Walk the promenade at sunset for spectacular light on the water and fortress walls.',
      'The path ends at Arvanitia Beach, a small pebbly cove perfect for a refreshing swim.',
      'Start from the end of the old town near the Nafplio Palace hotel for the easiest access.',
    ],
    tags: ['nature', 'free', 'walking'],
  },
  {
    id: 'see-karathona-beach',
    tab: 'see',
    name: 'Karathona Beach',
    city: 'Nafplio',
    category: 'beach',
    description:
      'A beautiful long sandy beach set in a sheltered bay just southeast of Nafplio, Karathona is backed by olive groves and pine trees with the dramatic silhouette of Palamidi Fortress rising above. The calm, shallow waters and natural shade make it a favorite for both locals and visitors.',
    photos: [
      u('1775649135113-51d710c37983'),
      u('1677336068327-e0e545dbf13a'),
    ],
    heroPhoto: u('1775649135113-51d710c37983'),
    address: 'Karathona Beach, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5535, lng: 22.8103 },
    hours: 'Open 24 hours',
    costEstimate: 'Free',
    costNote: 'Free access; some sections have sunbed rental for €8',
    duration: '2-4 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Walk or cycle from Nafplio old town along the scenic coastal road — it takes about 20 minutes on foot.',
      'The southern end of the beach is quieter and has natural shade from the trees.',
      'There is a small seasonal cantina for snacks and cold drinks, but bring your own supplies to be safe.',
    ],
    tags: ['beach', 'nature', 'family'],
  },

  // ─── CRETE (10) ─────────────────────────────────────────────────
  {
    id: 'see-knossos-palace',
    tab: 'see',
    name: 'Knossos Palace',
    city: 'Crete',
    category: 'ruins',
    description:
      'The legendary Minoan palace of Knossos was the ceremonial and political center of Europe\'s oldest civilization, dating back to 1900 BC. Associated with the myth of the Labyrinth and the Minotaur, the partially reconstructed ruins reveal grand throne rooms, vivid frescoes, and a complex of over 1,300 rooms.',
    photos: [
      u('1570303345338-e1f0eddf4946'),
      u('1555939594-58d7cb561ad1'),
    ],
    heroPhoto: u('1570303345338-e1f0eddf4946'),
    address: 'Knossos Palace, Heraklion 714 09, Crete, Greece',
    coordinates: { lat: 35.2979, lng: 25.1633 },
    hours: 'Apr–Oct: 8:00 AM – 8:00 PM; Nov–Mar: 8:00 AM – 5:00 PM',
    costEstimate: '$$',
    costNote: '€15 adults, €8 reduced; combo with Archaeological Museum €20',
    duration: '2-3 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Arrive right at opening to avoid the tour bus crowds that descend by 10 AM.',
      'Buy the combo ticket with the Heraklion Archaeological Museum — the original frescoes are displayed there.',
      'Hire a guide on-site to bring the ruins to life; the layout is confusing without context.',
    ],
    tags: ['ancient', 'must-see', 'Minoan'],
  },
  {
    id: 'see-heraklion-archaeological-museum',
    tab: 'see',
    name: 'Heraklion Archaeological Museum',
    city: 'Crete',
    category: 'museum',
    description:
      'Home to the world\'s finest and most complete collection of Minoan art and artifacts, this museum traces 5,500 years of Cretan history. Highlights include the Phaistos Disc, the Snake Goddess figurines, the Bull-Leaper fresco, and dazzling gold jewelry from palatial tombs.',
    photos: [
      u('1555939594-58d7cb561ad1'),
      u('1504512485720-7d83a16ee930'),
    ],
    heroPhoto: u('1555939594-58d7cb561ad1'),
    address: '2 Xanthoudidou Street, Heraklion 712 02, Crete, Greece',
    coordinates: { lat: 35.3397, lng: 25.1374 },
    hours: 'Apr–Oct: 8:00 AM – 8:00 PM; Nov–Mar: 9:00 AM – 4:00 PM; Mon opens at 11:00 AM',
    costEstimate: '$$',
    costNote: '€12 adults, €6 reduced; combo with Knossos €20',
    duration: '2-3 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Visit after Knossos to see the original frescoes and artifacts in their proper context.',
      'The Minoan frescoes gallery on the upper floor is the undisputed highlight — save time for it.',
      'The museum is fully air-conditioned, making it a welcome midday retreat from the summer heat.',
    ],
    tags: ['museum', 'must-see', 'Minoan'],
  },
  {
    id: 'see-koules-venetian-fortress',
    tab: 'see',
    name: 'Koules Venetian Fortress',
    city: 'Crete',
    category: 'historic',
    description:
      'Guarding the entrance to Heraklion\'s old harbor since the 16th century, the imposing Koules fortress (also known as Rocca a Mare) is one of the best-preserved Venetian fortifications in the Mediterranean. Its thick walls, vaulted chambers, and rooftop terrace offer panoramic views of the harbor and sea.',
    photos: [
      u('1504512485720-7d83a16ee930'),
      u('1601581875309-fafbf2d3ed3a'),
    ],
    heroPhoto: u('1504512485720-7d83a16ee930'),
    address: 'Koules Fortress, Old Venetian Harbor, Heraklion 712 02, Crete, Greece',
    coordinates: { lat: 35.3451, lng: 25.1357 },
    hours: 'Wed–Mon: 8:30 AM – 3:30 PM; closed Tuesdays',
    costEstimate: '$',
    costNote: '€4 adults',
    duration: '30-60 minutes',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Walk along the harbor breakwater to reach the fortress — the stroll itself is lovely.',
      'The rooftop offers the best views of Heraklion\'s old harbor and the open sea.',
      'Visit in the late afternoon when the stone glows golden and the interior rooms are cool.',
    ],
    tags: ['fortress', 'Venetian', 'harbor'],
  },
  {
    id: 'see-lions-square',
    tab: 'see',
    name: 'Lions Square (Plateia Venizelou)',
    city: 'Crete',
    category: 'landmark',
    description:
      'The vibrant heart of Heraklion, Lions Square takes its name from the elegant 17th-century Morosini Fountain adorned with four carved lions. Surrounded by cafes, restaurants, and Venetian-era buildings, the square is the perfect starting point for exploring the old city.',
    photos: [
      u('1601581875309-fafbf2d3ed3a'),
      u('1598889272668-64e8b2d04a1b'),
    ],
    heroPhoto: u('1601581875309-fafbf2d3ed3a'),
    address: 'Plateia Venizelou, Heraklion 712 02, Crete, Greece',
    coordinates: { lat: 35.3390, lng: 25.1339 },
    hours: 'Open 24 hours',
    costEstimate: 'Free',
    costNote: 'Free to visit; cafes and dining vary',
    duration: '30-60 minutes',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Grab a bougatsa (Cretan custard pastry) from a nearby bakery and enjoy it by the fountain.',
      'The square is a natural meeting point — use it as your base for exploring the old town on foot.',
      'In the evening the cafes fill up with locals, making it a great spot for people-watching.',
    ],
    tags: ['landmark', 'free', 'Venetian'],
  },
  {
    id: 'see-historical-museum-of-crete',
    tab: 'see',
    name: 'Historical Museum of Crete',
    city: 'Crete',
    category: 'museum',
    description:
      'Spanning the period from early Christian times to the modern era, this museum chronicles Cretan history through Byzantine icons, Venetian manuscripts, Ottoman artifacts, and World War II resistance memorabilia. Its crown jewel is the only El Greco painting remaining on Crete, "View of Mt. Sinai and the Monastery of St. Catherine."',
    photos: [
      u('1598889272668-64e8b2d04a1b'),
      u('1587130906985-0e1e97d1c6e5'),
    ],
    heroPhoto: u('1598889272668-64e8b2d04a1b'),
    address: '27 Lysimachou Kalokerinou, Heraklion 712 02, Crete, Greece',
    coordinates: { lat: 35.3430, lng: 25.1300 },
    hours: 'Mon–Sat: 9:00 AM – 5:00 PM; Sun: closed',
    costEstimate: '$',
    costNote: '€5 adults, €3 reduced',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Do not miss the El Greco painting on the ground floor — it is the only one of his works still on the island where he was born.',
      'The World War II room documenting the Battle of Crete and resistance is deeply moving.',
      'A quieter alternative to the Archaeological Museum, best visited on a hot afternoon.',
    ],
    tags: ['museum', 'history', 'culture'],
  },
  {
    id: 'see-church-of-agios-titos',
    tab: 'see',
    name: 'Church of Agios Titos',
    city: 'Crete',
    category: 'historic',
    description:
      'Dedicated to Crete\'s patron saint, this historic church near Lions Square has served as a Byzantine basilica, a Venetian cathedral, and an Ottoman mosque before returning to Orthodox worship. It houses the revered skull relic of Saint Titus, the first bishop of Crete and disciple of the Apostle Paul.',
    photos: [
      u('1587130906985-0e1e97d1c6e5'),
      u('1572803655444-0c52dba3e1de'),
    ],
    heroPhoto: u('1587130906985-0e1e97d1c6e5'),
    address: '25is Avgoustou Street, Heraklion 712 02, Crete, Greece',
    coordinates: { lat: 35.3399, lng: 25.1345 },
    hours: 'Daily 8:00 AM – 6:00 PM',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '20-30 minutes',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Step inside to see the ornate interior and the gold reliquary containing the skull of Saint Titus.',
      'The church is beautifully lit at night — worth a visit during an evening stroll through the old town.',
      'Located on the pedestrian street connecting Lions Square to the harbor, easy to combine with other sights.',
    ],
    tags: ['church', 'free', 'Byzantine'],
  },
  {
    id: 'see-heraklion-old-town-walls',
    tab: 'see',
    name: 'Heraklion Old Town Walls',
    city: 'Crete',
    category: 'historic',
    description:
      'Among the finest Venetian fortifications in the Mediterranean, Heraklion\'s massive walls stretch nearly 4 kilometers around the old city. Built between the 15th and 17th centuries, the walls feature seven imposing bastions, monumental gates, and walkable sections offering sweeping views over the rooftops.',
    photos: [
      u('1572803655444-0c52dba3e1de'),
      u('1580502304784-8985b7eb7260'),
    ],
    heroPhoto: u('1572803655444-0c52dba3e1de'),
    address: 'Venetian Walls, Heraklion 712 01, Crete, Greece',
    coordinates: { lat: 35.3375, lng: 25.1287 },
    hours: 'Open 24 hours (some bastions may have limited access)',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Walk along the top of the walls near the Martinengo Bastion where the writer Nikos Kazantzakis is buried.',
      'The Bethlehem Bastion has been restored and hosts cultural events in summer.',
      'Best explored in the early morning or late afternoon when the ramparts are not baking in the sun.',
    ],
    tags: ['Venetian', 'free', 'walking'],
  },
  {
    id: 'see-loggia-of-heraklion',
    tab: 'see',
    name: 'Loggia of Heraklion',
    city: 'Crete',
    category: 'landmark',
    description:
      'This elegant two-story Venetian building on 25th of August Street was the social and political hub of Venetian Heraklion, where nobles gathered to discuss affairs of state. Carefully reconstructed after wartime damage, it now serves as Heraklion\'s city hall and stands as one of the finest examples of Venetian architecture on Crete.',
    photos: [
      u('1580502304784-8985b7eb7260'),
      u('1597223557791-6e4e3a94c7ea'),
    ],
    heroPhoto: u('1580502304784-8985b7eb7260'),
    address: '25is Avgoustou Street, Heraklion 712 02, Crete, Greece',
    coordinates: { lat: 35.3401, lng: 25.1351 },
    hours: 'Exterior viewable 24 hours; interior not open to public',
    costEstimate: 'Free',
    costNote: 'Free (exterior only)',
    duration: '15-20 minutes',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'The building is best appreciated from the small square in front, where you can admire the arched facade.',
      'Combine with a walk down 25th of August Street, the most elegant Venetian-era avenue in Heraklion.',
      'Look for the carved Venetian coat of arms and elegant double-arched windows on the upper floor.',
    ],
    tags: ['landmark', 'Venetian', 'architecture'],
  },
  {
    id: 'see-cretaquarium',
    tab: 'see',
    name: 'CretAquarium (Thalassocosmos)',
    city: 'Crete',
    category: 'attraction',
    description:
      'One of the largest and most modern aquariums in the Mediterranean, CretAquarium showcases over 2,500 marine organisms across 60 tanks, representing the biodiversity of the Mediterranean and tropical seas. Highlights include sharks, jellyfish displays, loggerhead sea turtles, and a massive open-ocean tank.',
    photos: [
      u('1597223557791-6e4e3a94c7ea'),
      u('1564594985645-4427056e22e2'),
    ],
    heroPhoto: u('1597223557791-6e4e3a94c7ea'),
    address: 'Gournes, Heraklion 710 03, Crete, Greece',
    coordinates: { lat: 35.3317, lng: 25.2808 },
    hours: 'May–Sep: 9:30 AM – 9:00 PM; Oct–Apr: 9:30 AM – 5:00 PM',
    costEstimate: '$$',
    costNote: '€12 adults, €8 children',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Located about 15 kilometers east of Heraklion — easy to reach by car or public bus.',
      'A great rainy-day or midday-heat activity, especially for families with children.',
      'The jellyfish tanks and the open-ocean shark tank are the most impressive exhibits.',
    ],
    tags: ['family', 'aquarium', 'indoor'],
  },
  {
    id: 'see-amnissos-beach',
    tab: 'see',
    name: 'Amnissos Beach',
    city: 'Crete',
    category: 'beach',
    description:
      'The closest quality beach to Heraklion, Amnissos stretches along a wide sandy shore with clear turquoise waters backed by tamarisk trees. This was once the harbor of ancient Knossos, and the site of the Minoan "Villa of the Lilies" whose frescoes are now in the Heraklion Archaeological Museum.',
    photos: [
      u('1564594985645-4427056e22e2'),
      u('1570303345338-e1f0eddf4946'),
    ],
    heroPhoto: u('1564594985645-4427056e22e2'),
    address: 'Amnissos Beach, Heraklion 715 00, Crete, Greece',
    coordinates: { lat: 35.3350, lng: 25.2050 },
    hours: 'Open 24 hours; sunbed rentals typically 9 AM – 7 PM',
    costEstimate: '$',
    costNote: 'Free access; sunbed and umbrella rental €7-10',
    duration: '2-4 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Only 7 kilometers from Heraklion, reachable by city bus in about 15 minutes.',
      'The western end near the tamarisk trees has natural shade and is less crowded.',
      'Strong north winds can make the sea rough here — check conditions before going, especially in August.',
    ],
    tags: ['beach', 'swimming', 'Minoan'],
  },

  // ─── SANTORINI (10) ─────────────────────────────────────────────
  {
    id: 'see-oia-village',
    tab: 'see',
    name: 'Oia Village',
    city: 'Santorini',
    category: 'viewpoint',
    description:
      'Perched on the northern tip of Santorini\'s caldera, Oia is world-famous for its blue-domed churches, white-washed cave houses, and what is often called the most beautiful sunset on Earth. The narrow marble lanes are lined with art galleries, boutiques, and restaurants clinging to the cliff.',
    photos: [
      u('1690324075771-f8b43b7b1bbc'),
      u('1580855453606-7a02774c686c'),
      u('1545006547-eee2b9beddff'),
    ],
    heroPhoto: u('1690324075771-f8b43b7b1bbc'),
    address: 'Oia 847 02, Santorini, Greece',
    coordinates: { lat: 36.4618, lng: 25.3753 },
    hours: 'Open 24 hours',
    costEstimate: 'Free',
    costNote: 'Free to explore',
    duration: '2-3 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'For the famous sunset, claim a spot at the castle ruins at least 1 hour before — it gets extremely crowded.',
      'Visit early morning (before 9 AM) for photos without crowds, especially at the blue dome churches.',
      'The walk from Fira to Oia along the caldera edge takes about 3 hours and is one of Santorini\'s best experiences.',
    ],
    tags: ['sunset', 'must-see', 'photography'],
  },
  {
    id: 'see-fira-town',
    tab: 'see',
    name: 'Fira Town',
    city: 'Santorini',
    category: 'neighborhood',
    description:
      'Santorini\'s vibrant capital clings to the edge of the caldera cliff, offering dramatic views of the volcanic crater, the sea, and neighboring islands. Its winding streets are filled with shops, restaurants, and the excellent Museum of Prehistoric Thera housing Akrotiri finds.',
    photos: [
      u('1544327404-f6aed3d39dbf'),
      u('1724412575242-5d1a62458751'),
    ],
    heroPhoto: u('1544327404-f6aed3d39dbf'),
    address: 'Fira 847 00, Santorini, Greece',
    coordinates: { lat: 36.4165, lng: 25.4316 },
    hours: 'Open 24 hours',
    costEstimate: 'Free',
    costNote: 'Free to explore; dining and shopping vary',
    duration: '2-3 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Walk down the 587 zig-zag steps to the old port for a different perspective — or ride a donkey back up.',
      'The Museum of Prehistoric Thera on the main road is small but superb, with stunning Minoan frescoes.',
      'Fira has more affordable restaurants than Oia — explore the back streets away from the caldera edge.',
    ],
    tags: ['neighborhood', 'caldera', 'shopping'],
  },
  {
    id: 'see-akrotiri-archaeological-site',
    tab: 'see',
    name: 'Akrotiri Archaeological Site',
    city: 'Santorini',
    category: 'ruins',
    description:
      'Often called the "Minoan Pompeii," Akrotiri is a remarkably preserved Bronze Age settlement buried by a volcanic eruption around 1627 BC. The covered excavation reveals multi-story buildings, frescoes, drainage systems, and pottery, showcasing a sophisticated civilization frozen in time.',
    photos: [
      u('1654118890957-136cbada631e'),
      u('1652179326115-943d168c4cb2'),
    ],
    heroPhoto: u('1654118890957-136cbada631e'),
    address: 'Akrotiri 847 00, Santorini, Greece',
    coordinates: { lat: 36.3517, lng: 25.4036 },
    hours: 'Wed–Mon: 8:00 AM – 8:00 PM (summer), 8:30 AM – 3:30 PM (winter); closed Tuesdays',
    costEstimate: '$$',
    costNote: '€12 adults',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'The site is covered by a modern roof, making it one of the few Santorini attractions comfortable in midday heat.',
      'Pair this with a visit to Red Beach, which is just a 5-minute walk from the entrance.',
      'The original frescoes are in the National Archaeological Museum in Athens and the Museum of Prehistoric Thera in Fira.',
    ],
    tags: ['ancient', 'ruins', 'must-see'],
  },
  {
    id: 'see-red-beach',
    tab: 'see',
    name: 'Red Beach',
    city: 'Santorini',
    category: 'beach',
    description:
      'One of Santorini\'s most dramatic natural wonders, Red Beach features towering volcanic cliffs of deep crimson and black that plunge into turquoise waters. The contrast of colors against the bright Aegean sky creates an otherworldly landscape.',
    photos: [
      u('1676730056228-7e38cbb88edc'),
      u('1625936716555-5577fb317a24'),
    ],
    heroPhoto: u('1676730056228-7e38cbb88edc'),
    address: 'Red Beach, Akrotiri 847 00, Santorini, Greece',
    coordinates: { lat: 36.3476, lng: 25.3965 },
    hours: 'Open 24 hours (best visited in daylight)',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'The cliff path to the beach can be unstable — check local conditions and wear proper shoes.',
      'Alternatively, take a water taxi from Akrotiri port to avoid the cliff walk.',
      'Arrive before 10 AM to get a good spot; bring an umbrella as there is no natural shade.',
    ],
    tags: ['beach', 'nature', 'photography'],
  },
  {
    id: 'see-amoudi-bay',
    tab: 'see',
    name: 'Amoudi Bay',
    city: 'Santorini',
    category: 'nature',
    description:
      'Tucked 300 steps below Oia\'s castle, this tiny fishing harbor with its handful of seafood tavernas and rust-red cliffs is a hidden gem. Locals and brave visitors jump from the rocks into the crystal-clear water, and the sunlight reflecting off the caldera walls is mesmerizing.',
    photos: [
      u('1654118891010-3c067d8c25cc'),
      u('1651045691067-d02eaaf96205'),
    ],
    heroPhoto: u('1654118891010-3c067d8c25cc'),
    address: 'Amoudi Bay, Oia 847 02, Santorini, Greece',
    coordinates: { lat: 36.4652, lng: 25.3697 },
    hours: 'Open 24 hours; restaurants typically 12 PM – 11 PM',
    costEstimate: 'Free',
    costNote: 'Free to visit; seafood dinner $$-$$$',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Come for a late lunch of fresh grilled octopus or sea urchin at one of the waterfront tavernas.',
      'The 300 steps down from Oia are easy but the climb back up after lunch is a workout.',
      'Swim out to the small island across the bay and jump off the rocks on the far side.',
    ],
    tags: ['harbor', 'seafood', 'swimming'],
  },
  {
    id: 'see-skaros-rock',
    tab: 'see',
    name: 'Skaros Rock',
    city: 'Santorini',
    category: 'ruins',
    description:
      'This dramatic rocky headland jutting out from the caldera between Fira and Imerovigli holds the ruins of a medieval Venetian castle that was once Santorini\'s capital. The short hike to the tip offers some of the island\'s most spectacular and uncrowded caldera views.',
    photos: [
      u('1652179467601-e313edb8473f'),
      u('1663051861448-44f15fa8f74d'),
    ],
    heroPhoto: u('1652179467601-e313edb8473f'),
    address: 'Skaros Rock, Imerovigli 847 00, Santorini, Greece',
    coordinates: { lat: 36.4351, lng: 25.4232 },
    hours: 'Open 24 hours',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'The trail down to the rock starts from Imerovigli and takes about 20 minutes — it is steep but manageable.',
      'Visit at sunset for incredible views without the Oia crowds.',
      'Wear sturdy shoes as the path is rocky and can be slippery.',
    ],
    tags: ['ruins', 'hiking', 'viewpoint'],
  },
  {
    id: 'see-ancient-thera',
    tab: 'see',
    name: 'Ancient Thera',
    city: 'Santorini',
    category: 'ruins',
    description:
      'Perched on the steep Mesa Vouno ridge between Kamari and Perissa beaches, Ancient Thera features ruins spanning from the 9th century BC to the Byzantine era, including temples, an agora, a theatre, and Roman baths. The hilltop location offers panoramic views of both coasts.',
    photos: [
      u('1654118890950-e4b0785175e5'),
      u('1565741478311-b3e79a17bfe3'),
    ],
    heroPhoto: u('1654118890950-e4b0785175e5'),
    address: 'Ancient Thera, Mesa Vouno, Santorini 847 00, Greece',
    coordinates: { lat: 36.3677, lng: 25.4701 },
    hours: 'Tue–Sun: 8:30 AM – 3:30 PM; closed Mondays',
    costEstimate: '$',
    costNote: '€6 adults',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'The winding road up is narrow — a scooter or ATV handles it better than a large car.',
      'Bring water and sun protection; there is no shade or facilities at the site.',
      'Combine with a day at Kamari or Perissa beach below.',
    ],
    tags: ['ancient', 'ruins', 'views'],
  },
  {
    id: 'see-pyrgos-village',
    tab: 'see',
    name: 'Pyrgos Village',
    city: 'Santorini',
    category: 'historic',
    description:
      'The highest village on Santorini, Pyrgos is a beautifully preserved medieval settlement crowned by the ruins of a Venetian kasteli. Far less touristy than Oia or Fira, its blue-and-white alleys, Byzantine churches, and panoramic terraces offer an authentic Santorini experience.',
    photos: [
      u('1690324075771-f8b43b7b1bbc'),
      u('1580855453606-7a02774c686c'),
    ],
    heroPhoto: u('1580855453606-7a02774c686c'),
    address: 'Pyrgos Kallistis 847 00, Santorini, Greece',
    coordinates: { lat: 36.3853, lng: 25.4452 },
    hours: 'Open 24 hours',
    costEstimate: 'Free',
    costNote: 'Free to explore',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Climb to the kasteli ruins at the top for 360-degree views of the entire island.',
      'Visit the Church of the Assumption (Theotokaki) with its beautiful blue dome.',
      'The village has several excellent traditional tavernas with far better prices than Oia.',
    ],
    tags: ['village', 'medieval', 'quiet'],
  },
  {
    id: 'see-santorini-lighthouse',
    tab: 'see',
    name: 'Santorini Lighthouse',
    city: 'Santorini',
    category: 'viewpoint',
    description:
      'Built in 1892 at the southern tip of Santorini near Akrotiri, the Faros lighthouse is one of the island\'s best-kept sunset secrets. The low stone building sits on a barren headland with unobstructed 270-degree views over the caldera, the sea, and the volcanic islands.',
    photos: [
      u('1625936716555-5577fb317a24'),
      u('1654118890957-136cbada631e'),
    ],
    heroPhoto: u('1625936716555-5577fb317a24'),
    address: 'Akrotiri Lighthouse, Akrotiri 847 00, Santorini, Greece',
    coordinates: { lat: 36.3476, lng: 25.3460 },
    hours: 'Open 24 hours (exterior only)',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '30-60 minutes',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'This is a local favorite for sunset — far less crowded than Oia with equally stunning views.',
      'Drive or ATV here; the road is paved but narrow. Arrive 45 minutes before sunset for parking.',
      'Combine with a visit to Akrotiri archaeological site and Red Beach, all within 10 minutes\' drive.',
    ],
    tags: ['sunset', 'viewpoint', 'free'],
  },
  {
    id: 'see-perissa-black-beach',
    tab: 'see',
    name: 'Perissa Black Beach',
    city: 'Santorini',
    category: 'beach',
    description:
      'Santorini\'s longest beach stretches for seven kilometers of dramatic black volcanic sand beneath the towering Mesa Vouno headland. The dark sand, deep blue water, and organized beach clubs with loungers and umbrellas make Perissa one of the most popular and striking beaches in the Cyclades.',
    photos: [
      u('1652179326115-943d168c4cb2'),
      u('1654118890950-e4b0785175e5'),
    ],
    heroPhoto: u('1652179326115-943d168c4cb2'),
    address: 'Perissa Beach, Perissa 847 03, Santorini, Greece',
    coordinates: { lat: 36.3553, lng: 25.4737 },
    hours: 'Open 24 hours; beach clubs typically 9 AM – 8 PM',
    costEstimate: '$',
    costNote: 'Free access; sunbed and umbrella rental €8-12',
    duration: '2-4 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'The black sand gets extremely hot in summer — wear water shoes or sandals to the waterline.',
      'The water drops off quickly, making it better for swimming than the shallower Kamari beach nearby.',
      'Buses run frequently from Fira, or rent an ATV for more flexibility exploring the south coast.',
    ],
    tags: ['beach', 'swimming', 'volcanic'],
  },
];

export default see;
