const shop = [
  // ============ ATHENS (8) ============
  {
    id: 'shop-greek-olive-oil',
    tab: 'shop',
    name: 'Greek Olive Oil',
    city: 'Athens',
    category: 'food & drink',
    description: 'Greece produces some of the world\'s finest extra virgin olive oil, particularly from Kalamata and Crete. Look for single-estate, cold-pressed varieties with PDO certification for the highest quality.',
    photos: [
      'https://images.unsplash.com/photo-1594048234320-f2caf3dac5c0?w=800&q=80',
      'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1594048234320-f2caf3dac5c0?w=800&q=80',
    address: 'Evripidou Street, Athens 105 53, Greece',
    coordinates: { lat: 37.9784, lng: 23.7253 },
    hours: '9:00 AM – 8:00 PM',
    closedOn: 'Sunday',
    costEstimate: '$$',
    costNote: '€8–€35 per bottle',
    bookingRequired: false,
    whereToBuy: ['Pantopoleion tis Mesogeiou (Athens Central Market area)', 'Ergon House Deli', 'Athens Airport duty-free'],
    tips: [
      'Look for "extra virgin" and a harvest date on the label — freshness matters more than brand.',
      'Kalamata and Sitia (Crete) PDO oils are consistently top-rated.',
      'Pack bottles in checked luggage wrapped in clothing to avoid breakage.',
    ],
    tags: ['food', 'gourmet', 'athens', 'gift'],
  },
  {
    id: 'shop-greek-honey-preserves',
    tab: 'shop',
    name: 'Greek Honey & Preserves',
    city: 'Athens',
    category: 'food & drink',
    description: 'Greek honey is renowned worldwide, especially thyme honey from the islands and pine honey from the mainland. Paired with fruit preserves like sour cherry and quince, these make exceptional gourmet gifts.',
    photos: [
      'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
      'https://images.unsplash.com/photo-1594048234320-f2caf3dac5c0?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
    address: 'Athinas Street 42, Athens 105 51, Greece',
    coordinates: { lat: 37.9790, lng: 23.7260 },
    hours: '8:00 AM – 7:00 PM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€6–€25 per jar',
    bookingRequired: false,
    whereToBuy: ['Athens Central Market (Varvakios Agora)', 'To Pantopoleion', 'Fine Food shop on Adrianou Street'],
    tips: [
      'Thyme honey from Ikaria or Kythira is the most prized variety — look for "thymari" on the label.',
      'Pine honey (peuko meli) has a unique savory-sweet flavor worth trying.',
      'Pair with Greek yogurt for the quintessential Greek breakfast.',
    ],
    tags: ['food', 'gourmet', 'athens', 'gift'],
  },
  {
    id: 'shop-monastiraki-flea-market',
    tab: 'shop',
    name: 'Monastiraki Flea Market Finds',
    city: 'Athens',
    category: 'market',
    description: 'The Monastiraki Flea Market is Athens\' legendary open-air bazaar, stretching around Avyssinia Square. On Sundays it explodes into a sprawling treasure hunt of antiques, vintage records, old coins, and curiosities.',
    photos: [
      'https://images.unsplash.com/photo-1669706341369-1e40498d2e40?w=800&q=80',
      'https://images.unsplash.com/photo-1676831159775-604ec16e1c1f?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1669706341369-1e40498d2e40?w=800&q=80',
    address: 'Ifestou Street, Monastiraki, Athens 105 55, Greece',
    coordinates: { lat: 37.9762, lng: 23.7245 },
    hours: '8:00 AM – 7:00 PM (Sunday market starts early)',
    closedOn: undefined,
    costEstimate: '$',
    costNote: '€2–€50+ depending on item',
    bookingRequired: false,
    whereToBuy: ['Avyssinia Square', 'Ifestou Street shops', 'Adrianou Street stalls'],
    tips: [
      'Sunday mornings are the best time for the full flea market experience — arrive by 9 AM.',
      'Bargaining is expected at outdoor stalls but not in the permanent shops.',
      'Look for vintage Greek movie posters, old maps, and Byzantine-style icons.',
    ],
    tags: ['vintage', 'antiques', 'athens', 'market', 'sunday'],
  },
  {
    id: 'shop-melissinos-leather-sandals',
    tab: 'shop',
    name: 'Handmade Leather Sandals (Melissinos)',
    city: 'Athens',
    category: 'artisan',
    description: 'The Melissinos Art — The Poet Sandal Maker is a legendary Athens sandal shop run by three generations of the Melissinos family. Their handmade leather sandals have graced the feet of celebrities from John Lennon to Sarah Jessica Parker.',
    photos: [
      'https://images.unsplash.com/photo-1676831159775-604ec16e1c1f?w=800&q=80',
      'https://images.unsplash.com/photo-1666192179043-5aad64280d63?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1676831159775-604ec16e1c1f?w=800&q=80',
    address: 'Agias Theklas 2, Athens 105 54, Greece',
    coordinates: { lat: 37.9770, lng: 23.7230 },
    hours: '10:00 AM – 7:00 PM',
    closedOn: 'Sunday',
    costEstimate: '$$',
    costNote: '€30–€75 per pair',
    bookingRequired: false,
    whereToBuy: ['Melissinos Art — The Poet Sandal Maker (Agias Theklas 2)'],
    tips: [
      'Go early or late in the day to avoid long waits — it\'s very popular with tourists.',
      'Sandals are made to order and can be adjusted to your foot on the spot.',
      'Check out the photos on the walls of famous customers spanning decades.',
    ],
    tags: ['artisan', 'leather', 'athens', 'handmade', 'iconic'],
  },
  {
    id: 'shop-komboloi-worry-beads',
    tab: 'shop',
    name: 'Komboloi (Worry Beads)',
    city: 'Athens',
    category: 'souvenir',
    description: 'Komboloi are traditional Greek worry beads, flipped and clicked as a meditative pastime. They come in amber, coral, semiprecious stones, and even olive wood — a quintessentially Greek gift.',
    photos: [
      'https://images.unsplash.com/photo-1666192179043-5aad64280d63?w=800&q=80',
      'https://images.unsplash.com/photo-1594048234320-f2caf3dac5c0?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1666192179043-5aad64280d63?w=800&q=80',
    address: 'Adrianou Street, Plaka, Athens 105 56, Greece',
    coordinates: { lat: 37.9740, lng: 23.7280 },
    hours: '10:00 AM – 9:00 PM',
    closedOn: undefined,
    costEstimate: '$',
    costNote: '€5–€80+ (amber sets are priciest)',
    bookingRequired: false,
    whereToBuy: ['Shops along Adrianou Street in Plaka', 'Komboloi Museum Shop (Nafplio)', 'Monastiraki gift shops'],
    tips: [
      'Natural amber komboloi are the most prized — hold them up to light to check authenticity.',
      'Learn the basic flipping technique from the shopkeeper; it\'s half the fun.',
      'Olive wood komboloi make affordable, lightweight souvenirs.',
    ],
    tags: ['souvenir', 'traditional', 'athens', 'gift'],
  },
  {
    id: 'shop-greek-ceramics-pottery',
    tab: 'shop',
    name: 'Greek Ceramics & Pottery',
    city: 'Athens',
    category: 'artisan',
    description: 'Greek pottery carries a tradition stretching back thousands of years. Today\'s artisans produce everything from museum-replica red-figure vases to colorful modern tableware inspired by island life.',
    photos: [
      'https://images.unsplash.com/photo-1594048234320-f2caf3dac5c0?w=800&q=80',
      'https://images.unsplash.com/photo-1669706341369-1e40498d2e40?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1594048234320-f2caf3dac5c0?w=800&q=80',
    address: 'Kidathineon Street 36, Plaka, Athens 105 58, Greece',
    coordinates: { lat: 37.9730, lng: 23.7295 },
    hours: '10:00 AM – 8:00 PM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€10–€120',
    bookingRequired: false,
    whereToBuy: ['Plaka district shops along Kidathineon Street', 'Benaki Museum gift shop', 'Monastiraki antique shops'],
    tips: [
      'Museum-replica vases from the Benaki or Acropolis Museum shops guarantee quality and authenticity.',
      'Handmade pieces will have slight imperfections — that\'s a sign of authenticity, not a flaw.',
      'Ask the shop to bubble-wrap pottery for safe transport in your luggage.',
    ],
    tags: ['artisan', 'handmade', 'athens', 'traditional', 'gift'],
  },
  {
    id: 'shop-mastiha-products',
    tab: 'shop',
    name: 'Mastiha Products',
    city: 'Athens',
    category: 'food & drink',
    description: 'Mastiha is a unique resin harvested only on the island of Chios, used in sweets, skincare, and cooking. The Mastiha Shop in Athens is the official outlet for authentic Chios mastiha products.',
    photos: [
      'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
      'https://images.unsplash.com/photo-1676831159775-604ec16e1c1f?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
    address: 'Panepistimiou 6, Athens 105 64, Greece',
    coordinates: { lat: 37.9792, lng: 23.7337 },
    hours: '9:00 AM – 9:00 PM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€5–€30 per item',
    bookingRequired: false,
    whereToBuy: ['Mastihashop (Panepistimiou 6, Athens)', 'Mastihashop (Athens Airport)', 'Korres stores'],
    tips: [
      'Mastiha-flavored Turkish delight (loukoumi) is a crowd-pleasing souvenir.',
      'Mastiha skincare products are excellent and unique to Greece.',
      'Try the mastiha candy drops — they have a refreshing pine-like flavor.',
    ],
    tags: ['food', 'gourmet', 'athens', 'unique', 'gift'],
  },
  {
    id: 'shop-greek-spices-herbs-bahar',
    tab: 'shop',
    name: 'Greek Spices & Herbs (Bahar)',
    city: 'Athens',
    category: 'food & drink',
    description: 'Bahar Spice Shop on Evripidou Street is an Athenian institution, its shelves bursting with aromatic Greek herbs, saffron, mountain tea, and exotic spices from across the Eastern Mediterranean.',
    photos: [
      'https://images.unsplash.com/photo-1669706341369-1e40498d2e40?w=800&q=80',
      'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1669706341369-1e40498d2e40?w=800&q=80',
    address: 'Evripidou 31, Athens 105 54, Greece',
    coordinates: { lat: 37.9787, lng: 23.7247 },
    hours: '8:00 AM – 6:00 PM',
    closedOn: 'Sunday',
    costEstimate: '$',
    costNote: '€2–€15 per packet',
    bookingRequired: false,
    whereToBuy: ['Bahar Spices (Evripidou 31)', 'Evripidou Street spice shops', 'Athens Central Market'],
    tips: [
      'Evripidou Street is Athens\' aromatic spice row — walk the whole block to compare shops.',
      'Kozani saffron (krokos) is among the best in the world and far cheaper here than abroad.',
      'Greek mountain tea and wild oregano are lightweight, shelf-stable gifts everyone loves.',
    ],
    tags: ['food', 'herbs', 'athens', 'gift', 'lightweight'],
  },

  // ============ NAFPLIO (6) ============
  {
    id: 'shop-nafplio-handmade-jewelry',
    tab: 'shop',
    name: 'Nafplio Handmade Jewelry',
    city: 'Nafplio',
    category: 'jewelry',
    description: 'Nafplio\'s old town is dotted with artisan jewelry studios where silversmiths and goldsmiths craft unique pieces inspired by Byzantine, ancient Greek, and modern Aegean designs.',
    photos: [
      'https://images.unsplash.com/photo-1677336068327-e0e545dbf13a?w=800&q=80',
      'https://images.unsplash.com/photo-1588250977873-b15f82d8176f?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1677336068327-e0e545dbf13a?w=800&q=80',
    address: 'Konstantinou Street 5, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5677, lng: 22.7975 },
    hours: '10:00 AM – 9:00 PM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€15–€200+',
    bookingRequired: false,
    whereToBuy: ['Artisan shops on Konstantinou Street', 'Staikopoulou Street boutiques', 'Syntagma Square galleries'],
    tips: [
      'Many jewelers will customize pieces on request — don\'t be shy about asking.',
      'Silver pieces offer great value compared to the same quality in Santorini or Mykonos.',
      'Look for designs incorporating ancient Greek coins or Byzantine motifs.',
    ],
    tags: ['jewelry', 'handmade', 'nafplio', 'artisan'],
  },
  {
    id: 'shop-komboloi-museum-shop',
    tab: 'shop',
    name: 'Komboloi Museum Shop',
    city: 'Nafplio',
    category: 'souvenir',
    description: 'The Komboloi Museum in Nafplio is the world\'s only museum dedicated to worry beads. Its shop carries an extraordinary collection of handcrafted komboloi in amber, semiprecious stones, horn, and more.',
    photos: [
      'https://images.unsplash.com/photo-1588250977873-b15f82d8176f?w=800&q=80',
      'https://images.unsplash.com/photo-1759063293478-1d2a9348d696?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1588250977873-b15f82d8176f?w=800&q=80',
    address: 'Staikopoulou 25, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5675, lng: 22.7970 },
    hours: '9:30 AM – 8:30 PM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€5–€150 (museum entry €3)',
    bookingRequired: false,
    whereToBuy: ['Komboloi Museum (Staikopoulou 25, Nafplio)'],
    tips: [
      'Visit the small museum upstairs first to appreciate the history before shopping.',
      'The owner Aris Evangelinos is passionate and will explain the craft if you ask.',
      'Amber and coral sets are the most traditional and valuable.',
    ],
    tags: ['souvenir', 'museum', 'nafplio', 'traditional', 'unique'],
  },
  {
    id: 'shop-greek-herbs-mountain-tea',
    tab: 'shop',
    name: 'Greek Herbs & Mountain Tea',
    city: 'Nafplio',
    category: 'food & drink',
    description: 'The hills of the Peloponnese yield wild oregano, mountain tea (tsai tou vounou), saffron from Kozani, and dried thyme — all far more potent than supermarket equivalents. They\'re lightweight and make perfect gifts.',
    photos: [
      'https://images.unsplash.com/photo-1759063293478-1d2a9348d696?w=800&q=80',
      'https://images.unsplash.com/photo-1602348143971-0c5c97d23367?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1759063293478-1d2a9348d696?w=800&q=80',
    address: 'Vasileos Konstantinou 18, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5685, lng: 22.7993 },
    hours: '9:00 AM – 7:00 PM',
    closedOn: 'Sunday',
    costEstimate: '$',
    costNote: '€3–€12 per packet',
    bookingRequired: false,
    whereToBuy: ['Nafplio Old Town grocery shops', 'Weekly farmers market (Wednesday & Saturday)', 'Herb shops on Staikopoulou Street'],
    tips: [
      'Greek mountain tea (sideritis) is a must-buy — it\'s caffeine-free and prized for health benefits.',
      'Wild oregano from the Peloponnese is leagues better than anything at home.',
      'Kozani saffron (krokos) is among the best in the world and much cheaper here than abroad.',
    ],
    tags: ['food', 'herbs', 'nafplio', 'gift', 'lightweight'],
  },
  {
    id: 'shop-handmade-soap-natural-cosmetics',
    tab: 'shop',
    name: 'Handmade Soap & Natural Cosmetics',
    city: 'Nafplio',
    category: 'artisan',
    description: 'Small workshops in Nafplio produce olive oil soaps, beeswax balms, and botanical skincare using Peloponnese ingredients. These artisan cosmetics are free from harsh chemicals and beautifully packaged for gifting.',
    photos: [
      'https://images.unsplash.com/photo-1751060867787-3d28ea3d6e22?w=800&q=80',
      'https://images.unsplash.com/photo-1602348709085-bc5720f99fd5?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1751060867787-3d28ea3d6e22?w=800&q=80',
    address: 'Staikopoulou 14, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5672, lng: 22.7978 },
    hours: '10:00 AM – 8:00 PM',
    closedOn: undefined,
    costEstimate: '$',
    costNote: '€4–€18 per item',
    bookingRequired: false,
    whereToBuy: ['Artisan soap shops on Staikopoulou Street', 'Korres corner shop', 'Apivita outlet (Nafplio)'],
    tips: [
      'Olive oil soap is gentle on sensitive skin and lasts longer than commercial soap.',
      'Look for soaps scented with local lavender, rose, or mastiha.',
      'These are lightweight and TSA-friendly — ideal carry-on souvenirs.',
    ],
    tags: ['artisan', 'cosmetics', 'nafplio', 'gift', 'natural'],
  },
  {
    id: 'shop-peloponnese-olive-oil-olives',
    tab: 'shop',
    name: 'Peloponnese Olive Oil & Olives',
    city: 'Nafplio',
    category: 'food & drink',
    description: 'The Peloponnese is home to the prized Koroneiki olive, producing rich, peppery extra virgin oil and plump Kalamata table olives. Local shops in Nafplio sell estate-bottled oils you won\'t find outside Greece.',
    photos: [
      'https://images.unsplash.com/photo-1602348143971-0c5c97d23367?w=800&q=80',
      'https://images.unsplash.com/photo-1677336068327-e0e545dbf13a?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1602348143971-0c5c97d23367?w=800&q=80',
    address: 'Syngrou Avenue 21, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5690, lng: 22.8005 },
    hours: '9:00 AM – 8:00 PM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€8–€30 per bottle',
    bookingRequired: false,
    whereToBuy: ['Local delis on Syngrou Avenue', 'Nafplio farmers market', 'Olive oil shops near Syntagma Square'],
    tips: [
      'Ask for a tasting before buying — most shops are happy to let you sample several oils.',
      'Kalamata olives vacuum-packed in brine travel well in checked luggage.',
      'Look for early-harvest (agoureleo) oil for the most intense, peppery flavor.',
    ],
    tags: ['food', 'gourmet', 'nafplio', 'gift'],
  },
  {
    id: 'shop-traditional-greek-sweets',
    tab: 'shop',
    name: 'Traditional Greek Sweets (Spoon Sweets)',
    city: 'Nafplio',
    category: 'food & drink',
    description: 'Spoon sweets (glyka tou koutaliou) are a beloved Greek tradition — whole fruits preserved in syrup, served on a spoon with coffee or over yogurt. Nafplio shops carry sour cherry, bergamot, fig, and walnut varieties.',
    photos: [
      'https://images.unsplash.com/photo-1759063293478-1d2a9348d696?w=800&q=80',
      'https://images.unsplash.com/photo-1588250977873-b15f82d8176f?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1759063293478-1d2a9348d696?w=800&q=80',
    address: 'Vasilissis Olgas 10, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5668, lng: 22.7988 },
    hours: '8:30 AM – 9:00 PM',
    closedOn: undefined,
    costEstimate: '$',
    costNote: '€4–€10 per jar',
    bookingRequired: false,
    whereToBuy: ['Traditional sweet shops in Nafplio Old Town', 'Antica Gelateria di Roma (next door sells preserves)', 'Nafplio farmers market'],
    tips: [
      'Sour cherry (vyssino) is the most classic flavor — perfect spooned over thick Greek yogurt.',
      'Bergamot spoon sweet from the Peloponnese is rare and incredibly aromatic.',
      'Glass jars travel well but wrap them in clothing in your checked bag just in case.',
    ],
    tags: ['food', 'traditional', 'nafplio', 'gift', 'sweets'],
  },

  // ============ SANTORINI (8) ============
  {
    id: 'shop-volcanic-lava-stone-jewelry',
    tab: 'shop',
    name: 'Volcanic Lava Stone Jewelry',
    city: 'Santorini',
    category: 'jewelry',
    description: 'Santorini\'s volcanic geology inspires local jewelers who work lava stone, obsidian, and volcanic glass into striking necklaces, bracelets, and earrings you won\'t find anywhere else.',
    photos: [
      'https://images.unsplash.com/photo-1545006547-eee2b9beddff?w=800&q=80',
      'https://images.unsplash.com/photo-1544327404-f6aed3d39dbf?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1545006547-eee2b9beddff?w=800&q=80',
    address: 'Oia Main Street, Oia, Santorini 847 02, Greece',
    coordinates: { lat: 36.4613, lng: 25.3753 },
    hours: '10:00 AM – 10:00 PM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€15–€120',
    bookingRequired: false,
    whereToBuy: ['Lava Santorini (Oia)', 'Mati Art Gallery (Fira)', 'Workshop shops along Oia caldera path'],
    tips: [
      'Lava stone is naturally porous — it can absorb essential oils for subtle fragrance.',
      'Pieces combined with sterling silver offer the best quality-to-price ratio.',
      'Check that "volcanic" jewelry actually contains real lava stone and isn\'t just painted resin.',
    ],
    tags: ['jewelry', 'volcanic', 'santorini', 'unique', 'handmade'],
  },
  {
    id: 'shop-santo-wines-non-alcoholic',
    tab: 'shop',
    name: 'Santo Wines Assyrtiko (Non-Alcoholic Products)',
    city: 'Santorini',
    category: 'food & drink',
    description: 'Santo Wines\' caldera-perched shop sells more than wine — their olive oils, grape vinegars, fruit jams, and preserves showcase Santorini\'s volcanic terroir in shelf-stable, giftable form.',
    photos: [
      'https://images.unsplash.com/photo-1580855453606-7a02774c686c?w=800&q=80',
      'https://images.unsplash.com/photo-1724412575242-5d1a62458751?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1580855453606-7a02774c686c?w=800&q=80',
    address: 'Pyrgos, Santorini 847 00, Greece',
    coordinates: { lat: 36.3780, lng: 25.4450 },
    hours: '10:00 AM – 11:00 PM (seasonal)',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€6–€25 per item',
    bookingRequired: false,
    whereToBuy: ['Santo Wines Winery Shop (Pyrgos)'],
    tips: [
      'Their Assyrtiko grape vinegar is outstanding for salad dressings and marinades.',
      'The caldera-view terrace is worth visiting even if you\'re only shopping for pantry goods.',
      'Olive oils and jams from the shop are exclusive products not available elsewhere.',
    ],
    tags: ['food', 'gourmet', 'santorini', 'gift'],
  },
  {
    id: 'shop-fira-gold-jewelry',
    tab: 'shop',
    name: 'Fira Gold & Jewelry Shops',
    city: 'Santorini',
    category: 'jewelry',
    description: 'Fira\'s main shopping street is lined with gold and jewelry shops offering everything from ancient Greek-inspired museum replicas to sleek contemporary designs. Prices are competitive by European standards.',
    photos: [
      'https://images.unsplash.com/photo-1654118890957-136cbada631e?w=800&q=80',
      'https://images.unsplash.com/photo-1652179326115-943d168c4cb2?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1654118890957-136cbada631e?w=800&q=80',
    address: '25is Martiou Street, Fira, Santorini 847 00, Greece',
    coordinates: { lat: 36.4166, lng: 25.4314 },
    hours: '10:00 AM – 11:00 PM',
    closedOn: undefined,
    costEstimate: '$$$',
    costNote: '€50–€500+',
    bookingRequired: false,
    whereToBuy: ['Kostas Antoniou Jewelry (Fira)', 'Byzantino Jewelry', 'Gold Street shops along 25is Martiou'],
    tips: [
      'Greek gold is typically 14K or 18K — always check the hallmark stamp.',
      'Museum-replica pieces from certified shops come with authenticity certificates.',
      'Compare prices at 3–4 shops before buying — markup varies significantly.',
    ],
    tags: ['jewelry', 'gold', 'santorini', 'luxury', 'shopping'],
  },
  {
    id: 'shop-oia-art-galleries-prints',
    tab: 'shop',
    name: 'Oia Art Galleries & Prints',
    city: 'Santorini',
    category: 'artisan',
    description: 'Oia has become a thriving artists\' colony, with dozens of galleries tucked into whitewashed cave houses along the caldera. You\'ll find paintings, sculptures, photography, and mixed media inspired by the island\'s dramatic light.',
    photos: [
      'https://images.unsplash.com/photo-1676730056228-7e38cbb88edc?w=800&q=80',
      'https://images.unsplash.com/photo-1625936716555-5577fb317a24?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1676730056228-7e38cbb88edc?w=800&q=80',
    address: 'Oia, Santorini 847 02, Greece',
    coordinates: { lat: 36.4618, lng: 25.3760 },
    hours: '10:00 AM – 10:00 PM',
    closedOn: undefined,
    costEstimate: '$$$',
    costNote: '€30–€2,000+',
    bookingRequired: false,
    whereToBuy: ['Art Gallery Oia (caldera walkway)', 'Mati Gallery', 'Oia Treasures Art Gallery'],
    tips: [
      'Smaller studios often offer better prices than the big caldera-front galleries.',
      'Many artists will ship large pieces internationally — ask about delivery options.',
      'Visit in the late afternoon when the light on the caldera is most magical.',
    ],
    tags: ['art', 'gallery', 'santorini', 'oia', 'artisan'],
  },
  {
    id: 'shop-santorini-fava-capers',
    tab: 'shop',
    name: 'Santorini Fava & Capers',
    city: 'Santorini',
    category: 'food & drink',
    description: 'Santorini\'s volcanic soil gives its split pea fava and wild capers an extraordinary concentrated flavor. These PDO-protected products are the island\'s culinary treasures and make lightweight gourmet gifts.',
    photos: [
      'https://images.unsplash.com/photo-1690324075771-f8b43b7b1bbc?w=800&q=80',
      'https://images.unsplash.com/photo-1724412575242-5d1a62458751?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1724412575242-5d1a62458751?w=800&q=80',
    address: 'Fira Town, Santorini 847 00, Greece',
    coordinates: { lat: 36.4170, lng: 25.4290 },
    hours: '9:00 AM – 9:00 PM',
    closedOn: undefined,
    costEstimate: '$',
    costNote: '€4–€10 per packet',
    bookingRequired: false,
    whereToBuy: ['Santorini Fava Factory (Fira)', 'Local grocery shops in Fira', 'Santo Wines shop'],
    tips: [
      'Fava Santorinis (yellow split pea puree) is the island\'s signature dish — buy the dried peas to recreate it at home.',
      'Caper leaves (kapari) are as prized as the buds and are harder to find outside Greece.',
      'These are lightweight, shelf-stable, and easy to pack — perfect carry-on souvenirs.',
    ],
    tags: ['food', 'gourmet', 'santorini', 'gift', 'lightweight'],
  },
  {
    id: 'shop-greek-evil-eye-jewelry-ornaments',
    tab: 'shop',
    name: 'Greek Evil Eye Jewelry & Ornaments',
    city: 'Santorini',
    category: 'jewelry',
    description: 'The mati (evil eye) is one of Greece\'s most recognizable symbols, believed to ward off negative energy. Santorini shops offer beautiful evil eye pieces in glass, gold, silver, and enamel.',
    photos: [
      'https://images.unsplash.com/photo-1544327404-f6aed3d39dbf?w=800&q=80',
      'https://images.unsplash.com/photo-1545006547-eee2b9beddff?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1544327404-f6aed3d39dbf?w=800&q=80',
    address: 'Fira Shopping Street, Fira, Santorini 847 00, Greece',
    coordinates: { lat: 36.4163, lng: 25.4320 },
    hours: '10:00 AM – 11:00 PM',
    closedOn: undefined,
    costEstimate: '$',
    costNote: '€5–€80',
    bookingRequired: false,
    whereToBuy: ['Jewelry shops along Fira\'s main street', 'Oia gift shops', 'Athens Airport duty-free'],
    tips: [
      'Handmade glass evil eyes from artisan workshops are far superior to mass-produced ones.',
      'Blue and white are traditional colors — gold-set versions make elegant gifts.',
      'It\'s tradition to receive one as a gift rather than buy for yourself, so they make perfect presents.',
    ],
    tags: ['jewelry', 'souvenir', 'santorini', 'traditional', 'gift'],
  },
  {
    id: 'shop-handmade-santorini-candles',
    tab: 'shop',
    name: 'Handmade Santorini Candles',
    city: 'Santorini',
    category: 'artisan',
    description: 'Artisan candle makers on Santorini craft hand-poured soy and beeswax candles scented with Aegean herbs, volcanic minerals, and island florals. Their minimalist Cycladic packaging makes them instant decor pieces.',
    photos: [
      'https://images.unsplash.com/photo-1652179326115-943d168c4cb2?w=800&q=80',
      'https://images.unsplash.com/photo-1654118890957-136cbada631e?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1652179326115-943d168c4cb2?w=800&q=80',
    address: 'Oia, Santorini 847 02, Greece',
    coordinates: { lat: 36.4610, lng: 25.3745 },
    hours: '10:00 AM – 10:00 PM',
    closedOn: undefined,
    costEstimate: '$',
    costNote: '€12–€35',
    bookingRequired: false,
    whereToBuy: ['Artisan candle shops in Oia', 'Fira boutique shops', 'Santorini airport gift shop'],
    tips: [
      'Soy candles burn cleaner and longer than paraffin — look for the soy or beeswax label.',
      'Volcanic ash and sea salt scented candles are unique to Santorini.',
      'They travel well in carry-on bags and make thoughtful, lightweight gifts.',
    ],
    tags: ['artisan', 'handmade', 'santorini', 'gift', 'home'],
  },
  {
    id: 'shop-thera-essential-oils-cosmetics',
    tab: 'shop',
    name: 'Thera Essential Oils & Cosmetics',
    city: 'Santorini',
    category: 'artisan',
    description: 'Named after Santorini\'s ancient name, Thera-brand cosmetics use locally sourced volcanic earth, grape seed oil, and island botanicals. Their essential oil blends and face masks capture the island\'s natural essence.',
    photos: [
      'https://images.unsplash.com/photo-1625936716555-5577fb317a24?w=800&q=80',
      'https://images.unsplash.com/photo-1676730056228-7e38cbb88edc?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1625936716555-5577fb317a24?w=800&q=80',
    address: '25is Martiou Street, Fira, Santorini 847 00, Greece',
    coordinates: { lat: 36.4168, lng: 25.4310 },
    hours: '9:30 AM – 10:00 PM',
    closedOn: undefined,
    costEstimate: '$$',
    costNote: '€10–€40',
    bookingRequired: false,
    whereToBuy: ['Thera Cosmetics shop (Fira)', 'Oia boutique stores', 'Santorini airport'],
    tips: [
      'The volcanic clay face mask is their bestseller and uses real Santorini earth.',
      'Essential oil blends with local herbs like thyme and oregano are wonderfully aromatic.',
      'All products are under 100ml so they\'re carry-on friendly.',
    ],
    tags: ['cosmetics', 'artisan', 'santorini', 'natural', 'gift'],
  },
];

export default shop;
