const sleep = [
  // ============ ATHENS (6) ============
  {
    id: 'sleep-hotel-grande-bretagne',
    tab: 'sleep',
    name: 'Hotel Grande Bretagne',
    city: 'Athens',
    category: 'luxury',
    isBooked: true,
    description: 'Athens\' most iconic luxury hotel since 1874, commanding Syntagma Square with direct views of the Acropolis. The rooftop restaurant and bar offer one of the best panoramas in the city.',
    photos: [
      'https://images.unsplash.com/photo-1594048234320-f2caf3dac5c0?w=800&q=80',
      'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1594048234320-f2caf3dac5c0?w=800&q=80',
    address: 'Vasileos Georgiou A\' 1, Syntagma Square, Athens 105 64, Greece',
    coordinates: { lat: 37.9755, lng: 23.7348 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$$$',
    costNote: '€350–€800 per night',
    phone: '+30 210 333 0000',
    website: 'https://www.marriott.com/hotels/travel/athgb-hotel-grande-bretagne-a-luxury-collection-hotel-athens/',
    amenities: ['Rooftop Pool', 'Spa', 'Rooftop Restaurant', 'Fitness Center', 'Concierge', 'Valet Parking'],
    tips: [
      'Book an Acropolis-view room — the sunset views from your balcony are extraordinary.',
      'The rooftop bar is open to non-guests too, but staying here means you can enjoy it at off-peak hours.',
    ],
    tags: ['luxury', 'historic', 'athens', 'acropolis-view', 'booked'],
  },
  {
    id: 'sleep-electra-palace-athens',
    tab: 'sleep',
    name: 'Electra Palace Athens',
    city: 'Athens',
    category: 'luxury',
    isBooked: false,
    description: 'A refined 5-star hotel in the heart of Plaka with a stunning rooftop pool and Acropolis views. Its neoclassical facade blends seamlessly with the historic neighborhood.',
    photos: [
      'https://images.unsplash.com/photo-1669706341369-1e40498d2e40?w=800&q=80',
      'https://images.unsplash.com/photo-1676831159775-604ec16e1c1f?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1669706341369-1e40498d2e40?w=800&q=80',
    address: 'Navarchou Nikodimou 18-20, Plaka, Athens 105 57, Greece',
    coordinates: { lat: 37.9735, lng: 23.7323 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$$',
    costNote: '€200–€450 per night',
    phone: '+30 210 337 0000',
    website: 'https://www.electrahotels.gr/electra-palace-athens/',
    amenities: ['Rooftop Pool', 'Spa', 'Restaurant', 'Fitness Center', 'Room Service', 'Concierge'],
    tips: [
      'The rooftop pool area is smaller than it looks in photos — go early morning to get a lounger.',
      'Location in Plaka is unbeatable for walking to the Acropolis and Monastiraki.',
    ],
    tags: ['luxury', 'athens', 'plaka', 'rooftop-pool'],
  },
  {
    id: 'sleep-athenswas-hotel',
    tab: 'sleep',
    name: 'AthensWas Hotel',
    city: 'Athens',
    category: 'boutique',
    isBooked: false,
    description: 'A sleek design hotel on the pedestrian boulevard below the Acropolis, blending mid-century modern furniture with contemporary Greek art. The rooftop terrace has unobstructed Parthenon views.',
    photos: [
      'https://images.unsplash.com/photo-1666192179043-5aad64280d63?w=800&q=80',
      'https://images.unsplash.com/photo-1594048234320-f2caf3dac5c0?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1666192179043-5aad64280d63?w=800&q=80',
    address: 'Dionysiou Areopagitou 5, Athens 117 42, Greece',
    coordinates: { lat: 37.9700, lng: 23.7280 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$$',
    costNote: '€180–€380 per night',
    phone: '+30 210 924 9954',
    website: 'https://www.athenswas.gr/',
    amenities: ['Rooftop Terrace', 'Restaurant', 'Bar', 'Fitness Center', 'Concierge'],
    tips: [
      'Rooms on higher floors facing the Acropolis are worth the upgrade.',
      'Located on the best pedestrian street in Athens — the Acropolis Museum is a 2-minute walk.',
    ],
    tags: ['boutique', 'design', 'athens', 'acropolis-view'],
  },
  {
    id: 'sleep-athens-gate-hotel',
    tab: 'sleep',
    name: 'Athens Gate Hotel',
    city: 'Athens',
    category: 'mid-range',
    isBooked: false,
    description: 'A well-located mid-range hotel directly opposite the Temple of Olympian Zeus and Hadrian\'s Arch. The rooftop restaurant offers some of the most affordable Acropolis views in the city.',
    photos: [
      'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
      'https://images.unsplash.com/photo-1669706341369-1e40498d2e40?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
    address: 'Syngrou Avenue 10, Athens 117 42, Greece',
    coordinates: { lat: 37.9695, lng: 23.7310 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$',
    costNote: '€100–€200 per night',
    phone: '+30 210 923 8302',
    website: 'https://www.athensgate.gr/',
    amenities: ['Rooftop Restaurant', 'Bar', 'Room Service', 'Concierge', 'Free Wi-Fi'],
    tips: [
      'Ask for a room with a Temple of Zeus view — it\'s extraordinary to wake up to.',
      'The rooftop breakfast with Acropolis views is included in most rates and is excellent value.',
    ],
    tags: ['mid-range', 'athens', 'value', 'acropolis-view'],
  },
  {
    id: 'sleep-coco-mat-athens-bc',
    tab: 'sleep',
    name: 'Coco-Mat Athens BC',
    city: 'Athens',
    category: 'boutique',
    isBooked: false,
    description: 'A design-forward boutique hotel by the famous Greek mattress brand, ensuring the best sleep in Athens. The rooftop pool and bar have panoramic views over the city.',
    photos: [
      'https://images.unsplash.com/photo-1676831159775-604ec16e1c1f?w=800&q=80',
      'https://images.unsplash.com/photo-1666192179043-5aad64280d63?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1676831159775-604ec16e1c1f?w=800&q=80',
    address: 'Patriarchou Ioakeim 36, Kolonaki, Athens 106 75, Greece',
    coordinates: { lat: 37.9770, lng: 23.7420 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$$',
    costNote: '€160–€320 per night',
    phone: '+30 210 723 0000',
    website: 'https://www.coco-mat-athens.com/',
    amenities: ['Rooftop Pool', 'Bar', 'Restaurant', 'Fitness Center', 'Bicycle Rental', 'Pillow Menu'],
    tips: [
      'Try different pillows from their pillow menu — it\'s the whole point of a Coco-Mat stay.',
      'Borrow one of their free bikes to explore the nearby National Garden and Plaka.',
    ],
    tags: ['boutique', 'design', 'athens', 'kolonaki', 'wellness'],
  },
  {
    id: 'sleep-plaka-hotel',
    tab: 'sleep',
    name: 'Plaka Hotel',
    city: 'Athens',
    category: 'mid-range',
    isBooked: false,
    description: 'A friendly, well-priced hotel in the heart of Plaka with a rooftop terrace offering Acropolis views that rival hotels at twice the price. Rooms are compact but clean and recently refreshed.',
    photos: [
      'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
      'https://images.unsplash.com/photo-1676831159775-604ec16e1c1f?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
    address: 'Kapnikareas 7 & Mitropoleos, Plaka, Athens 105 56, Greece',
    coordinates: { lat: 37.9748, lng: 23.7270 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$',
    costNote: '€90–€170 per night',
    phone: '+30 210 322 2096',
    website: 'https://www.plakahotel.gr/',
    amenities: ['Rooftop Terrace', 'Breakfast Included', 'Free Wi-Fi', 'Concierge', 'Luggage Storage'],
    tips: [
      'The rooftop terrace is the real selling point — grab a coffee there at sunset for stunning Acropolis views.',
      'Location could not be more central — Monastiraki, Syntagma, and the Acropolis are all within a 10-minute walk.',
    ],
    tags: ['mid-range', 'athens', 'plaka', 'value', 'acropolis-view'],
  },

  // ============ NAFPLIO (6) ============
  {
    id: 'sleep-amphitryon-hotel',
    tab: 'sleep',
    name: 'Amphitryon Hotel',
    city: 'Nafplio',
    category: 'luxury',
    isBooked: true,
    description: 'A refined waterfront hotel gazing across the Argolic Gulf toward the Bourtzi fortress. The private beach, elegant rooms, and outstanding service make it Nafplio\'s premier luxury stay.',
    photos: [
      'https://images.unsplash.com/photo-1751060867787-3d28ea3d6e22?w=800&q=80',
      'https://images.unsplash.com/photo-1677336068327-e0e545dbf13a?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1751060867787-3d28ea3d6e22?w=800&q=80',
    address: 'Spiliadou 31, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5640, lng: 22.7960 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$$$',
    costNote: '€250–€500 per night',
    phone: '+30 27520 70700',
    website: 'https://www.amphitryon.gr/',
    amenities: ['Private Beach', 'Pool', 'Restaurant', 'Bar', 'Spa', 'Concierge', 'Parking'],
    tips: [
      'Book a sea-view room facing the Bourtzi fortress — the sunset views are magical.',
      'The hotel is a short walk from the old town but feels like a private retreat.',
    ],
    tags: ['luxury', 'waterfront', 'nafplio', 'sea-view', 'booked'],
  },
  {
    id: 'sleep-nafplia-palace',
    tab: 'sleep',
    name: 'Nafplia Palace',
    city: 'Nafplio',
    category: 'luxury',
    isBooked: false,
    description: 'Perched on the Acronafplia hill above the old town, this sprawling hotel and bungalow complex offers commanding views of the sea and Palamidi fortress. Accessible by elevator carved through the rock.',
    photos: [
      'https://images.unsplash.com/photo-1677336068327-e0e545dbf13a?w=800&q=80',
      'https://images.unsplash.com/photo-1588250977873-b15f82d8176f?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1677336068327-e0e545dbf13a?w=800&q=80',
    address: 'Acronafplia, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5630, lng: 22.7935 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$$',
    costNote: '€180–€400 per night',
    phone: '+30 27520 28981',
    website: 'https://www.nafpliapalace.gr/',
    amenities: ['Pool', 'Restaurant', 'Bar', 'Spa', 'Tennis Court', 'Parking', 'Elevator to Old Town'],
    tips: [
      'The bungalows with private plunge pools are a splurge worth every euro.',
      'Use the rock-carved elevator to descend directly into the old town.',
    ],
    tags: ['luxury', 'nafplio', 'hilltop', 'panoramic-view'],
  },
  {
    id: 'sleep-3sixty-hotel-suites',
    tab: 'sleep',
    name: '3Sixty Hotel & Suites',
    city: 'Nafplio',
    category: 'boutique',
    isBooked: false,
    description: 'A stylish boutique hotel in a restored neoclassical building in the heart of Nafplio\'s old town. Rooms blend exposed stone walls with modern minimalist design.',
    photos: [
      'https://images.unsplash.com/photo-1588250977873-b15f82d8176f?w=800&q=80',
      'https://images.unsplash.com/photo-1759063293478-1d2a9348d696?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1588250977873-b15f82d8176f?w=800&q=80',
    address: 'Ellinon Anapiron 2, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5670, lng: 22.7990 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$$',
    costNote: '€150–€300 per night',
    phone: '+30 27520 21338',
    website: 'https://www.3sixty.gr/',
    amenities: ['Breakfast Included', 'Bar', 'Room Service', 'Concierge', 'Free Wi-Fi'],
    tips: [
      'The suite with the private terrace overlooking the rooftops is the best room in the house.',
      'Location is perfect — steps from Syntagma Square and all the best restaurants.',
    ],
    tags: ['boutique', 'nafplio', 'old-town', 'design'],
  },
  {
    id: 'sleep-pension-marianna',
    tab: 'sleep',
    name: 'Pension Marianna',
    city: 'Nafplio',
    category: 'budget',
    isBooked: false,
    description: 'A family-run guesthouse tucked against the Acronafplia walls, reached by climbing stone steps through the old town. Simple but charming rooms with balconies and stunning views over the rooftops and sea.',
    photos: [
      'https://images.unsplash.com/photo-1602348143971-0c5c97d23367?w=800&q=80',
      'https://images.unsplash.com/photo-1602348709085-bc5720f99fd5?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1602348143971-0c5c97d23367?w=800&q=80',
    address: 'Potamianou 9, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5660, lng: 22.7945 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$',
    costNote: '€70–€120 per night',
    phone: '+30 27520 24256',
    website: null,
    amenities: ['Breakfast Included', 'Balcony', 'Free Wi-Fi', 'Sea View'],
    tips: [
      'There are many steps up to the pension — pack light or be prepared for a workout.',
      'The views from the terrace at breakfast are better than hotels charging three times the price.',
    ],
    tags: ['budget', 'nafplio', 'family-run', 'sea-view', 'value'],
  },
  {
    id: 'sleep-aetoma-hotel',
    tab: 'sleep',
    name: 'Aetoma Hotel',
    city: 'Nafplio',
    category: 'mid-range',
    isBooked: false,
    description: 'A well-maintained mid-range hotel in a beautifully restored building on the edge of Nafplio\'s old town. Rooms are comfortable and the location provides easy access to both the town and the waterfront.',
    photos: [
      'https://images.unsplash.com/photo-1602348709085-bc5720f99fd5?w=800&q=80',
      'https://images.unsplash.com/photo-1751060867787-3d28ea3d6e22?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1602348709085-bc5720f99fd5?w=800&q=80',
    address: 'Kapodistriou 39, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5680, lng: 22.8015 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$',
    costNote: '€80–€150 per night',
    phone: '+30 27520 27373',
    website: 'https://www.aetomahotel.gr/',
    amenities: ['Breakfast Included', 'Garden', 'Free Wi-Fi', 'Parking Nearby', 'Concierge'],
    tips: [
      'The garden courtyard is a lovely spot for morning coffee before heading out.',
      'Ask for a room on the upper floor for better views and more natural light.',
    ],
    tags: ['mid-range', 'nafplio', 'old-town', 'value'],
  },
  {
    id: 'sleep-ippoliti-hotel',
    tab: 'sleep',
    name: 'Ippoliti Hotel',
    city: 'Nafplio',
    category: 'boutique',
    isBooked: false,
    description: 'A charming boutique hotel housed in two restored neoclassical mansions on Nafplio\'s main square. The individually decorated rooms feature period furniture, high ceilings, and original architectural details.',
    photos: [
      'https://images.unsplash.com/photo-1759063293478-1d2a9348d696?w=800&q=80',
      'https://images.unsplash.com/photo-1602348143971-0c5c97d23367?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1759063293478-1d2a9348d696?w=800&q=80',
    address: 'Plateia Syntagmatos 9, Nafplio 211 00, Greece',
    coordinates: { lat: 37.5674, lng: 22.7982 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$$',
    costNote: '€140–€280 per night',
    phone: '+30 27520 22722',
    website: 'https://www.ippoliti.gr/',
    amenities: ['Breakfast Included', 'Garden Courtyard', 'Bar', 'Free Wi-Fi', 'Concierge', 'Room Service'],
    tips: [
      'Request a room in the original mansion wing for the most character and highest ceilings.',
      'The location on Syntagma Square means cafes, restaurants, and the old town are right outside your door.',
    ],
    tags: ['boutique', 'nafplio', 'historic', 'central', 'romantic'],
  },

  // ============ CRETE (5) ============
  {
    id: 'sleep-gdm-megaron',
    tab: 'sleep',
    name: 'GDM Megaron Luxury Hotel',
    city: 'Crete',
    category: 'luxury',
    isBooked: true,
    description: 'A premier waterfront luxury hotel on the Heraklion harbor, GDM Megaron offers refined elegance with panoramic sea views, a rooftop pool, and impeccable service. The sleek rooms feature marble bathrooms and private balconies overlooking the Venetian fortress of Koules.',
    photos: [
      'https://images.unsplash.com/photo-1570303345338-e1f0eddf4946?w=800&q=80',
      'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1570303345338-e1f0eddf4946?w=800&q=80',
    address: 'Doukas Beaufort 9, Heraklion 712 02, Greece',
    coordinates: { lat: 35.3440, lng: 25.1310 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$$$',
    costNote: '€200–€450 per night',
    phone: '+30 281 030 5300',
    website: 'https://www.gdmmegaron.gr/',
    amenities: ['Rooftop Pool', 'Spa', 'Restaurant', 'Bar', 'Fitness Center', 'Concierge', 'Sea View'],
    tips: [
      'Book a sea-view room facing the Venetian harbor — the fortress views at sunset are spectacular.',
      'The rooftop pool and bar are a highlight — perfect for unwinding after a day at Knossos.',
    ],
    tags: ['luxury', 'waterfront', 'crete', 'sea-view', 'booked'],
  },
  {
    id: 'sleep-lato-boutique-hotel',
    tab: 'sleep',
    name: 'Lato Boutique Hotel',
    city: 'Crete',
    category: 'boutique',
    isBooked: false,
    description: 'A stylish boutique hotel with a prime location overlooking the old Venetian harbor of Heraklion. Lato combines contemporary design with warm Cretan hospitality. The Brilliant Restaurant on the top floor is regarded as one of the best in the city, and harbor-view rooms offer stunning vistas.',
    photos: [
      'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
      'https://images.unsplash.com/photo-1504512485720-7d83a16ee930?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    address: 'Epimenidou 15, Heraklion 712 02, Greece',
    coordinates: { lat: 35.3430, lng: 25.1325 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$$',
    costNote: '€130–€280 per night',
    phone: '+30 281 022 8103',
    website: 'https://www.lato.gr/',
    amenities: ['Restaurant', 'Bar', 'Room Service', 'Concierge', 'Free Wi-Fi', 'Harbor View'],
    tips: [
      'Request a harbor-view room — the views of the Venetian port and Koules fortress are worth the upgrade.',
      'The Brilliant Restaurant upstairs is excellent for dinner even if you are not a guest.',
    ],
    tags: ['boutique', 'crete', 'harbor-view', 'central'],
  },
  {
    id: 'sleep-olive-green-hotel',
    tab: 'sleep',
    name: 'Olive Green Hotel',
    city: 'Crete',
    category: 'boutique',
    isBooked: false,
    description: 'An eco-friendly boutique hotel in the heart of Heraklion old town, the Olive Green is built with sustainable materials and runs on green energy. The modern, minimalist rooms feature smart technology, and the central location puts you steps from Lions Square, the market, and all major sights.',
    photos: [
      'https://images.unsplash.com/photo-1504512485720-7d83a16ee930?w=800&q=80',
      'https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1504512485720-7d83a16ee930?w=800&q=80',
    address: 'Meramvellou 3 & Idomeneos, Heraklion 712 02, Greece',
    coordinates: { lat: 35.3390, lng: 25.1320 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$',
    costNote: '€80–€160 per night',
    phone: '+30 281 030 2900',
    website: 'https://www.olivegreenhotel.com/',
    amenities: ['Eco-Friendly', 'Smart Room Controls', 'Breakfast Available', 'Free Wi-Fi', 'Concierge', 'Bicycle Rental'],
    tips: [
      'The location is unbeatable — Lions Square, the 1866 Market, and the Archaeological Museum are all within a 5-minute walk.',
      'A great choice for eco-conscious travelers who want modern comfort without a large environmental footprint.',
    ],
    tags: ['boutique', 'eco-friendly', 'crete', 'old-town', 'central'],
  },
  {
    id: 'sleep-galaxy-hotel-iraklio',
    tab: 'sleep',
    name: 'Galaxy Hotel Iraklio',
    city: 'Crete',
    category: 'mid-range',
    isBooked: false,
    description: 'A modern, well-appointed mid-range hotel offering comfortable rooms, a rooftop pool, and reliable service. The Galaxy is a solid choice for travelers who want a quality stay without luxury prices. Its location is slightly outside the old town center but well-connected by foot.',
    photos: [
      'https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=800&q=80',
      'https://images.unsplash.com/photo-1598889272668-64e8b2d04a1b?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=800&q=80',
    address: 'Dimokratias Avenue 75, Heraklion 713 06, Greece',
    coordinates: { lat: 35.3340, lng: 25.1280 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$',
    costNote: '€90–€180 per night',
    phone: '+30 281 023 8812',
    website: 'https://www.galaxy-hotel.com/',
    amenities: ['Rooftop Pool', 'Restaurant', 'Bar', 'Fitness Center', 'Free Wi-Fi', 'Parking'],
    tips: [
      'The rooftop pool is a great bonus at this price point — enjoy it after a day of sightseeing.',
      'About a 15-minute walk to the old town center — easy and pleasant along the main avenue.',
    ],
    tags: ['mid-range', 'crete', 'modern', 'value'],
  },
  {
    id: 'sleep-kronos-hotel',
    tab: 'sleep',
    name: 'Kronos Hotel',
    city: 'Crete',
    category: 'budget',
    isBooked: false,
    description: 'A friendly, budget-friendly hotel steps from the Venetian harbor and old town of Heraklion. Rooms are simple but clean and well-maintained, and the welcoming staff go out of their way to help with local recommendations. An excellent base for exploring Heraklion without breaking the bank.',
    photos: [
      'https://images.unsplash.com/photo-1598889272668-64e8b2d04a1b?w=800&q=80',
      'https://images.unsplash.com/photo-1564594985645-4427056e22e2?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1598889272668-64e8b2d04a1b?w=800&q=80',
    address: 'Sofokli Venizelou 2, Heraklion 712 02, Greece',
    coordinates: { lat: 35.3447, lng: 25.1342 },
    hours: 'Check-in 2pm / Check-out 11am',
    costEstimate: '$',
    costNote: '€50–€90 per night',
    phone: '+30 281 028 2240',
    website: 'https://www.kronoshotel.gr/',
    amenities: ['Breakfast Available', 'Free Wi-Fi', 'Air Conditioning', 'Luggage Storage', 'Tour Desk'],
    tips: [
      'The harbor location is the real draw — Koules fortress and the waterfront promenade are right outside.',
      'Great value for the location — you are paying a fraction of what harbor-front hotels in Santorini charge.',
    ],
    tags: ['budget', 'crete', 'harbor', 'value', 'central'],
  },

  // ============ SANTORINI (6) ============
  {
    id: 'sleep-canaves-oia-suites',
    tab: 'sleep',
    name: 'Canaves Oia Suites',
    city: 'Santorini',
    category: 'luxury',
    isBooked: true,
    description: 'One of Santorini\'s most celebrated luxury hotels, carved into the Oia caldera cliffs with infinity pools that seem to pour into the Aegean. Every suite has a private plunge pool and uninterrupted sunset views.',
    photos: [
      'https://images.unsplash.com/photo-1690324075771-f8b43b7b1bbc?w=800&q=80',
      'https://images.unsplash.com/photo-1580855453606-7a02774c686c?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1690324075771-f8b43b7b1bbc?w=800&q=80',
    address: 'Oia, Santorini 847 02, Greece',
    coordinates: { lat: 36.4615, lng: 25.3720 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$$$',
    costNote: '€500–€1,500 per night',
    phone: '+30 22860 72001',
    website: 'https://www.canaves.com/canaves-oia-suites/',
    amenities: ['Private Plunge Pool', 'Infinity Pool', 'Spa', 'Restaurant', 'Bar', 'Concierge', 'Airport Transfer'],
    tips: [
      'Book a Honeymoon Suite for the most private caldera views and largest plunge pool.',
      'Request the sunset dinner setup on your private terrace — it\'s unforgettable.',
    ],
    tags: ['luxury', 'santorini', 'oia', 'caldera', 'sunset', 'booked'],
  },
  {
    id: 'sleep-katikies-hotel',
    tab: 'sleep',
    name: 'Katikies Hotel',
    city: 'Santorini',
    category: 'luxury',
    isBooked: false,
    description: 'A whitewashed cliff-side masterpiece in Oia, Katikies is regularly named among the world\'s best hotels. Its cascading infinity pools, cave suites, and Mikrasia restaurant define Santorini luxury.',
    photos: [
      'https://images.unsplash.com/photo-1580855453606-7a02774c686c?w=800&q=80',
      'https://images.unsplash.com/photo-1545006547-eee2b9beddff?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1580855453606-7a02774c686c?w=800&q=80',
    address: 'Oia, Santorini 847 02, Greece',
    coordinates: { lat: 36.4620, lng: 25.3730 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$$$',
    costNote: '€450–€1,200 per night',
    phone: '+30 22860 71401',
    website: 'https://www.katikies.com/',
    amenities: ['Infinity Pool', 'Spa', 'Fine Dining Restaurant', 'Bar', 'Concierge', 'Butler Service'],
    tips: [
      'Mikrasia restaurant is worth dining at even if you\'re not a guest — book well in advance.',
      'The three-tiered infinity pools are the most photographed in all of Greece.',
    ],
    tags: ['luxury', 'santorini', 'oia', 'iconic', 'world-class'],
  },
  {
    id: 'sleep-grace-hotel-santorini',
    tab: 'sleep',
    name: 'Grace Hotel Santorini (Auberge)',
    city: 'Santorini',
    category: 'luxury',
    isBooked: false,
    description: 'Perched high on the Imerovigli caldera, this Auberge Resorts Collection property offers a serene alternative to Oia\'s bustle. The cliffside infinity pool and exceptional Greek-Mediterranean restaurant are standouts.',
    photos: [
      'https://images.unsplash.com/photo-1544327404-f6aed3d39dbf?w=800&q=80',
      'https://images.unsplash.com/photo-1724412575242-5d1a62458751?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1544327404-f6aed3d39dbf?w=800&q=80',
    address: 'Imerovigli, Santorini 847 00, Greece',
    coordinates: { lat: 36.4320, lng: 25.4230 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$$$',
    costNote: '€400–€1,000 per night',
    phone: '+30 22860 21300',
    website: 'https://www.aubergeresorts.com/gracehotel/',
    amenities: ['Infinity Pool', 'Spa', 'Fine Dining', 'Yoga Classes', 'Bar', 'Concierge', 'Helipad'],
    tips: [
      'Imerovigli is quieter than Oia but has equally stunning sunset views with fewer crowds.',
      'The Skaros Rock hike starts right from the hotel — do it at sunrise for an unforgettable experience.',
    ],
    tags: ['luxury', 'santorini', 'imerovigli', 'caldera', 'tranquil'],
  },
  {
    id: 'sleep-cosmopolitan-suites',
    tab: 'sleep',
    name: 'Cosmopolitan Suites',
    city: 'Santorini',
    category: 'boutique',
    isBooked: false,
    description: 'A stylish boutique hotel on the Fira caldera rim offering big luxury-hotel views at a more approachable price. Each suite features cave-style architecture with modern furnishings and a private jacuzzi or plunge pool.',
    photos: [
      'https://images.unsplash.com/photo-1654118890957-136cbada631e?w=800&q=80',
      'https://images.unsplash.com/photo-1652179326115-943d168c4cb2?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1654118890957-136cbada631e?w=800&q=80',
    address: 'Fira, Santorini 847 00, Greece',
    coordinates: { lat: 36.4175, lng: 25.4280 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$$',
    costNote: '€200–€450 per night',
    phone: '+30 22860 25550',
    website: 'https://www.cosmopolitan-suites.com/',
    amenities: ['Private Jacuzzi', 'Caldera View', 'Breakfast Included', 'Bar', 'Concierge', 'Free Wi-Fi'],
    tips: [
      'Great value for a caldera-view hotel — you get the same views as €800/night places.',
      'Fira is the island\'s hub so you\'re walking distance from restaurants, shops, and nightlife.',
    ],
    tags: ['boutique', 'santorini', 'fira', 'caldera', 'value'],
  },
  {
    id: 'sleep-astra-suites',
    tab: 'sleep',
    name: 'Astra Suites',
    city: 'Santorini',
    category: 'boutique',
    isBooked: false,
    description: 'Consistently rated among the top small hotels in Europe, Astra Suites in Imerovigli delivers impeccable personal service, spacious cave suites, and one of the most scenic infinity pools on the island.',
    photos: [
      'https://images.unsplash.com/photo-1676730056228-7e38cbb88edc?w=800&q=80',
      'https://images.unsplash.com/photo-1625936716555-5577fb317a24?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1676730056228-7e38cbb88edc?w=800&q=80',
    address: 'Imerovigli, Santorini 847 00, Greece',
    coordinates: { lat: 36.4330, lng: 25.4215 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$$',
    costNote: '€250–€550 per night',
    phone: '+30 22860 23641',
    website: 'https://www.astrasuites.com/',
    amenities: ['Infinity Pool', 'Hot Tub', 'Breakfast Included', 'Bar', 'Concierge', 'Free Wi-Fi', 'Airport Transfer'],
    tips: [
      'The honeymoon suite with a private heated plunge pool is legendary — book months in advance.',
      'Staff will arrange private boat tours to the volcanic hot springs and Thirassia island.',
    ],
    tags: ['boutique', 'santorini', 'imerovigli', 'top-rated', 'romantic'],
  },
  {
    id: 'sleep-fira-backpackers-place',
    tab: 'sleep',
    name: 'Fira Backpackers Place',
    city: 'Santorini',
    category: 'budget',
    isBooked: false,
    description: 'The go-to budget option in Santorini, offering clean dorms and private rooms just minutes from the Fira caldera edge. A lively communal terrace makes it easy to meet fellow travelers.',
    photos: [
      'https://images.unsplash.com/photo-1652179326115-943d168c4cb2?w=800&q=80',
      'https://images.unsplash.com/photo-1654118890957-136cbada631e?w=800&q=80',
    ],
    heroPhoto: 'https://images.unsplash.com/photo-1652179326115-943d168c4cb2?w=800&q=80',
    address: 'Fira, Santorini 847 00, Greece',
    coordinates: { lat: 36.4160, lng: 25.4325 },
    hours: 'Check-in 3pm / Check-out 11am',
    costEstimate: '$$',
    costNote: '€30–€80 per night',
    phone: '+30 22860 24825',
    website: null,
    amenities: ['Shared Kitchen', 'Terrace', 'Free Wi-Fi', 'Lockers', 'Laundry', 'Common Room'],
    tips: [
      'Book a private room instead of a dorm if you want quiet — the social scene can get lively.',
      'The caldera sunset is a free 5-minute walk away — no need to pay for a view hotel.',
    ],
    tags: ['budget', 'santorini', 'fira', 'backpacker', 'social'],
  },
];

export default sleep;
