const activities = [
  {
    id: 'act-levada-balcoes',
    tab: 'activities',
    name: 'Levada dos Balcões Walk',
    category: 'hiking',
    description: 'A gentle levada walk through the laurel forest ending at a breathtaking viewpoint over the Ribeira da Metade valley.',
    photos: ['https://images.unsplash.com/photo-1721241843748-24202060eb45?w=800&q=80', 'https://images.unsplash.com/photo-1616878031706-b124365b4869?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1721241843748-24202060eb45?w=800&q=80',
    address: 'Ribeiro Frio, Santana',
    coordinates: { lat: 32.7500, lng: -16.8833 },
    hours: 'Daylight hours',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '1.5 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Starts from the Ribeiro Frio forestry park — easy to find',
      'Flat the entire way with levada alongside',
      'The viewpoint at the end often has firecrest birds',
    ],
    tags: ['levada', 'hiking', 'easy', 'nature', 'free'],
  },
  {
    id: 'act-toboggan',
    tab: 'activities',
    name: 'Monte Toboggan Ride',
    category: 'experience',
    description: 'Traditional wicker basket sledge ride down the steep streets from Monte to Livramento, steered by carreiros in white.',
    photos: ['https://images.unsplash.com/photo-1612427849005-10994e6eec4c?w=800&q=80', 'https://images.unsplash.com/photo-1690483707714-431c204032a2?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1690483707714-431c204032a2?w=800&q=80',
    address: 'Largo da Fonte, Monte, Funchal',
    coordinates: { lat: 32.6675, lng: -16.9031 },
    hours: 'Mon–Sat 9am–6pm',
    costEstimate: '$$',
    costNote: '€30 for 2 people / €25 for 1 person',
    duration: '10-15 min ride',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'The ride is about 2 km downhill — exhilarating!',
      'Pair it with the Monte Palace Garden visit',
      'Cash only for the ride',
    ],
    tags: ['iconic', 'unique', 'monte', 'fun'],
  },
  {
    id: 'act-pr1-trail',
    tab: 'activities',
    name: 'PR1 Pico do Arieiro to Pico Ruivo',
    category: 'hiking',
    description: 'Madeira\'s most spectacular mountain trail connecting the two highest peaks along a dramatic ridge line above the clouds.',
    photos: ['https://images.unsplash.com/photo-1667766465010-41c5c5eab9ce?w=800&q=80', 'https://images.unsplash.com/photo-1690483708338-6cea52aa02b3?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1690483708338-6cea52aa02b3?w=800&q=80',
    address: 'Pico do Arieiro car park',
    coordinates: { lat: 32.7356, lng: -16.9281 },
    hours: 'Daylight hours (start early)',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '5-6 hours',
    difficulty: 'moderate',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Start before sunrise for magical light',
      'Bring headlamp for the tunnels, water, and layers',
      'Return the same way or arrange a taxi pickup at Achada do Teixeira',
    ],
    tags: ['hiking', 'mountain', 'sunrise', 'challenging', 'scenic'],
  },
  {
    id: 'act-wine-tour',
    tab: 'activities',
    name: 'Blandy\'s Wine Lodge Tour',
    category: 'food & drink',
    description: 'Tour the historic wine lodge in Funchal, learn about Madeira wine production, and taste several vintages.',
    photos: ['https://images.unsplash.com/photo-1714136180128-00905ac71ee7?w=800&q=80', 'https://images.unsplash.com/photo-1674994035340-04635d2bf54d?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1714136180128-00905ac71ee7?w=800&q=80',
    address: 'Avenida Arriaga 28, Funchal',
    coordinates: { lat: 32.6461, lng: -16.9108 },
    hours: 'Mon–Fri 10am–6:30pm, Sat 10am–1pm',
    costEstimate: '$$',
    costNote: '€15 standard / €25 premium / €35 vintage tasting',
    duration: '1.5 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: '+351 291 228 978',
    website: 'https://www.bfrancis.com/visits',
    bookingUrl: 'https://www.bfrancis.com/visits',
    tips: [
      'Book the premium tasting — the vintage wines are worth it',
      'The cellar dates back to 1811',
      'Buy wine here rather than souvenir shops — better selection and prices',
    ],
    tags: ['wine', 'tasting', 'culture', 'funchal'],
  },
  {
    id: 'act-dolphin-watch',
    tab: 'activities',
    name: 'Dolphin & Whale Watching',
    category: 'water',
    description: 'Boat trip from Funchal marina to spot bottlenose dolphins, pilot whales, and — if lucky — sperm whales in the deep Atlantic waters.',
    photos: ['https://images.unsplash.com/photo-1725992245371-a822cff4e2d0?w=800&q=80', 'https://images.unsplash.com/photo-1632389448299-21bb362faf29?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1725992245371-a822cff4e2d0?w=800&q=80',
    address: 'Funchal Marina',
    coordinates: { lat: 32.6431, lng: -16.9106 },
    hours: 'Departures 10am & 3pm (seasonal)',
    costEstimate: '$$',
    costNote: '€40-55 per person',
    duration: '3 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Morning trips tend to have calmer seas',
      'Bring sunscreen and a light jacket — it\'s windier on the water',
      'Most operators guarantee a second trip free if no sightings',
    ],
    tags: ['boat', 'wildlife', 'ocean', 'dolphins', 'whales'],
  },
  {
    id: 'act-canyoning',
    tab: 'activities',
    name: 'Canyoning in Ribeira das Cales',
    category: 'adventure',
    description: 'Descend through waterfalls, natural slides, and jump pools in one of Madeira\'s lush canyon systems with expert guides.',
    photos: ['https://images.unsplash.com/photo-1735463256774-d8624f54448b?w=800&q=80', 'https://images.unsplash.com/photo-1635181738094-f82aee7b0aa7?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1735463256774-d8624f54448b?w=800&q=80',
    address: 'Ribeira das Cales, São Vicente',
    coordinates: { lat: 32.7600, lng: -17.0200 },
    hours: 'By appointment',
    costEstimate: '$$',
    costNote: '€55 per person (equipment included)',
    duration: '4 hours (including transport)',
    difficulty: 'moderate',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'No experience needed — guides handle all rope work',
      'Wear swimwear under clothes; wetsuit provided',
      'Waterproof camera recommended',
    ],
    tags: ['adventure', 'waterfall', 'outdoor', 'guided'],
  },
  {
    id: 'act-levada-caldeirao',
    tab: 'activities',
    name: 'Levada do Caldeirão Verde (PR9)',
    category: 'hiking',
    description: 'A dramatic levada walk through tunnels and along sheer cliffs to the emerald pools of Caldeirão Verde waterfall in the island\'s heart.',
    photos: ['https://images.unsplash.com/photo-1721241843687-fed85df281d1?w=800&q=80', 'https://images.unsplash.com/photo-1773399204793-20a25586e9c2?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1721241843687-fed85df281d1?w=800&q=80',
    address: 'Queimadas Forest Park, Santana',
    coordinates: { lat: 32.7583, lng: -16.8917 },
    hours: 'Daylight hours',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '3 hours',
    difficulty: 'moderate',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Several dark tunnels — bring a headlamp',
      'Not for those with vertigo — steep drops alongside the path',
      'Swimming possible at the waterfall base',
    ],
    tags: ['levada', 'hiking', 'waterfall', 'moderate', 'tunnels'],
  },
  {
    id: 'act-levada-25fontes',
    tab: 'activities',
    name: 'Levada das 25 Fontes (PR6)',
    category: 'hiking',
    description: 'A scenic levada walk to a spectacular waterfall surrounded by 25 springs cascading down a volcanic rock face.',
    photos: ['https://images.unsplash.com/photo-1721241843726-628eeca3efe3?w=800&q=80', 'https://images.unsplash.com/photo-1721241843448-af1c8ade1835?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1721241843726-628eeca3efe3?w=800&q=80',
    address: 'Rabaçal Forestry Park, West Madeira',
    coordinates: { lat: 32.7650, lng: -17.0933 },
    hours: 'Daylight hours',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '2.5 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Start early to avoid afternoon clouds',
      'The waterfall is most impressive after rain',
      'Pair with nearby Levada do Risco walk',
    ],
    tags: ['levada', 'hiking', 'waterfall', 'easy', 'scenic'],
  },
  {
    id: 'act-ponta-sao-lourenco',
    tab: 'activities',
    name: 'Ponta de São Lourenço Hike (PR8)',
    category: 'hiking',
    description: 'Walk along dramatic windswept cliffs on Madeira\'s easternmost peninsula, with sweeping ocean views and unusual semi-desert vegetation.',
    photos: ['https://images.unsplash.com/photo-1667766528699-d0d2db8e60b9?w=800&q=80', 'https://images.unsplash.com/photo-1730103292841-e755f3a9fb92?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1667766528699-d0d2db8e60b9?w=800&q=80',
    address: 'Ponta de São Lourenço car park, Caniçal',
    coordinates: { lat: 32.7183, lng: -16.7017 },
    hours: 'Daylight hours',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '2-3 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Windy but spectacular — bring a windproof jacket',
      'Rare island lizards visible among the rocks',
      'Turn back at Ilhéu de Fora for a good 3-hour round trip',
    ],
    tags: ['hiking', 'ocean', 'windswept', 'easy', 'peninsula'],
  },
  {
    id: 'act-paragliding',
    tab: 'activities',
    name: 'Paragliding over Arco da Calheta',
    category: 'adventure',
    description: 'Soar above dramatic coastal cliffs and turquoise waters on a tandem paragliding flight with bird\'s-eye views of Madeira\'s south coast.',
    photos: ['https://images.unsplash.com/photo-1667766417150-07497849e810?w=800&q=80', 'https://images.unsplash.com/photo-1721241844238-bf5b0f099bbd?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1667766417150-07497849e810?w=800&q=80',
    address: 'Arco da Calheta, Calheta',
    coordinates: { lat: 32.7483, lng: -17.1550 },
    hours: 'Morning flights (weather dependent)',
    costEstimate: '$$$',
    costNote: '€150-200 per person (tandem)',
    duration: '30-45 minutes flight',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Book in advance — weather often cancels flights',
      'Early morning flights are most stable',
      'Bring a waterproof camera for stunning aerial shots',
    ],
    tags: ['adventure', 'flying', 'adrenaline', 'views'],
  },
  {
    id: 'act-sup-calheta',
    tab: 'activities',
    name: 'Stand-up Paddleboarding in Calheta',
    category: 'water',
    description: 'Paddle along Madeira\'s golden sandy beach in the calm bay at Calheta, with views of sea cliffs and pristine turquoise waters.',
    photos: ['https://images.unsplash.com/photo-1689969935900-1214f303ea86?w=800&q=80', 'https://images.unsplash.com/photo-1635896076856-a78d60420ffa?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1689969935900-1214f303ea86?w=800&q=80',
    address: 'Calheta Beach, Calheta',
    coordinates: { lat: 32.7400, lng: -17.1633 },
    hours: '9am–6pm',
    costEstimate: '$$',
    costNote: '€30 per hour (board & padddle rental)',
    duration: '1-2 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Calheta has the calmest, warmest waters in Madeira',
      'Early morning for glassier conditions',
      'Rent from beachside schools for instruction',
    ],
    tags: ['water sports', 'beach', 'paddling', 'easy'],
  },
  {
    id: 'act-scuba-garajau',
    tab: 'activities',
    name: 'Scuba Diving Garajau Reserve',
    category: 'water',
    description: 'Dive in a protected marine reserve teeming with colorful fish, octopus, and pristine coral gardens off the sunny south coast.',
    photos: ['https://images.unsplash.com/photo-1690483708344-fb9e8d7078b9?w=800&q=80', 'https://images.unsplash.com/photo-1687174991688-4253fd6a5701?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1690483708344-fb9e8d7078b9?w=800&q=80',
    address: 'Garajau Marine Reserve, Caniçal',
    coordinates: { lat: 32.6383, lng: -16.8483 },
    hours: 'Morning dives 9am–12pm',
    costEstimate: '$$',
    costNote: '€60-80 per dive (equipment included)',
    duration: '3 hours (including briefing)',
    difficulty: 'moderate',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Certification required or book a discovery dive',
      'Best visibility in summer months',
      'Depths range from 12-35 meters',
    ],
    tags: ['diving', 'marine life', 'underwater', 'reserve'],
  },
  {
    id: 'act-jeep-safari',
    tab: 'activities',
    name: 'Jeep Safari Mountain Tour',
    category: 'adventure',
    description: 'Off-road 4x4 adventure exploring mountain villages, cloud forests, and panoramic viewpoints inaccessible by regular vehicles.',
    photos: ['https://images.unsplash.com/photo-1690483708094-fa59a7f9ff21?w=800&q=80', 'https://images.unsplash.com/photo-1625216616521-6a6a78f3ee0b?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1690483708094-fa59a7f9ff21?w=800&q=80',
    address: 'Various tour operators, Funchal',
    coordinates: { lat: 32.6461, lng: -16.9108 },
    hours: '8am–5pm (full day tours)',
    costEstimate: '$$',
    costNote: '€70-100 per person (includes lunch)',
    duration: '8 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Combines hiking, cultural visits, and scenic drives',
      'Lunch typically at a traditional mountain restaurant',
      'Hotel pickup/dropoff usually included',
    ],
    tags: ['jeep', 'adventure', 'mountains', 'cultural'],
  },
  {
    id: 'act-fishing-charter',
    tab: 'activities',
    name: 'Big Game Fishing Charter',
    category: 'water',
    description: 'Deep-sea fishing charter for marlin, tuna, wahoo, and dorado in the productive waters off Madeira\'s south coast.',
    photos: ['https://images.unsplash.com/photo-1622048235741-41e882ee42bc?w=800&q=80', 'https://images.unsplash.com/photo-1697563289350-9b24dce0a097?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1622048235741-41e882ee42bc?w=800&q=80',
    address: 'Funchal Marina',
    coordinates: { lat: 32.6431, lng: -16.9106 },
    hours: '7am–4pm',
    costEstimate: '$$$',
    costNote: '€400-600 per boat (up to 4 people)',
    duration: '8-9 hours',
    difficulty: 'moderate',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Summer (June–Oct) best for marlin season',
      'Bring sunscreen, hat, and motion sickness medication',
      'Most boats include tackle and all equipment',
    ],
    tags: ['fishing', 'ocean', 'adventure', 'boat'],
  },
  {
    id: 'act-surfing-porto-cruz',
    tab: 'activities',
    name: 'Surfing at Porto da Cruz',
    category: 'water',
    description: 'Catch Atlantic swells at Madeira\'s premier north coast break with consistent waves and a scenic amphitheater of cliffs.',
    photos: ['https://images.unsplash.com/photo-1631715680382-7ac8f0eb4042?w=800&q=80', 'https://images.unsplash.com/photo-1711798383580-cd74e18511ea?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1631715680382-7ac8f0eb4042?w=800&q=80',
    address: 'Porto da Cruz Beach, Porto da Cruz',
    coordinates: { lat: 32.8033, lng: -16.7467 },
    hours: 'Daylight hours',
    costEstimate: '$$',
    costNote: '€30-50 per day (board rental + instruction)',
    duration: '2-4 hours',
    difficulty: 'moderate',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Winter (Oct–Mar) has bigger swells',
      'Water is cool year-round — bring a wetsuit',
      'Local schools offer lessons for beginners',
    ],
    tags: ['surfing', 'water sports', 'beach', 'waves'],
  },
  {
    id: 'act-poncha-tasting',
    tab: 'activities',
    name: 'Poncha Tasting Crawl in Câmara de Lobos',
    category: 'food & drink',
    description: 'Bar hop through picturesque fishing village sampling Madeira\'s iconic sugarcane spirit served warm with honey, lemon, and spices.',
    photos: ['https://images.unsplash.com/photo-1734631620517-0a8bd80756f4?w=800&q=80', 'https://images.unsplash.com/photo-1725992204983-b67b2c9b6ab2?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1734631620517-0a8bd80756f4?w=800&q=80',
    address: 'Câmara de Lobos waterfront',
    coordinates: { lat: 32.6483, lng: -17.0017 },
    hours: '10am–11pm',
    costEstimate: '$',
    costNote: '€4-8 per drink',
    duration: '2-3 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Poncha is strong — pace yourself with food',
      'Try the honey and lemon version (poncha de mel)',
      'Visit at sunset for the fishermen unloading their catch',
    ],
    tags: ['drink', 'cultural', 'village', 'local'],
  },
  {
    id: 'act-cooking-class',
    tab: 'activities',
    name: 'Traditional Madeiran Cooking Class',
    category: 'food & drink',
    description: 'Hands-on cooking class preparing authentic Madeiran dishes like tuna, espetada, and passion fruit desserts with a local chef.',
    photos: ['https://images.unsplash.com/photo-1674948169926-ee93fb9641de?w=800&q=80', 'https://images.unsplash.com/photo-1610989569039-3dc4c344767b?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1674948169926-ee93fb9641de?w=800&q=80',
    address: 'Various locations in Funchal',
    coordinates: { lat: 32.6461, lng: -16.9108 },
    hours: '10am–2pm or 5pm–9pm',
    costEstimate: '$$',
    costNote: '€55-80 per person (includes lunch/dinner)',
    duration: '3 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Classes include market tour and wine pairings',
      'English-speaking instructors available',
      'Recipes provided to recreate at home',
    ],
    tags: ['cooking', 'culture', 'food', 'experience'],
  },
  {
    id: 'act-levada-rei',
    tab: 'activities',
    name: 'Levada do Rei Walk (PR18)',
    category: 'hiking',
    description: 'A peaceful water channel walk through green valleys with minimal elevation gain, perfect for mixed fitness levels.',
    photos: ['https://images.unsplash.com/photo-1612427849005-10994e6eec4c?w=800&q=80', 'https://images.unsplash.com/photo-1616878031706-b124365b4869?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1612427849005-10994e6eec4c?w=800&q=80',
    address: 'Santo da Serra, Santo da Serra',
    coordinates: { lat: 32.7233, lng: -16.8550 },
    hours: 'Daylight hours',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '2 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Ideal for families and older hikers',
      'Picnic areas along the route',
      'Rural villages offer refreshments midway',
    ],
    tags: ['levada', 'hiking', 'easy', 'family-friendly'],
  },
  {
    id: 'act-mountain-biking',
    tab: 'activities',
    name: 'Mountain Biking Downhill Adventure',
    category: 'adventure',
    description: 'Ride forest trails and mountain paths down from high elevation, ending at coastal viewpoints with expert guides.',
    photos: ['https://images.unsplash.com/photo-1667766465010-41c5c5eab9ce?w=800&q=80', 'https://images.unsplash.com/photo-1690483707714-431c204032a2?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1667766465010-41c5c5eab9ce?w=800&q=80',
    address: 'Pico do Arieiro, mountain tours',
    coordinates: { lat: 32.7356, lng: -16.9281 },
    hours: '8am–4pm',
    costEstimate: '$$',
    costNote: '€50-70 per person (bike rental included)',
    duration: '4-5 hours',
    difficulty: 'moderate',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'No climbing — mostly downhill and flat',
      'Suitable for intermediate riders',
      'Protective gear provided',
    ],
    tags: ['biking', 'adventure', 'downhill', 'guided'],
  },
  {
    id: 'act-kayaking',
    tab: 'activities',
    name: 'Kayaking Along Sea Cliffs',
    category: 'water',
    description: 'Paddle along dramatic sea cliffs spotting seabirds, sea caves, and hidden coves on Madeira\'s pristine northern coast.',
    photos: ['https://images.unsplash.com/photo-1721241843748-24202060eb45?w=800&q=80', 'https://images.unsplash.com/photo-1735463256774-d8624f54448b?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1721241843748-24202060eb45?w=800&q=80',
    address: 'São Vicente Marine Tours departure point',
    coordinates: { lat: 32.7733, lng: -17.0267 },
    hours: '9am–3pm',
    costEstimate: '$$',
    costNote: '€45-60 per person (includes guide & equipment)',
    duration: '3 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Morning departures have calmer waters',
      'Snorkeling stops included in most tours',
      'No kayaking experience needed',
    ],
    tags: ['kayaking', 'water', 'coastal', 'wildlife'],
  },
  {
    id: 'act-catamaran-sunset',
    tab: 'activities',
    name: 'Sunset Catamaran Cruise',
    category: 'water',
    description: 'Relax on a sailing catamaran watching the Atlantic sunset with refreshments, often including live music and dolphin spotting.',
    photos: ['https://images.unsplash.com/photo-1725992245371-a822cff4e2d0?w=800&q=80', 'https://images.unsplash.com/photo-1632389448299-21bb362faf29?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1725992245371-a822cff4e2d0?w=800&q=80',
    address: 'Funchal Marina',
    coordinates: { lat: 32.6431, lng: -16.9106 },
    hours: '5pm–8pm (seasonal)',
    costEstimate: '$$',
    costNote: '€35-50 per person',
    duration: '3 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Book 2-3 days in advance in high season',
      'Bring a light jacket for evening breezes',
      'Stunning photo opportunities with the sunset',
    ],
    tags: ['boat', 'sunset', 'romantic', 'relaxation'],
  },
  {
    id: 'act-film-experience',
    tab: 'activities',
    name: 'Madeira Film Experience',
    category: 'culture',
    description: 'Interactive cinema exhibition showcasing Madeira\'s history, landscape, and culture through immersive digital presentations.',
    photos: ['https://images.unsplash.com/photo-1510739628590-0c601822e0a0?w=800&q=80', 'https://images.unsplash.com/photo-1609870445811-7446dbae8b94?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1510739628590-0c601822e0a0?w=800&q=80',
    address: 'Madeira Film Experience, Rua Don Carlos I, Funchal',
    coordinates: { lat: 32.6475, lng: -16.9089 },
    hours: '10am–8pm',
    costEstimate: '$',
    costNote: '€8 adults / €5 children',
    duration: '45 minutes',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: 'https://www.madeirafilmexperience.com',
    bookingUrl: null,
    tips: [
      'Great for rainy days',
      'Multiple language options available',
      'Combines 5 different cinematic experiences',
    ],
    tags: ['culture', 'film', 'indoor', 'history'],
  },
  {
    id: 'act-levada-furado',
    tab: 'activities',
    name: 'Levada do Furado (PR10)',
    category: 'hiking',
    description: 'Water channel walk through laurel forests connecting two valleys with small waterfalls and lush vegetation on each side.',
    photos: ['https://images.unsplash.com/photo-1689349666953-e8d81553fda2?w=800&q=80', 'https://images.unsplash.com/photo-1722608036686-500ce069c264?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1689349666953-e8d81553fda2?w=800&q=80',
    address: 'Santana Parish, Santana',
    coordinates: { lat: 32.7633, lng: -16.8817 },
    hours: 'Daylight hours',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '2.5 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Both directions equally scenic',
      'Swimming possible in forest pools',
      'Less crowded than Levada dos Balcões',
    ],
    tags: ['levada', 'hiking', 'easy', 'forest'],
  },
  {
    id: 'act-trail-running',
    tab: 'activities',
    name: 'Trail Running at Encumeada Pass',
    category: 'adventure',
    description: 'Run high-altitude mountain trails with panoramic views and downhill sections perfect for trail runners of intermediate level.',
    photos: ['https://images.unsplash.com/photo-1605117665076-e5508ce98164?w=800&q=80', 'https://images.unsplash.com/photo-1644770871378-8cfd55dccd30?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1605117665076-e5508ce98164?w=800&q=80',
    address: 'Encumeada Pass, West Madeira',
    coordinates: { lat: 32.7617, lng: -17.0433 },
    hours: 'Early morning (7am–10am)',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '1.5-2 hours',
    difficulty: 'moderate',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Start very early before clouds roll in',
      'Bring electrolytes for high altitude',
      'Trail can be muddy after rain',
    ],
    tags: ['running', 'trail', 'mountain', 'adventure'],
  },
  {
    id: 'act-coasteering',
    tab: 'activities',
    name: 'Coasteering in Machico',
    category: 'adventure',
    description: 'Scramble over rocks, jump into sea caves, and swim along dramatic cliffs in this outdoor adventure combining climbing and water activity.',
    photos: ['https://images.unsplash.com/photo-1630324111397-0463bbd27145?w=800&q=80', 'https://images.unsplash.com/photo-1688669546785-3c06792e10e1?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1630324111397-0463bbd27145?w=800&q=80',
    address: 'Machico waterfront, Machico',
    coordinates: { lat: 32.7267, lng: -16.7717 },
    hours: '9am–4pm (weather dependent)',
    costEstimate: '$$',
    costNote: '€50-65 per person (includes guide & equipment)',
    duration: '3 hours',
    difficulty: 'moderate',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Good swimming ability required',
      'Wetsuits and helmets provided',
      'Scrambling, not technical climbing',
    ],
    tags: ['adventure', 'water', 'climbing', 'guided'],
  },
  {
    id: 'act-botanical-cable-car',
    tab: 'activities',
    name: 'Botanical Garden & Cable Car Ride',
    category: 'experience',
    description: 'Explore tropical plants from five continents in lush gardens, then take the cable car ride down to the coastal village of Babosas.',
    photos: ['https://images.unsplash.com/photo-1510739628590-0c601822e0a0?w=800&q=80', 'https://images.unsplash.com/photo-1609870445811-7446dbae8b94?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1510739628590-0c601822e0a0?w=800&q=80',
    address: 'Funchal Botanical Garden, Funchal',
    coordinates: { lat: 32.6389, lng: -16.9022 },
    hours: '9am–6pm',
    costEstimate: '$$',
    costNote: '€15 garden / €8 cable car (or €20 combined)',
    duration: '2 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: '+351 291 211 200',
    website: 'https://www.jardimbotanicofunchal.com',
    bookingUrl: null,
    tips: [
      'Cable car offers stunning views down to the coast',
      'Garden has many shaded rest areas',
      'Restaurant on-site with sea views',
    ],
    tags: ['garden', 'cable car', 'experience', 'views'],
  },
  {
    id: 'act-espetada-bbq',
    tab: 'activities',
    name: 'Traditional Espetada BBQ Experience',
    category: 'food & drink',
    description: 'Feast on grilled meat skewers prepared over wood fire at a traditional mountain restaurant with panoramic island views.',
    photos: ['https://images.unsplash.com/photo-1714136180128-00905ac71ee7?w=800&q=80', 'https://images.unsplash.com/photo-1674994035340-04635d2bf54d?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1714136180128-00905ac71ee7?w=800&q=80',
    address: 'Various mountain restaurants throughout Madeira',
    coordinates: { lat: 32.7100, lng: -16.9500 },
    hours: '12pm–11pm',
    costEstimate: '$$',
    costNote: '€20-30 per person (meat + sides)',
    duration: '1.5-2 hours',
    difficulty: 'easy',
    bookingRequired: true,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'Espetada is made with beef, garlic, and bay leaves',
      'Served with maize bread and sweet potato',
      'Reserve at mountain pousadas for best experience',
    ],
    tags: ['food', 'bbq', 'traditional', 'cultural'],
  },
  {
    id: 'act-snorkeling-garajau',
    tab: 'activities',
    name: 'Snorkeling at Praia de Garajau',
    category: 'water',
    description: 'Swim among colorful fish and octopus in crystal-clear waters at a protected marine reserve ideal for beginner snorkelers.',
    photos: ['https://images.unsplash.com/photo-1602135399239-245bfd831499?w=800&q=80', 'https://images.unsplash.com/photo-1662311238730-c506789606b2?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1602135399239-245bfd831499?w=800&q=80',
    address: 'Praia de Garajau, Caniçal',
    coordinates: { lat: 32.6383, lng: -16.8483 },
    hours: '9am–5pm',
    costEstimate: '$',
    costNote: '€5-10 equipment rental',
    duration: '1-2 hours',
    difficulty: 'easy',
    bookingRequired: false,
    phone: null,
    website: null,
    bookingUrl: null,
    tips: [
      'One of Madeira\'s warmest and clearest spots',
      'Bring reef-safe sunscreen',
      'Lifeguards on duty during summer',
    ],
    tags: ['snorkeling', 'water', 'marine life', 'easy'],
  },
];

export default activities;
