/**
 * Activities and things to do in Madeira.
 */

const activities = [
  {
    id: 'act-levada-balcoes',
    name: 'Levada dos Balcões Walk',
    category: 'hiking',
    duration: '1.5 hours',
    difficulty: 'easy',
    description: 'A gentle levada walk through the laurel forest ending at a breathtaking viewpoint over the Ribeira da Metade valley.',
    coordinates: { lat: 32.7500, lng: -16.8833 },
    image: null,
    bookingRequired: false,
    estimatedCost: 'Free',
  },
  {
    id: 'act-toboggan',
    name: 'Monte Toboggan Ride',
    category: 'experience',
    duration: '10 minutes',
    difficulty: 'easy',
    description: 'Traditional wicker basket sledge ride down the steep streets from Monte to Livramento, steered by carreiros in white.',
    coordinates: { lat: 32.6675, lng: -16.9031 },
    image: null,
    bookingRequired: false,
    estimatedCost: '€30 per pair',
  },
  {
    id: 'act-pr1-trail',
    name: 'PR1 Pico do Arieiro to Pico Ruivo',
    category: 'hiking',
    duration: '5-6 hours',
    difficulty: 'moderate',
    description: 'Madeira\'s most spectacular mountain trail connecting the two highest peaks along a dramatic ridge line above the clouds.',
    coordinates: { lat: 32.7356, lng: -16.9281 },
    image: null,
    bookingRequired: false,
    estimatedCost: 'Free',
  },
  {
    id: 'act-wine-tour',
    name: 'Blandy\'s Wine Lodge Tour',
    category: 'food & drink',
    duration: '1.5 hours',
    difficulty: 'easy',
    description: 'Tour the historic wine lodge in Funchal, learn about Madeira wine production, and taste several vintages.',
    coordinates: { lat: 32.6461, lng: -16.9108 },
    image: null,
    bookingRequired: true,
    estimatedCost: '€15-35',
  },
  {
    id: 'act-dolphin-watch',
    name: 'Dolphin & Whale Watching',
    category: 'water',
    duration: '3 hours',
    difficulty: 'easy',
    description: 'Boat trip from Funchal marina to spot bottlenose dolphins, pilot whales, and — if lucky — sperm whales in the deep Atlantic waters.',
    coordinates: { lat: 32.6431, lng: -16.9106 },
    image: null,
    bookingRequired: true,
    estimatedCost: '€40-55',
  },
  {
    id: 'act-canyoning',
    name: 'Canyoning in Ribeira das Cales',
    category: 'adventure',
    duration: '4 hours',
    difficulty: 'moderate',
    description: 'Descend through waterfalls, natural slides, and jump pools in one of Madeira\'s lush canyon systems with expert guides.',
    coordinates: { lat: 32.7600, lng: -17.0200 },
    image: null,
    bookingRequired: true,
    estimatedCost: '€55',
  },
];

export default activities;
