const activities = [
  {
    id: 'act-levada-balcoes',
    tab: 'activities',
    name: 'Levada dos Balcões Walk',
    category: 'hiking',
    description: 'A gentle levada walk through the laurel forest ending at a breathtaking viewpoint over the Ribeira da Metade valley.',
    photos: [],
    heroPhoto: null,
    address: 'Ribeiro Frio, Santana',
    coordinates: { lat: 32.7500, lng: -16.8833 },
    hours: 'Daylight hours',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '1.5 hours',
    difficulty: 'easy',
    bookingRequired: false,
    tips: [
      'Starts from the Ribeiro Frio forestry park — easy to find',
      'Flat the entire way with levada alongside',
      'The viewpoint at the end often has firecrest birds',
    ],
    tags: ['levada', 'hiking', 'easy', 'nature', 'free'],
  },
  {
    id: 'act-toboggan',
    tab: 'activities',
    name: 'Monte Toboggan Ride',
    category: 'experience',
    description: 'Traditional wicker basket sledge ride down the steep streets from Monte to Livramento, steered by carreiros in white.',
    photos: [],
    heroPhoto: null,
    address: 'Largo da Fonte, Monte, Funchal',
    coordinates: { lat: 32.6675, lng: -16.9031 },
    hours: 'Mon–Sat 9am–6pm',
    closedOn: 'Sunday',
    costEstimate: '$$',
    costNote: '€30 for 2 people / €25 for 1 person',
    duration: '10-15 min ride',
    difficulty: 'easy',
    bookingRequired: false,
    tips: [
      'The ride is about 2 km downhill — exhilarating!',
      'Pair it with the Monte Palace Garden visit',
      'Cash only for the ride',
    ],
    tags: ['iconic', 'unique', 'monte', 'fun'],
  },
  {
    id: 'act-pr1-trail',
    tab: 'activities',
    name: 'PR1 Pico do Arieiro to Pico Ruivo',
    category: 'hiking',
    description: 'Madeira\'s most spectacular mountain trail connecting the two highest peaks along a dramatic ridge line above the clouds.',
    photos: [],
    heroPhoto: null,
    address: 'Pico do Arieiro car park',
    coordinates: { lat: 32.7356, lng: -16.9281 },
    hours: 'Daylight hours (start early)',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '5-6 hours',
    difficulty: 'moderate',
    bookingRequired: false,
    tips: [
      'Start before sunrise for magical light',
      'Bring headlamp for the tunnels, water, and layers',
      'Return the same way or arrange a taxi pickup at Achada do Teixeira',
    ],
    tags: ['hiking', 'mountain', 'sunrise', 'challenging', 'scenic'],
  },
  {
    id: 'act-wine-tour',
    tab: 'activities',
    name: 'Blandy\'s Wine Lodge Tour',
    category: 'food & drink',
    description: 'Tour the historic wine lodge in Funchal, learn about Madeira wine production, and taste several vintages.',
    photos: [],
    heroPhoto: null,
    address: 'Avenida Arriaga 28, Funchal',
    coordinates: { lat: 32.6461, lng: -16.9108 },
    hours: 'Mon–Fri 10am–6:30pm, Sat 10am–1pm',
    closedOn: 'Sunday',
    costEstimate: '$$',
    costNote: '€15 standard / €25 premium / €35 vintage tasting',
    duration: '1.5 hours',
    difficulty: 'easy',
    phone: '+351 291 228 978',
    website: 'https://www.bfrancis.com/visits',
    bookingRequired: true,
    bookingUrl: 'https://www.bfrancis.com/visits',
    tips: [
      'Book the premium tasting — the vintage wines are worth it',
      'The cellar dates back to 1811',
      'Buy wine here rather than souvenir shops — better selection and prices',
    ],
    tags: ['wine', 'tasting', 'culture', 'funchal'],
  },
  {
    id: 'act-dolphin-watch',
    tab: 'activities',
    name: 'Dolphin & Whale Watching',
    category: 'water',
    description: 'Boat trip from Funchal marina to spot bottlenose dolphins, pilot whales, and — if lucky — sperm whales in the deep Atlantic waters.',
    photos: [],
    heroPhoto: null,
    address: 'Funchal Marina',
    coordinates: { lat: 32.6431, lng: -16.9106 },
    hours: 'Departures 10am & 3pm (seasonal)',
    costEstimate: '$$',
    costNote: '€40-55 per person',
    duration: '3 hours',
    difficulty: 'easy',
    bookingRequired: true,
    tips: [
      'Morning trips tend to have calmer seas',
      'Bring sunscreen and a light jacket — it\'s windier on the water',
      'Most operators guarantee a second trip free if no sightings',
    ],
    tags: ['boat', 'wildlife', 'ocean', 'dolphins', 'whales'],
  },
  {
    id: 'act-canyoning',
    tab: 'activities',
    name: 'Canyoning in Ribeira das Cales',
    category: 'adventure',
    description: 'Descend through waterfalls, natural slides, and jump pools in one of Madeira\'s lush canyon systems with expert guides.',
    photos: [],
    heroPhoto: null,
    address: 'Ribeira das Cales, São Vicente',
    coordinates: { lat: 32.7600, lng: -17.0200 },
    hours: 'By appointment',
    costEstimate: '$$',
    costNote: '€55 per person (equipment included)',
    duration: '4 hours (including transport)',
    difficulty: 'moderate',
    bookingRequired: true,
    tips: [
      'No experience needed — guides handle all rope work',
      'Wear swimwear under clothes; wetsuit provided',
      'Waterproof camera recommended',
    ],
    tags: ['adventure', 'waterfall', 'outdoor', 'guided'],
  },
];

export default activities;
