/**
 * Places to eat in Madeira.
 */

const eat = [
  {
    id: 'eat-abrigo-pastor',
    tab: 'eat',
    name: 'Abrigo do Pastor',
    category: 'traditional',
    description: 'Rustic mountain restaurant famous for espetada — beef skewered on laurel wood sticks and hung over the table. A true Madeiran experience.',
    photos: [],
    heroPhoto: null,
    address: 'Estrada Regional 203, Eira do Serrado',
    coordinates: { lat: 32.7186, lng: -16.9475 },
    hours: '12pm – 10pm daily',
    costEstimate: '$$',
    costNote: '€15-25 per person',
    phone: '+351 291 741 617',
    website: null,
    bookingRequired: true,
    tips: [
      'Order the espetada — it\'s the reason to come',
      'Book ahead for weekend dinners',
      'The terrace has stunning valley views',
    ],
    tags: ['traditional', 'espetada', 'mountain', 'views'],
  },
  {
    id: 'eat-gaviao-novo',
    tab: 'eat',
    name: 'Gavião Novo',
    category: 'seafood',
    description: 'No-frills seafood institution in the Old Town. Known for limpets (lapas), grilled fish, and an authentic local atmosphere.',
    photos: [],
    heroPhoto: null,
    address: 'Rua de Santa Maria 131, Funchal',
    coordinates: { lat: 32.6450, lng: -16.9015 },
    hours: '12pm – 11pm, closed Wednesdays',
    closedOn: 'Wednesday',
    costEstimate: '$$',
    costNote: '€12-22 per person',
    phone: '+351 291 229 238',
    website: null,
    bookingRequired: false,
    tips: [
      'Try the lapas (limpets grilled with garlic butter)',
      'Cash preferred',
      'Busy at lunch — go early or expect a short wait',
    ],
    tags: ['seafood', 'local', 'old town', 'casual'],
  },
  {
    id: 'eat-il-gallo-doro',
    tab: 'eat',
    name: 'Il Gallo d\'Oro',
    category: 'fine dining',
    description: 'Two Michelin-starred restaurant at The Cliff Bay hotel, blending Portuguese ingredients with French technique. Chef Benoît Sinthon.',
    photos: [],
    heroPhoto: null,
    address: 'The Cliff Bay, Estrada Monumental 147, Funchal',
    coordinates: { lat: 32.6369, lng: -16.9353 },
    hours: '7pm – 10pm, Tue–Sat',
    closedOn: 'Sunday, Monday',
    costEstimate: '$$$$',
    costNote: '€120-180 tasting menu',
    phone: '+351 291 707 700',
    website: 'https://www.portobay.com/en/dining/il-gallo-doro/',
    bookingRequired: true,
    bookingUrl: 'https://www.portobay.com/en/dining/il-gallo-doro/',
    tips: [
      'Book at least a week ahead',
      'The tasting menu with wine pairing is outstanding',
      'Smart casual dress code',
    ],
    tags: ['michelin', 'fine dining', 'tasting menu', 'special occasion'],
  },
  {
    id: 'eat-venda-donna',
    tab: 'eat',
    name: 'Venda da Donna Maria',
    category: 'traditional',
    description: 'Hidden gem in São Vicente serving homestyle Madeiran cooking. Small menu that changes daily based on what\'s fresh.',
    photos: [],
    heroPhoto: null,
    address: 'Sítio do Passo, São Vicente',
    coordinates: { lat: 32.7953, lng: -17.0408 },
    hours: '12pm – 3pm, 7pm – 9pm',
    costEstimate: '$',
    costNote: '€8-14 per person',
    phone: '+351 291 842 957',
    website: null,
    bookingRequired: false,
    tips: [
      'Menu is whatever Donna Maria cooked that day — just say yes',
      'BYOB or try the house wine',
      'Pair with a visit to the São Vicente volcanic caves',
    ],
    tags: ['homestyle', 'budget', 'local', 'north coast'],
  },
  {
    id: 'eat-rei-carne',
    tab: 'eat',
    name: 'O Rei da Carne',
    category: 'grill',
    description: 'The "King of Meat" — a no-fuss spot popular with locals for massive espetada portions and house wine served in ceramic jugs.',
    photos: [],
    heroPhoto: null,
    address: 'Rua do Bom Jesus, Santo António, Funchal',
    coordinates: { lat: 32.6608, lng: -16.9250 },
    hours: '11am – 10pm daily',
    costEstimate: '$',
    costNote: '€10-18 per person',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Portions are enormous — one espetada easily feeds two',
      'House red wine in ceramic jugs is part of the charm',
      'More locals than tourists — always a good sign',
    ],
    tags: ['meat', 'espetada', 'budget', 'local'],
  },
];

export default eat;
