const see = [
  {
    id: 'see-cabo-girao',
    tab: 'see',
    name: 'Cabo Girão Skywalk',
    category: 'viewpoint',
    description: 'One of the highest sea cliffs in Europe at 580 m, with a glass-floor skywalk offering vertigo-inducing views of the terraced vineyards below.',
    photos: [],
    heroPhoto: null,
    address: 'Cabo Girão, Câmara de Lobos',
    coordinates: { lat: 32.6569, lng: -17.0097 },
    hours: 'Open 24 hours (skywalk area)',
    costEstimate: 'Free',
    costNote: 'Free entry',
    duration: '30-45 min',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Go early morning to avoid tour bus crowds',
      'The glass floor can be slippery when wet',
      'Small café at the top for espresso with a view',
    ],
    tags: ['viewpoint', 'free', 'iconic', 'cliff'],
  },
  {
    id: 'see-monte-palace',
    tab: 'see',
    name: 'Monte Palace Tropical Garden',
    category: 'garden',
    description: 'A lush 70,000 m² garden above Funchal with exotic plants, koi ponds, and a tile collection spanning six centuries.',
    photos: [],
    heroPhoto: null,
    address: 'Caminho do Monte 174, Funchal',
    coordinates: { lat: 32.6681, lng: -16.9022 },
    hours: '9:30am – 6pm daily (last entry 5:30pm)',
    costEstimate: '$$',
    costNote: '€12.50 adults / €3.50 children',
    duration: '2-3 hours',
    phone: '+351 291 780 800',
    website: 'https://montepalace.com',
    bookingRequired: false,
    tips: [
      'Take the Funchal cable car up, then walk down or take the toboggan',
      'Don\'t miss the underground mineral collection',
      'The oriental gardens are the most photogenic section',
    ],
    tags: ['garden', 'museum', 'cable car', 'monte'],
  },
  {
    id: 'see-pico-ruivo',
    tab: 'see',
    name: 'Pico Ruivo',
    category: 'nature',
    description: 'Madeira\'s highest peak at 1,862 m. Accessible via the iconic PR1 trail from Pico do Arieiro with stunning ridge-line views above the clouds.',
    photos: [],
    heroPhoto: null,
    address: 'Pico Ruivo, Santana',
    coordinates: { lat: 32.7603, lng: -16.9453 },
    hours: 'Open 24 hours (outdoor)',
    costEstimate: 'Free',
    costNote: 'Free',
    duration: '5-6 hours round trip via PR1',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Start before sunrise at Pico do Arieiro for the best light',
      'Bring layers — temperature drops significantly at altitude',
      'The shorter route from Achada do Teixeira is 1.5 hours return',
    ],
    tags: ['summit', 'hiking', 'sunrise', 'mountain'],
  },
  {
    id: 'see-zona-velha',
    tab: 'see',
    name: 'Zona Velha (Old Town)',
    category: 'culture',
    description: 'Funchal\'s historic quarter with cobblestone streets, painted doors by local artists, and a lively restaurant scene.',
    photos: [],
    heroPhoto: null,
    address: 'Rua de Santa Maria, Funchal',
    coordinates: { lat: 32.6450, lng: -16.9020 },
    hours: 'Always open (outdoor area)',
    costEstimate: 'Free',
    costNote: 'Free to explore; restaurants vary',
    duration: '1-2 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Best in the evening when restaurants and bars come alive',
      'Look for the "Art of Open Doors" painted doorways along Rua de Santa Maria',
      'Friday and Saturday nights have live fado music at several spots',
    ],
    tags: ['old town', 'nightlife', 'art', 'restaurants', 'free'],
  },
  {
    id: 'see-porto-moniz',
    tab: 'see',
    name: 'Porto Moniz Natural Pools',
    category: 'nature',
    description: 'Volcanic rock pools filled by the Atlantic on the northwest coast — a natural swimming experience unlike any other.',
    photos: [],
    heroPhoto: null,
    address: 'Porto Moniz, Madeira',
    coordinates: { lat: 32.8667, lng: -17.1667 },
    hours: '9am – 7pm (summer) / 9am – 5pm (winter)',
    closedOn: 'Open daily in summer; check winter schedule',
    costEstimate: '$',
    costNote: '€3 adults (managed pools) / Free (natural pools)',
    duration: '2-3 hours',
    phone: '+351 291 850 190',
    website: null,
    bookingRequired: false,
    tips: [
      'Bring water shoes — volcanic rock is sharp',
      'The natural pools (free) are just west of the managed complex',
      'Combine with a scenic drive along the north coast',
    ],
    tags: ['swimming', 'volcanic', 'natural pools', 'north coast'],
  },
  {
    id: 'see-mercado',
    tab: 'see',
    name: 'Mercado dos Lavradores',
    category: 'market',
    description: 'Funchal\'s vibrant farmers\' market filled with tropical fruit, fresh flowers, and a lively fish hall on the lower level.',
    photos: [],
    heroPhoto: null,
    address: 'Rua Latino Coelho 39, Funchal',
    coordinates: { lat: 32.6486, lng: -16.9053 },
    hours: 'Mon–Fri 7am–6pm, Sat 7am–2pm',
    closedOn: 'Sunday',
    costEstimate: '$',
    costNote: 'Free entry; fruit samples free, purchases vary',
    duration: '1-1.5 hours',
    phone: null,
    website: null,
    bookingRequired: false,
    tips: [
      'Go on a weekday morning for the full experience',
      'Try passion fruit and custard apple samples — vendors offer them freely',
      'The fish hall on the lower floor is dramatic — huge black scabbard fish',
      'Don\'t buy fruit from the first vendor who approaches you; prices are higher',
    ],
    tags: ['market', 'food', 'flowers', 'fish', 'local culture'],
  },
];

export default see;
