const shop = [
  {
    id: 'shop-bordado',
    tab: 'shop',
    name: 'Madeira Embroidery (Bordado)',
    category: 'artisan',
    description: 'Hand-embroidered linens recognised worldwide. Look for the official IVBAM hologram seal to guarantee authenticity.',
    photos: [],
    heroPhoto: null,
    address: 'Patrício & Gouveia, Rua do Visconde de Anadia 34, Funchal',
    coordinates: { lat: 32.6472, lng: -16.9100 },
    hours: 'Mon–Fri 9am–12:30pm, 2pm–6pm',
    closedOn: 'Saturday, Sunday',
    costEstimate: '$$$',
    costNote: '€20-200+ depending on size and complexity',
    bookingRequired: false,
    tips: [
      'The factory shop at Patrício & Gouveia lets you see artisans at work',
      'Look for the IVBAM hologram — it guarantees authentic Madeira embroidery',
      'Table runners and napkins are popular, packable gifts',
    ],
    tags: ['artisan', 'souvenir', 'textile', 'handmade'],
  },
  {
    id: 'shop-vinho',
    tab: 'shop',
    name: 'Madeira Wine',
    category: 'food & drink',
    description: 'Fortified wine aged using the unique estufagem process. Ranges from dry Sercial to sweet Malmsey.',
    photos: [],
    heroPhoto: null,
    address: 'Blandy\'s Wine Lodge, Av. Arriaga 28, Funchal',
    coordinates: { lat: 32.6461, lng: -16.9108 },
    hours: 'Mon–Fri 10am–6:30pm, Sat 10am–1pm',
    costEstimate: '$$',
    costNote: '€8-300+ per bottle',
    bookingRequired: false,
    tips: [
      'Buy from the wine lodges rather than souvenir shops — better prices',
      '5-year-old Verdelho is a great mid-range gift',
      'Wines over 50ml can\'t go in carry-on — plan for checked luggage',
    ],
    tags: ['wine', 'souvenir', 'food', 'gift'],
  },
  {
    id: 'shop-wickerwork',
    tab: 'shop',
    name: 'Wicker Baskets & Furniture',
    category: 'artisan',
    description: 'Handwoven willow products from Camacha, Madeira\'s wicker capital since the 19th century.',
    photos: [],
    heroPhoto: null,
    address: 'Café Relógio, Largo Achada, Camacha',
    coordinates: { lat: 32.6833, lng: -16.8333 },
    hours: '9:30am–6pm daily',
    costEstimate: '$$',
    costNote: '€10-150 depending on item',
    bookingRequired: false,
    tips: [
      'The Café Relógio building has a massive showroom upstairs',
      'Small baskets and coasters are easy to pack',
      'They can ship larger furniture items internationally',
    ],
    tags: ['artisan', 'wicker', 'handmade', 'camacha'],
  },
  {
    id: 'shop-honey-cake',
    tab: 'shop',
    name: 'Bolo de Mel (Honey Cake)',
    category: 'food & drink',
    description: 'Dense, spiced molasses cake that keeps for months — a traditional Madeiran treat, especially at Christmas.',
    photos: [],
    heroPhoto: null,
    address: 'Fábrica Santo António, Travessa do Forno 27, Funchal',
    coordinates: { lat: 32.6489, lng: -16.9067 },
    hours: 'Mon–Fri 9am–7pm, Sat 9am–1pm',
    costEstimate: '$',
    costNote: '€5-15',
    bookingRequired: false,
    tips: [
      'Fábrica Santo António has been baking since 1893',
      'Keeps for weeks — great for bringing home',
      'Pair with a glass of sweet Malmsey wine',
    ],
    tags: ['food', 'cake', 'traditional', 'gift'],
  },
  {
    id: 'shop-passion-fruit',
    tab: 'shop',
    name: 'Passion Fruit Liqueur',
    category: 'food & drink',
    description: 'Made from Madeira\'s prized maracujá (passion fruit). Sweet, fragrant, and easy to pack.',
    photos: [],
    heroPhoto: null,
    address: 'Mercado dos Lavradores, Funchal',
    coordinates: { lat: 32.6486, lng: -16.9053 },
    hours: 'Mon–Fri 7am–6pm, Sat 7am–2pm',
    costEstimate: '$',
    costNote: '€8-18 per bottle',
    bookingRequired: false,
    tips: [
      'Taste before buying — sweetness varies by brand',
      'The airport duty-free often has the same bottles cheaper',
      'Also try poncha — the local rum + honey + citrus cocktail',
    ],
    tags: ['liqueur', 'souvenir', 'food', 'gift'],
  },
];

export default shop;
