const shop = [
  {
    id: 'shop-bordado',
    tab: 'shop',
    name: 'Madeira Embroidery (Bordado)',
    category: 'artisan',
    description: 'Hand-embroidered linens recognised worldwide. Look for the official IVBAM hologram seal to guarantee authenticity.',
    photos: ['https://images.unsplash.com/photo-1743485754062-b6ad79fd3278?w=800&q=80', 'https://images.unsplash.com/photo-1756792339315-db64021190be?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1767040276964-d2a39a86b1d4?w=800&q=80',
    address: 'Patrício & Gouveia, Rua do Visconde de Anadia 34, Funchal',
    coordinates: { lat: 32.6472, lng: -16.9100 },
    hours: 'Mon–Fri 9am–12:30pm, 2pm–6pm',
    closedOn: 'Saturday, Sunday',
    costEstimate: '$$$',
    costNote: '€20-200+ depending on size and complexity',
    bookingRequired: false,
    whereToBuy: ['Patrício & Gouveia factory shop', 'Funchal artisan markets'],
    tips: [
      'The factory shop at Patrício & Gouveia lets you see artisans at work',
      'Look for the IVBAM hologram — it guarantees authentic Madeira embroidery',
      'Table runners and napkins are popular, packable gifts',
    ],
    tags: ['artisan', 'souvenir', 'textile', 'handmade'],
  },
  {
    id: 'shop-vinho',
    tab: 'shop',
    name: 'Madeira Wine',
    category: 'food & drink',
    description: 'Fortified wine aged using the unique estufagem process. Ranges from dry Sercial to sweet Malmsey.',
    photos: ['https://images.unsplash.com/photo-1714136180128-00905ac71ee7?w=800&q=80', 'https://images.unsplash.com/photo-1674994035340-04635d2bf54d?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1602135399239-245bfd831499?w=800&q=80',
    address: 'Blandy\'s Wine Lodge, Av. Arriaga 28, Funchal',
    coordinates: { lat: 32.6461, lng: -16.9108 },
    hours: 'Mon–Fri 10am–6:30pm, Sat 10am–1pm',
    closedOn: 'Sunday',
    costEstimate: '$$',
    costNote: '€8-300+ per bottle',
    bookingRequired: false,
    whereToBuy: ['Blandy\'s Wine Lodge', 'Vinicola de Madeira', 'Wine shops throughout Funchal'],
    tips: [
      'Buy from the wine lodges rather than souvenir shops — better prices',
      '5-year-old Verdelho is a great mid-range gift',
      'Wines over 50ml can\'t go in carry-on — plan for checked luggage',
    ],
    tags: ['wine', 'souvenir', 'food', 'gift'],
  },
  {
    id: 'shop-wickerwork',
    tab: 'shop',
    name: 'Wicker Baskets & Furniture',
    category: 'artisan',
    description: 'Handwoven willow products from Camacha, Madeira\'s wicker capital since the 19th century.',
    photos: ['https://images.unsplash.com/photo-1772411535408-46380779fde3?w=800&q=80', 'https://images.unsplash.com/photo-1766901110596-749e419db76a?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1766933330352-81ff095ad04a?w=800&q=80',
    address: 'Café Relógio, Largo Achada, Camacha',
    coordinates: { lat: 32.6833, lng: -16.8333 },
    hours: '9:30am–6pm daily',
    costEstimate: '$$',
    costNote: '€10-150 depending on item',
    bookingRequired: false,
    whereToBuy: ['Café Relógio', 'Camacha artisan shops', 'Funchal markets'],
    tips: [
      'The Café Relógio building has a massive showroom upstairs',
      'Small baskets and coasters are easy to pack',
      'They can ship larger furniture items internationally',
    ],
    tags: ['artisan', 'wicker', 'handmade', 'camacha'],
  },
  {
    id: 'shop-honey-cake',
    tab: 'shop',
    name: 'Bolo de Mel (Honey Cake)',
    category: 'food & drink',
    description: 'Dense, spiced molasses cake that keeps for months — a traditional Madeiran treat, especially at Christmas.',
    photos: ['https://images.unsplash.com/photo-1736143157411-0a70fe999ecb?w=800&q=80', 'https://images.unsplash.com/photo-1773802551633-6068010cdaa4?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1768102365363-d20d185b331e?w=800&q=80',
    address: 'Fábrica Santo António, Travessa do Forno 27, Funchal',
    coordinates: { lat: 32.6489, lng: -16.9067 },
    hours: 'Mon–Fri 9am–7pm, Sat 9am–1pm',
    closedOn: 'Sunday',
    costEstimate: '$',
    costNote: '€5-15',
    bookingRequired: false,
    whereToBuy: ['Fábrica Santo António', 'Mercado dos Lavradores', 'Funchal bakeries'],
    tips: [
      'Fábrica Santo António has been baking since 1893',
      'Keeps for weeks — great for bringing home',
      'Pair with a glass of sweet Malmsey wine',
    ],
    tags: ['food', 'cake', 'traditional', 'gift'],
  },
  {
    id: 'shop-passion-fruit',
    tab: 'shop',
    name: 'Passion Fruit Liqueur',
    category: 'food & drink',
    description: 'Made from Madeira\'s prized maracujá (passion fruit). Sweet, fragrant, and easy to pack.',
    photos: ['https://images.unsplash.com/photo-1767039770798-89ed11c842d6?w=800&q=80', 'https://images.unsplash.com/photo-1756792340190-2039b9a1787d?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1769425158985-8452c0e54194?w=800&q=80',
    address: 'Mercado dos Lavradores, Funchal',
    coordinates: { lat: 32.6486, lng: -16.9053 },
    hours: 'Mon–Fri 7am–6pm, Sat 7am–2pm',
    closedOn: 'Sunday',
    costEstimate: '$',
    costNote: '€8-18 per bottle',
    bookingRequired: false,
    whereToBuy: ['Mercado dos Lavradores', 'Duty-free shops', 'Funchal markets'],
    tips: [
      'Taste before buying — sweetness varies by brand',
      'The airport duty-free often has the same bottles cheaper',
      'Also try poncha — the local rum + honey + citrus cocktail',
    ],
    tags: ['liqueur', 'souvenir', 'food', 'gift'],
  },
  {
    id: 'shop-poncha',
    tab: 'shop',
    name: 'Poncha (Local Cocktail)',
    category: 'food & drink',
    description: 'Traditional Madeiran drink made with aguardente (fire water), honey, and citrus. A warming, potent local favourite.',
    photos: ['https://images.unsplash.com/photo-1756792339125-51edbdb03c74?w=800&q=80', 'https://images.unsplash.com/photo-1756792339487-d044709b27f2?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1761210719325-283557e92487?w=800&q=80',
    address: 'Bars throughout Funchal, Mercado dos Lavradores',
    coordinates: { lat: 32.6486, lng: -16.9053 },
    hours: 'Varies by venue',
    costEstimate: '$',
    costNote: '€3-8 per glass',
    bookingRequired: false,
    whereToBuy: ['Local bars', 'Tavernas', 'Mercado dos Lavradores'],
    tips: [
      'Try it fresh at a local taverna — it\'s much better than bottled versions',
      'Pace yourself — it\'s stronger than it tastes',
      'Each bar has its own recipe; compare a few to find your favourite',
    ],
    tags: ['drink', 'local', 'traditional', 'souvenir'],
  },
  {
    id: 'shop-madeira-boots',
    tab: 'shop',
    name: 'Madeira Boots (Botas)',
    category: 'fashion',
    description: 'Traditional leather boots with decorative embroidery, worn for hiking and traditional celebrations. Durable and iconic.',
    photos: ['https://images.unsplash.com/photo-1743485754062-b6ad79fd3278?w=800&q=80', 'https://images.unsplash.com/photo-1756792339315-db64021190be?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1767040276964-d2a39a86b1d4?w=800&q=80',
    address: 'Funchal Old Town, Rua da Carreira',
    coordinates: { lat: 32.6465, lng: -16.9125 },
    hours: '10am–6pm daily',
    costEstimate: '$$',
    costNote: '€80-200 per pair',
    bookingRequired: false,
    whereToBuy: ['Funchal Old Town shops', 'Traditional craft markets', 'Specialty boot makers'],
    tips: [
      'Authentic botas feature hand-stitched leather and embroidery',
      'Wear in gradually — they\'re stiff and need breaking in',
      'Perfect for hiking or as a cultural souvenir',
    ],
    tags: ['fashion', 'traditional', 'handmade', 'hiking'],
  },
  {
    id: 'shop-azulejo',
    tab: 'shop',
    name: 'Azulejo Tiles',
    category: 'ceramics',
    description: 'Hand-painted Portuguese azulejo tiles with traditional blue and white patterns. Decorative and collectible.',
    photos: ['https://images.unsplash.com/photo-1672446063068-680ca91d7082?w=800&q=80', 'https://images.unsplash.com/photo-1674333362725-84e9996aa6fb?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1718621220994-c377336f6c77?w=800&q=80',
    address: 'Funchal ceramics shops, Rua do Visconde de Anadia',
    coordinates: { lat: 32.6472, lng: -16.9100 },
    hours: '10am–6pm daily',
    costEstimate: '$$',
    costNote: '€5-50 per tile',
    bookingRequired: false,
    whereToBuy: ['Ceramics shops in Funchal', 'Artisan markets', 'Museum gift shops'],
    tips: [
      'Look for hand-painted tiles — they\'re more authentic than printed ones',
      'Pack carefully with bubble wrap for travel',
      'Coasters are small, affordable, and easy to transport',
    ],
    tags: ['ceramics', 'souvenir', 'traditional', 'gift'],
  },
  {
    id: 'shop-exotic-preserves',
    tab: 'shop',
    name: 'Exotic Fruit Preserves',
    category: 'food & drink',
    description: 'Homemade jams and marmalades made from Madeira\'s tropical fruits: passion fruit, guava, papaya, and banana.',
    photos: ['https://images.unsplash.com/photo-1743485754062-b6ad79fd3278?w=800&q=80', 'https://images.unsplash.com/photo-1756792339315-db64021190be?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1767040276964-d2a39a86b1d4?w=800&q=80',
    address: 'Mercado dos Lavradores, Funchal',
    coordinates: { lat: 32.6486, lng: -16.9053 },
    hours: 'Mon–Fri 7am–6pm, Sat 7am–2pm',
    closedOn: 'Sunday',
    costEstimate: '$',
    costNote: '€4-12 per jar',
    bookingRequired: false,
    whereToBuy: ['Mercado dos Lavradores', 'Local markets', 'Artisan food shops'],
    tips: [
      'Taste samples before buying — flavours vary widely',
      'The smallest jars are perfect souvenirs and gifts',
      'Try passion fruit — it\'s a local signature flavour',
    ],
    tags: ['food', 'organic', 'local', 'gift'],
  },
  {
    id: 'shop-banana-liqueur',
    tab: 'shop',
    name: 'Banana Liqueur',
    category: 'food & drink',
    description: 'Smooth, sweet liqueur made from Madeira\'s famous bananas. A unique regional spirit with tropical notes.',
    photos: ['https://images.unsplash.com/photo-1714136180128-00905ac71ee7?w=800&q=80', 'https://images.unsplash.com/photo-1674994035340-04635d2bf54d?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1602135399239-245bfd831499?w=800&q=80',
    address: 'Duty-free shops, Wine lodges, Funchal market',
    coordinates: { lat: 32.6461, lng: -16.9108 },
    hours: 'Shop hours vary',
    costEstimate: '$',
    costNote: '€10-20 per bottle',
    bookingRequired: false,
    whereToBuy: ['Airport duty-free', 'Wine shops', 'Mercado dos Lavradores'],
    tips: [
      'Serve chilled as a digestif or mixed with desserts',
      'Smaller bottles are easy to pack',
      'Try it alongside the passion fruit liqueur for a taste comparison',
    ],
    tags: ['liqueur', 'souvenir', 'tropical', 'gift'],
  },
  {
    id: 'shop-ginja',
    tab: 'shop',
    name: 'Ginja Cherry Liqueur',
    category: 'food & drink',
    description: 'Portuguese cherry liqueur with a tart-sweet flavour. A traditional Portuguese digestif now produced in Madeira.',
    photos: ['https://images.unsplash.com/photo-1662311238730-c506789606b2?w=800&q=80', 'https://images.unsplash.com/photo-1685268213146-5b34414ab9d3?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1724184983327-8caf4b26f07b?w=800&q=80',
    address: 'Wine shops, Liquor stores, Mercado dos Lavradores',
    coordinates: { lat: 32.6486, lng: -16.9053 },
    hours: 'Shop hours vary',
    costEstimate: '$',
    costNote: '€8-15 per bottle',
    bookingRequired: false,
    whereToBuy: ['Wine shops', 'Liquor stores', 'Markets'],
    tips: [
      'Serve as a chilled digestif after meals',
      'More affordable than other Portuguese liqueurs',
      'Small bottles make perfect gifts',
    ],
    tags: ['liqueur', 'portuguese', 'souvenir', 'gift'],
  },
  {
    id: 'shop-lavender-fanal',
    tab: 'shop',
    name: 'Lavender Products from Fanal',
    category: 'beauty',
    description: 'Organic lavender oils, soaps, and cosmetics sourced from Fanal, a high-altitude plateau known for its wild lavender.',
    photos: ['https://images.unsplash.com/photo-1540308990836-5a7b1df6dc00?w=800&q=80', 'https://images.unsplash.com/photo-1604850849447-6435708cb130?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1743485754062-b6ad79fd3278?w=800&q=80',
    address: 'Funchal beauty shops, Gift shops',
    coordinates: { lat: 32.6450, lng: -16.9100 },
    hours: '10am–6pm daily',
    costEstimate: '$$',
    costNote: '€8-30 per product',
    bookingRequired: false,
    whereToBuy: ['Beauty shops', 'Gift shops', 'Organic markets'],
    tips: [
      'The essential oil is concentrated — a little goes a long way',
      'Soaps make excellent, aromatic travel souvenirs',
      'Look for 100% organic certifications',
    ],
    tags: ['beauty', 'organic', 'natural', 'gift'],
  },
  {
    id: 'shop-handmade-soap',
    tab: 'shop',
    name: 'Handmade Soap',
    category: 'beauty',
    description: 'Artisanal soaps made with local ingredients: palm oil, herbs, and essential oils. Often infused with traditional scents.',
    photos: ['https://images.unsplash.com/photo-1756792340190-2039b9a1787d?w=800&q=80', 'https://images.unsplash.com/photo-1769425158985-8452c0e54194?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1756792339125-51edbdb03c74?w=800&q=80',
    address: 'Artisan markets, Funchal Old Town',
    coordinates: { lat: 32.6465, lng: -16.9125 },
    hours: '10am–6pm daily',
    costEstimate: '$',
    costNote: '€3-8 per bar',
    bookingRequired: false,
    whereToBuy: ['Artisan markets', 'Funchal Old Town shops', 'Gift shops'],
    tips: [
      'Small bars are perfect travel sizes and gifts',
      'Natural soaps often have a shorter shelf life — use sooner rather than later',
      'Compare scents — each maker has unique blends',
    ],
    tags: ['beauty', 'artisan', 'handmade', 'natural'],
  },
  {
    id: 'shop-leather-goods',
    tab: 'shop',
    name: 'Leather Goods',
    category: 'fashion',
    description: 'Handcrafted leather belts, bags, and accessories made by local artisans. Durable, timeless pieces.',
    photos: ['https://images.unsplash.com/photo-1756792339315-db64021190be?w=800&q=80', 'https://images.unsplash.com/photo-1767040276964-d2a39a86b1d4?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1772411535408-46380779fde3?w=800&q=80',
    address: 'Funchal Old Town artisan shops',
    coordinates: { lat: 32.6465, lng: -16.9125 },
    hours: '10am–6pm daily',
    costEstimate: '$$',
    costNote: '€25-100+ depending on item',
    bookingRequired: false,
    whereToBuy: ['Funchal Old Town', 'Artisan shops', 'Markets'],
    tips: [
      'Ask the maker about the leather source and durability',
      'Simple designs age beautifully and remain timeless',
      'Wallets and belts are practical, packable gifts',
    ],
    tags: ['fashion', 'artisan', 'handmade', 'leather'],
  },
  {
    id: 'shop-coral-jewelry',
    tab: 'shop',
    name: 'Coral Jewelry',
    category: 'souvenir',
    description: 'Delicate necklaces, earrings, and bracelets made from red and pink coral harvested from Madeiran waters.',
    photos: ['https://images.unsplash.com/photo-1766901110596-749e419db76a?w=800&q=80', 'https://images.unsplash.com/photo-1766933330352-81ff095ad04a?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1736143157411-0a70fe999ecb?w=800&q=80',
    address: 'Jewelry shops, Funchal Old Town',
    coordinates: { lat: 32.6465, lng: -16.9125 },
    hours: '10am–6pm daily',
    costEstimate: '$$',
    costNote: '€15-80+ per piece',
    bookingRequired: false,
    whereToBuy: ['Jewelry shops', 'Funchal Old Town', 'Markets'],
    tips: [
      'Ask about sustainability practices — some coral is endangered',
      'Antique pieces are more valuable and often more beautiful',
      'Pairs well with traditional Madeiran dress',
    ],
    tags: ['jewelry', 'souvenir', 'maritime', 'gift'],
  },
  {
    id: 'shop-queijada',
    tab: 'shop',
    name: 'Queijada (Traditional Madeiran Cake)',
    category: 'food & drink',
    description: 'Small, custard-filled pastry tarts with a golden crust. A regional speciality from the convents of Madeira.',
    photos: ['https://images.unsplash.com/photo-1768102365363-d20d185b331e?w=800&q=80', 'https://images.unsplash.com/photo-1767039770798-89ed11c842d6?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1756792340190-2039b9a1787d?w=800&q=80',
    address: 'Bakeries, Mercado dos Lavradores, Funchal',
    coordinates: { lat: 32.6486, lng: -16.9053 },
    hours: 'Varies by bakery',
    closedOn: 'Varies',
    costEstimate: '$',
    costNote: '€1-3 per tart',
    bookingRequired: false,
    whereToBuy: ['Local bakeries', 'Mercado dos Lavradores', 'Funchal pastry shops'],
    tips: [
      'Best eaten fresh from the bakery',
      'They keep for a few days, perfect for travel snacking',
      'Buy a box to share — they\'re hard to resist',
    ],
    tags: ['food', 'cake', 'traditional', 'local'],
  },
  {
    id: 'shop-rum-agricola',
    tab: 'shop',
    name: 'Rum Agrícola',
    category: 'food & drink',
    description: 'Premium agricultural rum made from fresh sugarcane juice. A bold, smooth spirit unique to Madeira.',
    photos: ['https://images.unsplash.com/photo-1662311238730-c506789606b2?w=800&q=80', 'https://images.unsplash.com/photo-1685268213146-5b34414ab9d3?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1724184983327-8caf4b26f07b?w=800&q=80',
    address: 'Rum distilleries, Wine lodges, Duty-free',
    coordinates: { lat: 32.6461, lng: -16.9108 },
    hours: 'Shop hours vary',
    costEstimate: '$$',
    costNote: '€20-60 per bottle',
    bookingRequired: false,
    whereToBuy: ['Distillery shops', 'Wine lodges', 'Airport duty-free'],
    tips: [
      'Sip neat to appreciate the flavour — it\'s often smoother than Caribbean rums',
      'Ask for a tasting at the distillery before buying',
      'Pairs beautifully with dark chocolate',
    ],
    tags: ['spirits', 'souvenir', 'premium', 'gift'],
  },
  {
    id: 'shop-local-honey',
    tab: 'shop',
    name: 'Local Honey',
    category: 'food & drink',
    description: 'Raw, unfiltered honey from Madeiran mountain bees. Rich, complex flavour with floral and chestnut notes.',
    photos: ['https://images.unsplash.com/photo-1540308990836-5a7b1df6dc00?w=800&q=80', 'https://images.unsplash.com/photo-1604850849447-6435708cb130?w=800&q=80'],
    heroPhoto: 'https://images.unsplash.com/photo-1672446063068-680ca91d7082?w=800&q=80',
    address: 'Mercado dos Lavradores, Local farmers\' markets',
    coordinates: { lat: 32.6486, lng: -16.9053 },
    hours: 'Mon–Fri 7am–6pm, Sat 7am–2pm',
    closedOn: 'Sunday',
    costEstimate: '$',
    costNote: '€5-15 per jar',
    bookingRequired: false,
    whereToBuy: ['Mercado dos Lavradores', 'Farmers\' markets', 'Health food shops'],
    tips: [
      'Raw honey may crystallize in cool temperatures — this is normal',
      'Smaller jars (250ml) are ideal for travel and gifting',
      'Use in tea, on toast, or straight from the spoon',
    ],
    tags: ['food', 'organic', 'local', 'natural'],
  },
];

export default shop;