const sleep = [
  {
    id: 'sleep-reids',
    tab: 'sleep',
    name: 'Belmond Reid\'s Palace',
    category: 'luxury',
    isBooked: true,
    description: 'Iconic cliffside hotel since 1891, with subtropical gardens, an ocean-view spa, and impeccable service. Winston Churchill\'s favourite Madeira retreat.',
    photos: [],
    heroPhoto: null,
    address: 'Estrada Monumental 139, 9000-098 Funchal',
    coordinates: { lat: 32.6375, lng: -16.9344 },
    hours: 'Check-in 3pm / Check-out 12pm',
    costEstimate: '$$$$',
    costNote: '€350-700+ per night',
    phone: '+351 291 717 171',
    website: 'https://www.belmond.com/reids-palace-madeira',
    amenities: ['Pool', 'Spa', 'Fine dining', 'Garden', 'Ocean view', 'Tennis'],
    tips: [
      'Afternoon tea on the terrace is a must — even for non-guests',
      'Request a sea-view room on the upper floors',
      'The spa pool is heated and has stunning cliff-edge views',
    ],
    tags: ['luxury', 'historic', 'cliffside', 'spa'],
  },
  {
    id: 'sleep-savoy',
    tab: 'sleep',
    name: 'Savoy Palace',
    category: 'luxury',
    isBooked: false,
    description: 'Modern five-star with a rooftop infinity pool, multiple restaurants, and a large spa in the hotel zone.',
    photos: [],
    heroPhoto: null,
    address: 'Avenida do Infante 25, 9004-542 Funchal',
    coordinates: { lat: 32.6389, lng: -16.9306 },
    hours: 'Check-in 3pm / Check-out 12pm',
    costEstimate: '$$$$',
    costNote: '€250-500+ per night',
    phone: '+351 291 213 000',
    website: 'https://www.savoypalace.com',
    amenities: ['Rooftop pool', 'Spa', 'Multiple restaurants', 'Kids club', 'Gym'],
    tips: [
      'The rooftop bar has the best sunset views in Funchal',
      'The spa is one of the largest on the island',
    ],
    tags: ['luxury', 'modern', 'pool', 'family'],
  },
  {
    id: 'sleep-quinta',
    tab: 'sleep',
    name: 'Quinta da Casa Branca',
    category: 'boutique',
    isBooked: false,
    description: 'Boutique hotel set in a historic banana plantation estate with lush gardens and a contemporary wing.',
    photos: [],
    heroPhoto: null,
    address: 'Rua da Casa Branca 7, 9000-088 Funchal',
    coordinates: { lat: 32.6408, lng: -16.9358 },
    hours: 'Check-in 2pm / Check-out 12pm',
    costEstimate: '$$$',
    costNote: '€150-300 per night',
    phone: '+351 291 700 770',
    website: 'https://www.quintacasabranca.com',
    amenities: ['Garden', 'Pool', 'Restaurant', 'Quiet location', 'Library'],
    tips: [
      'The original manor house has the most character',
      'Beautiful breakfast served in the garden pavilion',
      'Walking distance to the hotel zone and Lido',
    ],
    tags: ['boutique', 'garden', 'quiet', 'historic estate'],
  },
];

export default sleep;
